.settings/AllTests.launch

Eclipse users won't have to enable assertions manually before running AllTests.
This is an autogenerated file. Note the second-to-last line.

AllTests launch configuration enables assertions.

---

pom.xml
src/software/amazon/ion/util/JarInfo.java
test/software/amazon/ion/util/JarInfoTest.java

Created manifest keys that are more likely to be unique. Loop through all manifest files on the classpath and retrieve jar info for the one that contains both keys. If multiple manifests are found to contain both keys, fail (to avoid the risk of giving misleading or incorrect information).
Also fixes the build time format to properly include the local offset.
Works on Mac and Linux. No Windows testing yet.

Handle encountering multiple manifests on the classpath when retrieving jar info

---

pom.xml

* Adds `release` profile for Sonatype repository deployment.
* Switches version to `1.0.1-SNAPSHOT`
* Minor cleanup on Javadoc targets to put 'Ion Java' in our documentation over 'ion-java'.
Ref #69

Adds Build Config for Maven Central Deployment

---

src/software/amazon/ion/impl/IonReaderBinaryRawX.java
src/software/amazon/ion/impl/PrivateIonBinaryWriterBuilder.java
src/software/amazon/ion/impl/bin/IonManagedBinaryWriter.java
src/software/amazon/ion/impl/bin/IonRawBinaryWriter.java
src/software/amazon/ion/impl/bin/PrivateIonManagedBinaryWriterBuilder.java
src/software/amazon/ion/system/IonBinaryWriterBuilder.java
test/software/amazon/ion/BinaryTest.java
test/software/amazon/ion/impl/bin/IonManagedBinaryWriterTest.java
test/software/amazon/ion/impl/bin/IonRawBinaryWriterTest.java
test/software/amazon/ion/system/IonBinaryWriterBuilderTest.java

IonReaderBinaryRawX has learned to read the length of the float
type.
IonRawBinaryWriter has learned how to write 32-bit float values
when there will be no loss in precision.
Ref: http://amznlabs.github.io/ion-docs/float.html

Adds Support for 32-bit Floats

---

src/software/amazon/ion/IntegerSize.java
src/software/amazon/ion/IonInt.java
src/software/amazon/ion/IonReader.java
src/software/amazon/ion/impl/IonReaderBinarySystemX.java
src/software/amazon/ion/impl/IonReaderTextRawTokensX.java
src/software/amazon/ion/impl/IonReaderTextSystemX.java
src/software/amazon/ion/impl/IonReaderTreeSystem.java
src/software/amazon/ion/impl/PrivateScalarConversions.java
src/software/amazon/ion/impl/SymbolTableReader.java
src/software/amazon/ion/impl/bin/AbstractIonWriter.java
src/software/amazon/ion/impl/lite/IonIntLite.java
src/software/amazon/ion/impl/lite/IonValueLite.java
test/AllTests.java
test/software/amazon/ion/IntTest.java
test/software/amazon/ion/streaming/ReaderIntegerSizeTest.java

The changes in AbstractIonWriter show how this can be useful. Whereas previously Ion ints were all resurrected as BigIntegers for safety, they can now be resurrected into the smallest possible integer data type.
See #76

Added getIntegerType API to IonReader and IonInt.

---

pom.xml

It is not intended to be an API for customer use.
Removed the Import-Package instruction, because the documentation says it should be rarely used.
Relevant entries in `MANIFEST.MF` before the change:
```
Export-Package: software.amazon.ion;uses:="software.amazon.ion.facet,s
oftware.amazon.ion.system";version="1.0.2",software.amazon.ion.apps;u
ses:="software.amazon.ion";version="1.0.2",software.amazon.ion.facet;
version="1.0.2",software.amazon.ion.system;uses:="software.amazon.ion
";version="1.0.2",software.amazon.ion.util;uses:="software.amazon.ion
";version="1.0.2"
```
After the change:
```
Export-Package: software.amazon.ion;uses:="software.amazon.ion.facet,s
oftware.amazon.ion.system";version="1.0.2",software.amazon.ion.facet; …
```

Remove `apps` package from OSGi export list.

---

pom.xml

Preparation for release to Maven Central.

Release 1.0.2

---

test/software/amazon/ion/TestUtils.java

Updates ion-test pkg and add non supported files to skip list. Files on
skip list have ISSUES associated to follow up on fixes
symbolWithTab was added to skip list temporarily as it's being
considered as a bad/ example, but should be on the good/ set. See
https://github.com/amzn/ion-tests/pull/32 for details

Ignore new non supported files from ion-test

---

src/software/amazon/ion/EmptySymbolException.java
src/software/amazon/ion/IonSymbol.java
src/software/amazon/ion/IonText.java
src/software/amazon/ion/IonValue.java
src/software/amazon/ion/IonWriter.java
src/software/amazon/ion/SymbolTable.java
src/software/amazon/ion/ValueFactory.java
src/software/amazon/ion/impl/IonReaderTextRawX.java
src/software/amazon/ion/impl/IonWriterSystem.java
src/software/amazon/ion/impl/LocalSymbolTable.java
src/software/amazon/ion/impl/PrivateIonTextAppender.java
src/software/amazon/ion/impl/PrivateUtils.java
src/software/amazon/ion/impl/SharedSymbolTable.java
src/software/amazon/ion/impl/bin/IonManagedBinaryWriter.java
src/software/amazon/ion/impl/lite/IonStructLite.java
src/software/amazon/ion/impl/lite/IonSymbolLite.java
src/software/amazon/ion/impl/lite/IonValueLite.java
src/software/amazon/ion/util/IonTextUtils.java
test/software/amazon/ion/IonValueTest.java
test/software/amazon/ion/StructTest.java
test/software/amazon/ion/SymbolTest.java
test/software/amazon/ion/TestUtils.java
test/software/amazon/ion/impl/IonWriterTestCase.java

Issue: https://github.com/amzn/ion-java/issues/42

Support for empty symbols, e.g. ''

---

src/software/amazon/ion/impl/IonWriterSystem.java
test/software/amazon/ion/SystemProcessingTestCase.java

One is an ignored for malformed symbols, "" is valid so should not be
there
Another is part of the writer. Since it was not caught by any UT it
could be dead code, will investigate marking it as deprecated and
potentially removing as a separate task
https://github.com/amzn/ion-java/issues/42

Adding missed changes for empty symbol support

---

src/software/amazon/ion/impl/IonReaderBinaryRawX.java
src/software/amazon/ion/impl/LocalSymbolTable.java
test/software/amazon/ion/TestUtils.java

https://github.com/amzn/ion-java/issues/35

Multiple symbol/import list error identification.

---

test/software/amazon/ion/impl/BinaryWriterTest.java

builds failing on travis during testHugeWrite(2 gigs of additional memory).

removed testHugeWrite due to travis memory limitations.

---

src/software/amazon/ion/impl/IonReaderBinarySystemX.java
src/software/amazon/ion/impl/IonWriterSystem.java
src/software/amazon/ion/impl/IonWriterSystemText.java
src/software/amazon/ion/impl/LocalSymbolTable.java
src/software/amazon/ion/impl/SharedSymbolTable.java
src/software/amazon/ion/impl/SymbolTokenImpl.java
src/software/amazon/ion/impl/bin/IonRawBinaryWriter.java
src/software/amazon/ion/impl/lite/IonContainerLite.java
src/software/amazon/ion/impl/lite/IonStructLite.java
src/software/amazon/ion/impl/lite/IonSymbolLite.java
src/software/amazon/ion/impl/lite/IonValueLite.java
test/software/amazon/ion/TestUtils.java

-changed functionality that assumed that fieldID is a unique identifier for a symbolID
-removed testHugeWrite due to travis memory restrictions.
-added support for sid0 in ID lookup logic.

SIDzero support

---

test/software/amazon/ion/EquivTimelineTest.java
test/software/amazon/ion/EquivsTestCase.java
test/software/amazon/ion/GoodIonTest.java
test/software/amazon/ion/junit/IonAssert.java

adds support for round tripping equivalent data within equivstest and goodiontest.
Seems to be the exact same logic as detailed within roundtriptest.test()
-- work in progress --

Roundtrip equivalence

---

src/software/amazon/ion/Timestamp.java
test/software/amazon/ion/TimestampTest.java

Checking if the ERA flips in any Timestamp.add* operation and throwing
an error if that's the case
ref: https://github.com/amzn/ion-java/issues/130

Handling CE to BCE dates during add* operations

---

src/software/amazon/ion/impl/IonReaderTreeSystem.java
test/software/amazon/ion/impl/BinaryWriterTest.java
test/software/amazon/ion/impl/IonWriterTestCase.java
test/software/amazon/ion/impl/TreeReaderTest.java

Fix for https://github.com/amzn/ion-java/issues/133

fixes isInStruct/getFieldName/getFieldNameSymbol behavior for DOM-backed readers

---

pom.xml

Add Automatic-Module-Name in manifest so Java9 modular applications can depend on this library.
It is recommended for java libraries in public repositories like Maven Central to add Automatic-Module-Name manifest entry. This allows the consumers of the library to move to Java 9 modularization and depend on the Automatic-Module-Name value instead of the name derived from the Jar file. This way, your consumers won't need to make changes when your library is eventually converted to a Java 9 module.
Adding Automatic-Module-Name doesn't affect any code and will simply make a name reservation until an actual module-info.java will be added eventually. More details can be found in this [article](https://dzone.com/articles/automatic-module-name-calling-all-java-library-maintainers).
[This …

Add Automatic-Module-Name in manifest

---

src/software/amazon/ion/impl/IonReaderBinaryRawX.java
test/software/amazon/ion/impl/VarIntTest.java

#146: Detects if a `VarUInt` or `VarInt` value fits inside a Java `int`, if not throws an exeception 

Correctly detects overflow for VarUInt and VarInt

---

src/software/amazon/ion/impl/PrivateScalarConversions.java
test/software/amazon/ion/impl/PrivateScalarConversionsTest.java

was using intValue previously resulting in overflow. Inludes UTs to
verify the behavior
https://github.com/amzn/ion-java/issues/148

uses decimal.longValue when casting from decimal to long

---

src/software/amazon/ion/impl/IonReaderBinaryUserX.java
src/software/amazon/ion/impl/IonReaderTextUserX.java
src/software/amazon/ion/impl/IonReaderTreeUserX.java
src/software/amazon/ion/impl/IonWriterSystem.java
src/software/amazon/ion/impl/IonWriterSystemTree.java
src/software/amazon/ion/impl/IonWriterUser.java
src/software/amazon/ion/impl/PrivateIonValue.java
src/software/amazon/ion/impl/PrivateIonWriterBase.java
src/software/amazon/ion/impl/PrivateUtils.java
src/software/amazon/ion/impl/lite/IonValueLite.java

Relevant line from the spec:
> ...a top-level struct whose first annotation is $ion_symbol_table is interpreted as a local symbol table.
This PR also updates the ion-tests submodule, which brings in the coverage for this change (see `iontestdata/good/equivs/localSymbolTableWithAnnotations.ion` and `iontestdata/good/non-equivs/localSymbolTableWithAnnotations.ion`).

Requires the $ion_symbol_table annotation to be a struct's first annotation in order to carry LST semantics.

---

src/software/amazon/ion/UnknownSymbolException.java
src/software/amazon/ion/impl/lite/IonStructLite.java
test/software/amazon/ion/StructTest.java

Updated ionstructlite so fieldmap will not always resolve as null on construction, added a boolean hasNullField to throw correctly when a fieldname does not resolve and correctness cannot be determined.

IonStructLite bugfixes

---

test/software/amazon/ion/SequenceTestCase.java
test/software/amazon/ion/TrueSequenceTestCase.java
test/software/amazon/ion/impl/VarIntTest.java

A couple quick fixes for problems I ran into when building using OpenJDK 11, now that it's GA. Good news is only test code is affected.
First: IonSequence now inherits a new `toArray(IntFunction<T[]>)` default method from java.util.Collection in addition to the `toArray(T[])` method it defines, making references to `seq.toArray(null)` ambiguous. Easy enough fix, presumably no one is doing that in real code.
Second: Java EE modules have been dropped from the standard library, breaking a reference to `javax.xml.bind.DatatypeConverter.parseHexBinary(String)` used to construct some test data. I inlined a quick-and-dirty implementation, or happy to back that out and add a test-scoped dependency on `javax.xml.bind:jaxb-api` if you prefer.
By submitting this pull …

Fixes for compile errors when using Java 11

---

.travis.yml

https://github.com/amzn/ion-java/issues/164
This adds more JDKs to our `.travis.yml` file.  Looks like we are not source compatible earlier versions of the JDK due to some references to `java.lang.Long.BYTES` which was introduced in JDK8.

Add additonal JDKs to .travis.yml, issue 164

---

.travis.yml
src/software/amazon/ion/Timestamp.java
test/software/amazon/ion/TimestampTest.java

See https://github.com/amzn/ion-java/issues/160.  Also there are ample comments in the diff.

Implements workaround for java.util.Date bug described in issue 160

---

.travis.yml

Oracle JDK 10 was deprecated and fails travis builds example:
https://travis-ci.org/amzn/ion-java/jobs/442398169

Removes oraclejdk10 from build list

---

src/software/amazon/ion/Timestamp.java

Some Timestamp methods have incorrect javadocs due to copy/pasting. This change fixes those javadocs.

Fix javadoc for some methods of Timestamp

---

src/software/amazon/ion/Timestamp.java
test/software/amazon/ion/TimestampTest.java

Operations that require inflating the BigDecimal can be expensive for
large numbers, examples:
* longValue
* intValue
* setScale
https://github.com/amzn/ion-java/issues/159

Bound checking BigDecimal in Timestamp to guard against DoS

---

src/software/amazon/ion/impl/bin/WriteBuffer.java
test/software/amazon/ion/impl/bin/WriteBufferTest.java

Calls to `WriteBuffer#truncate(long)` modify an internal `index` value that tracks the last block in the buffer that contains data to write. Our current implementation of `WriteBuffer#writeTo(OutputStream)` ignores the `index` value and writes the contents of all allocated blocks to the `OutputStream`.
In cases where multiple blocks have been allocated and `truncate()` should cause one or more to be ignored, this bug results in unparsable data. This problem is relatively rare, but it can happen when writing a very large (>32kb) local symbol table at the head of a stream.
1. `WriteBuffer#writeTo(OutputStream)` has been modified to only write the contents of blocks `[0, index]`.
2. A new unit test has been added.
By submitting this pull request, I confirm that my …

WriteBuffer truncation fix

---

src/software/amazon/ion/impl/bin/IonRawBinaryWriter.java
test/software/amazon/ion/impl/bin/IonRawBinaryWriterTest.java

Issue #174 
Modifies IonRawBinaryWriter.flush() so WriteBuffer.finish() is not called when the writer is closed, thus avoiding the exception case introduced by #171.

Avoids calling WriteBuffer.finish() if the writer is closed

---

src/software/amazon/ion/impl/lite/IonSystemLite.java

Removes the synchronization, which is unnecessary because:
* The `_loader `member field is final, so the reference cannot change.
* Implementations of `IonLoader` are required to be threadsafe.

Removes unnecessary synchronization from IonSystemLite.getLoader.

---

src/software/amazon/ion/IonDatagram.java
test/software/amazon/ion/impl/lite/BaseIonSequenceLiteTest.java
test/software/amazon/ion/impl/lite/IonDatagramLiteTest.java
test/software/amazon/ion/impl/lite/IonListLiteTest.java
test/software/amazon/ion/impl/lite/IonSexpLiteTest.java

https://github.com/amzn/ion-java/issues/179
https://github.com/amzn/ion-java/issues/49
Adds unit tests for all `IonSequenceLite` implementations and fixes `IonDatagram` javadoc. The method remove from `IonDatagram` interface is inherited from `IonSequence` and works as described in its javadoc so no need to have it in `IonDatagram` as well 

IonSequenceLite#retainAll javadoc fix and tests

---

src/software/amazon/ion/impl/IonReaderTextRawX.java
src/software/amazon/ion/impl/IonReaderTextUserX.java
test/software/amazon/ion/TestUtils.java

*Issues:* #88, #114
*Description of changes:*  top-level values such as `'$ion_1_0'` and `$2` were previously incorrectly processed as IVMs.  Such values are now ignored, which is the expected behavior per the Ion specification.

Ignores pseudo-IVMs as expected by the specification

---

src/software/amazon/ion/impl/IonReaderBinaryRawX.java
test/software/amazon/ion/TestUtils.java

Fixes #100. When reading a binary struct that is flagged as having ordered keys, the reader now enforces that the struct cannot be empty.

Empty ordered structs now cause an exception.

---

src/software/amazon/ion/impl/IonReaderTextRawX.java
test/software/amazon/ion/streaming/ReaderTest.java

*Issue:* #186 
* updates ion-tests submodule to include a new bad/structWithIncompleteField.ion test
* fixes lexer state transitions such that an error is produced when a `}` is found where a value is expected
* removes lob test cases for values `[1, { c: } }` and `{a: 1, b: { c: } }`

Produces an error for a struct field that has no value

---

src/software/amazon/ion/impl/IonReaderBinaryRawX.java
test/software/amazon/ion/TestUtils.java

Fixes #102.
Timestamps whose fractional seconds are outside of the range 0 (inclusive) to 1 (exclusive) will now cause an exception to be thrown.
The original issue indicated that the spec itself needed to be updated to clarify this. However, it already states:
> The fractional seconds’ value is coefficient * 10 ^ exponent. **It must be greater than or equal to zero and less than 1.**
(emphasis mine) which I think is pretty clear.

Timestamp fractional seconds outside of [0, 1) now cause an exception.

---

src/software/amazon/ion/Timestamp.java
test/software/amazon/ion/TimestampTest.java

#136 
#160 
#163 
#165
Removes Timestamp's `_year`, `_month`, `day`, `hour`, `minute`, and `second` internal fields in favor of an internal Calendar. This allows us to shift responsibility for the arithmetic (especially leap year calculations) to Calendar. Timestamp still must manually track fractional seconds and local offsets. Users who want to use a non-standard Calendar system to back their Timestamps may do so using `Timestamp.forCalendar`. Timestamp remains externally immutable--there is no way for the user to access the internal Calendar and arithmetic methods always clone the calendar before performing their operations.
The changes to `TimestampTest.testAdd*` are to support the behavioral fix discussed in #136. Additional tests …

Replaces Timestamp internals with Calendar.

---

.travis.yml
src/software/amazon/ion/Decimal.java
src/software/amazon/ion/Timestamp.java
src/software/amazon/ion/impl/IonReaderTextRawTokensX.java
src/software/amazon/ion/impl/IonReaderTextSystemX.java
test/software/amazon/ion/BadIonTest.java
test/software/amazon/ion/SystemProcessingTestCase.java
test/software/amazon/ion/TestUtils.java
test/software/amazon/ion/TimestampTest.java

*Issue* #105 
Produces an error when an unpaired surrogate is encountered, in accordance with http://www.unicode.org/faq/utf_bom.html#utf16-7:  
> Unpaired surrogates are invalid in UTFs. These include any value in the range D800<sub>16</sub> to DBFF<sub>16</sub> not followed by a value in the range DC00<sub>16</sub> to DFFF<sub>16</sub>, or any value in the range DC00<sub>16</sub> to DFFF<sub>16</sub> not preceded by a value in the range D800<sub>16</sub> to D<sub>BFF16</sub>.
In accordance with the [Strings and Clobs](https://amzn.github.io/ion-docs/docs/stringclob.html) portion of the Ion Specification, splitting an escaped surrogate pair across multiple long strings (such as `'''\uD800''' '''\uDC00'''`) is invalid Ion.  Test logic that expects such values to …

Produces an error when an unpaired surrogate is encountered

---

pom.xml
src/software/amazon/ion/IonSystem.java
src/software/amazon/ion/ValueFactory.java

The log of this [failed travis buid](https://travis-ci.org/amzn/ion-java/jobs/486874734) shows:
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  49.094 s
[INFO] Finished at: 2019-02-01T15:30:47-08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.7.1:site (default-site) on project ion-java: Error generating maven-javadoc-plugin:2.10.3:javadoc-no-fork report:
[ERROR] Exit code: 1 - javadoc: error - The code being documented uses modules but the packages defined in http://docs.oracle.com/javase/8/docs/api/ are in the unnamed …
```

OpenJDK11 javadoc fix

---

src/software/amazon/ion/Timestamp.java
test/software/amazon/ion/TimestampTest.java

The additional memory pressure caused by backing Timestamp by Calendar was noticeable by heavy users of Timestamp.
Keeps the other bug fixes from that commit (see #136, #160, #163, and most of #165).
#195 replaced Timestamp's internals with Calendar and fixed several bugs in Timestamp by deferring the more bug-prone parts of Timestamp (like leap-year calculations and timestamp arithmetic) to Calendar. However, it turns out that Calendars are [too big](http://javaquirks.blogspot.com/2008/03/size-of-javautilcalendar-is-432-bytes.html).
Creating and storing 1,000,000 Timestamps:
v1.2.0: Heap size: 119151032
v1.3.0: Heap size: 533227696
(This PR) Heap size: 111301672
This change restores the previous Timestamp internals, while finding different solutions for the …

Reverts replacing Timestamp internals with Calendar.

---

src/software/amazon/ion/IonLoader.java
src/software/amazon/ion/IonSystem.java
src/software/amazon/ion/impl/PrivateIonSystem.java
src/software/amazon/ion/impl/lite/IonLoaderLite.java
src/software/amazon/ion/impl/lite/IonSystemLite.java
test/software/amazon/ion/BinaryByteArrayIteratorSystemProcessingTest.java
test/software/amazon/ion/BinaryStreamIteratorSystemProcessingTest.java
test/software/amazon/ion/IonSystemTest.java
test/software/amazon/ion/TextByteArrayIteratorSystemProcessingTest.java
test/software/amazon/ion/TextStreamIteratorSystemProcessingTest.java
test/software/amazon/ion/impl/IonWriterTestCase.java

This commit addresses the memleak caused by auto detecting and uncompressing gzipped ion data by either:
* Fixing the issue when possible, example IonSystem#singleValue
* Deprecating methods where a fix is not feasible providing a safe
alternative, example IonSystem#iterate(InputStream)
The alternative method takes in an IonReader which the user is
responsible for closing. IonReader will close all used resources
including the Gzip stream used to decompress which is hidden from users
in the unsafe deprecated methods.
Issues:
* https://github.com/amzn/ion-java/issues/210
* https://github.com/amzn/ion-java/issues/198

Gzip memleak fix

---

pom.xml

Some older users require JDK 5 compatibility so setting as the build and source target to block the use of any newer features.

target JDK 5

---

.gitignore

bin/ and tmp/ can match relative paths, e.g. com/amazon/ion/impl/bin

fixing gitignore

---

src/com/amazon/ion/impl/IonReaderBinarySystemX.java
src/com/amazon/ion/impl/IonReaderTextRawX.java
src/com/amazon/ion/impl/IonReaderTextSystemX.java
src/com/amazon/ion/impl/_Private_IonWriterBase.java

I started to use Amazon ION and got first exceptions from users: 
```
Caused by: java.lang.IllegalStateException
at com.amazon.ion.impl.IonReaderBinarySystemX.stringValue(IonReaderBinarySystemX.java:389)
```
From this error message (empty) not clear what was the current value type. Indeed, application itself can report more descriptive error message (because context aware), but still it is better if ION will throw `IllegalStateException` with some message.

Make IllegalStateException() more descriptive

---

pom.xml
src/com/amazon/ion/impl/_Private_CommandLine.java

resolves #240
Tested manually since the CLI is not testable without refactoring 
```
$ java -jar target/ion-java-1.5.0-SNAPSHOT.jar --version
Fixes manifest main class and CLI -- options
{
version:"1.5.0-SNAPSHOT",
build_time:2019-05-16T10:17:43-07:00
}
~/workplace/ion-java cli_fix-240*
$ java -jar target/ion-java-1.5.0-SNAPSHOT.jar --help
ion-java -- Copyright (c) 2007-2019 Amazon.com
usage: java -jar <jar> <options>
options:
version		prints current version entry
help		prints this helpful message
~/workplace/ion-java cli_fix-240*
$ java -jar target/ion-java-1.5.0-SNAPSHOT.jar -v
{
version:"1.5.0-SNAPSHOT",
build_time:2019-05-16T10:17:43-07:00
}
~/workplace/ion-java cli_fix-240*
$ java -jar target/ion-java-1.5.0-SNAPSHOT.jar -h
ion-java -- Copyright (c) 2007-2019 Amazon.com
usage: java …
```

Fixes manifest main class and CLI -- options

---

src/com/amazon/ion/impl/bin/IonRawBinaryWriter.java

...which caches the top element to avoid repetitive ArrayList.get calls in inner-loop code.
The technique used by the IonRawBinaryWriter's `containers` collection (see #244) to reduce the number of `ContainerInfo` allocations is a pattern that is potentially useful elsewhere (see #245). One of the most common operations on this collection is to retrieve the top element. Previously, this required a fresh `ArrayList.get` every time. Since, in many cases, this was done several times per value, profiles showed that these `ArrayList.get` consumed a fairly significant amount of CPU time  in applications that write long streams of binary Ion data. Storing the top element within the new `RecyclingStack` class eliminates these repetitive lookups.
A benchmark showed that …

Refactors the containers stack into the RecyclingStack class

---

src/com/amazon/ion/impl/bin/IonRawBinaryWriter.java

JDK 5 won't compile `@Override` annotations on methods that implement an interface.

Removes @Override annotation not allowed by old JDK versions.

---

.travis.yml

[Travis CI changed the default distro from trusty to xenial](https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment) back in April.  They also [disabled OracleJDK8 in xenial](https://github.com/travis-ci/travis-ci/issues/10290).  This breaks the build for us since OracleJDK8 is in our build matrix.
This change manually specifies `trusty` as our preferred distribution and seems to make the build succeed reliably.

Manually specify the trusty distro

---

src/com/amazon/ion/IonSystem.java
src/com/amazon/ion/impl/lite/IonSystemLite.java
test/com/amazon/ion/LoaderTest.java

When ion object resides in the middle of bytearray, this helper
method would help to extract it without memory copy overhead.
Issue #256

Add IonSystem#singleValue(byte[], int, int)

---

src/com/amazon/ion/impl/IonReaderBinaryRawX.java
test/AllTests.java
test/com/amazon/ion/impl/IonReaderBinaryRawLargeStreamTest.java
test/com/amazon/ion/util/RepeatInputStream.java

The binary reader uses `Integer.MIN_VALUE` to mean [`NO_LIMIT`](https://github.com/amzn/ion-java/blob/master/src/com/amazon/ion/impl/IonReaderBinaryRawX.java#L54) for its [`_local_remaining`](https://github.com/amzn/ion-java/blob/master/src/com/amazon/ion/impl/IonReaderBinaryRawX.java#L65) value, which keeps track of the remaining number of bytes in the current value. Between values at the top level, this should always be set to `NO_LIMIT`. No arithmetic should ever be performed on the `_local_remaining` when it is set to `NO_LIMIT`.
This PR fixes a bug that violated this by performing an unconditional subtraction of the current value's length from `_local_remaining` within `stringValue()`, `decimalValue()`, and `timestampValue()`. This caused `_local_remaining` …

Fixes a bug in IonReaderBinaryRawX that caused the reader to prematurely finish reading large streams in certain cases.

---

src/com/amazon/ion/impl/IonReaderBinaryRawX.java
test/com/amazon/ion/impl/IonReaderBinaryRawStringTest.java

This PR optimizes the process by which the binary `IonReader` reads `string`s.
When decoding strings that are small enough to fit in the reusable decoding buffer:
&nbsp; | Time Required | GC Time
| ----------- | :--------------: | :---------: |
| Before | 615.351 ± 34.344 ms/op | 273ms | 
| After | 380.573 ± 11.136   ms/op | 185ms | 
| &nbsp; | 38.15% faster | 32.23% lower |
&nbsp; | Time Required | GC Time
| ----------- | :--------------: | :---------: |
| Before | 867.368 ± 21.804 ms/op | 82ms | 
| After | 466.461 ± 21.796 ms/op | 54ms | 
| &nbsp; | 46.22% faster | 34.15% lower |
In order to read a `string` of length `n`, the old version of `IonBinaryReaderRawX#readString` will:
* Allocate and zero out a `char[]` of length `n` to store decoded `char`s.
* Read each byte from the data …

Optimizations for reading binary strings.

---

src/com/amazon/ion/IonWriter.java
src/com/amazon/ion/impl/bin/IonManagedBinaryWriter.java
test/com/amazon/ion/impl/BinaryWriterTest.java
test/com/amazon/ion/impl/IonWriterTestCase.java
test/com/amazon/ion/impl/OutputStreamWriterTestCase.java
test/com/amazon/ion/impl/bin/IonManagedBinaryWriterTest.java

Fixes #178 ; supersedes PR #236 
Now, `IonWriter.flush()` always flushes data when at the top level. Subsequent values that contain symbols will initiate an appended LST. The behavior of `IonWriter.finish()` is unchanged.
The writer also supports intercepting user calls that manually construct a symbol table. LST append support has been added for that case as well.

Adds support for writing LST append after IonWriter.flush()

---

src/com/amazon/ion/IonSystem.java
src/com/amazon/ion/impl/IonReaderTreeSystem.java
src/com/amazon/ion/system/IonReaderBuilder.java
test/com/amazon/ion/impl/TreeReaderTest.java

Caused by failure to update the loop condition.
Also added a note to the tree reader construction methods to state that behavior is undefined if the value is modified concurrently. The tree reader implementation is not designed to support this.

Fixes a bug that could cause an infinite loop when an IonValue was modified while being read with the tree reader.

---

test/com/amazon/ion/EquivsTestCase.java
test/com/amazon/ion/impl/OptimizedBinaryWriterTestCase.java

`EquivsTestCase` and `OptimiziedBinaryWriterTestCase` are base classes that were not marked as `abstract` causing my IDE's test runner to attempt treat them like regular, non-abstract test classes which both fail to execute and appear as failures in the IDE's test runner.  Making them both
abstract fixes this issue.

Fix issue causing test failures in IDE only

---

src/com/amazon/ion/impl/lite/IonSequenceLite.java

This just avoids keeping a second reference to a `parent` that's not actually needed.

Avoid nesting IonSequenceLite.SubListView instances

---

src/com/amazon/ion/impl/lite/IonSequenceLite.java
test/com/amazon/ion/impl/lite/BaseIonSequenceLiteSublistTestCase.java

Throw exceptions according to the [List<T>.subList(int, in)](https://docs.oracle.com/javase/7/docs/api/java/util/ArrayList.html#subList(int,%20int)) javadoc.
Fixes #295

Throw exception when IonSequenceLite.subList(int, int) arguments invalid

---

pom.xml
src/com/amazon/ion/IonSequence.java
src/com/amazon/ion/impl/lite/IonSequenceLite.java
test/com/amazon/ion/impl/lite/BaseIonSequenceLiteSublistTestCase.java
test/com/amazon/ion/impl/lite/IonSequenceLiteSubListViewEqualityTests.java

By changing `IonSequence.SubListView` to extend [`AbstractList`](https://docs.oracle.com/javase/7/docs/api/java/util/AbstractList.html) we inherit its implementation of `.equals` and `.hashCode`.
The only real work here was the unit tests and the javadoc.
Also adds `JUnitParams` as a test dependency since (IMHO) this provides a much better method of test parameterization.

Make IonSequence.SubListView implement equals and hashCode

---

src/com/amazon/ion/Timestamp.java
test/com/amazon/ion/TimestampTest.java

Implements #301 by adding `Timestamp.forEpochSecond` to allow easy conversion from Java 8's `java.time.Instant`.
This test works on my local machine when I target Java 8.  (It's not included in this PR since we can't yet update `ion-java` to Java 8.)
```Java
@Test
public void convertFromInstantTest() {
Instant i = Instant.now();
Timestamp ts = Timestamp.forEpochSecond(i.getEpochSecond(), i.getNano());
assertEquals(i.toString(), ts.toString());
System.out.println(i.toString());
System.out.println(ts.toString());
}
```
Output is: 
```
2020-08-12T18:28:26.439Z
2020-08-12T18:28:26.439Z
```

Adds Timestamp.forEpochSecond()

---

src/com/amazon/ion/impl/LocalSymbolTable.java

Before this change, invocations of this LST constructor that provided more than 12 symbols were guaranteed to require at least one HashMap resize before the constructor returns. After this change, no HashMap resizes will occur before the constructor returns.
For a large sample of binary Ion containing lots of symbols, this improved read performance by about 10%.

Sets LocalSymbolTable's initial map size to avoid guaranteed resizing within the constructor.

---

src/com/amazon/ion/impl/LocalSymbolTable.java
src/com/amazon/ion/impl/LocalSymbolTableAsStruct.java
test/com/amazon/ion/impl/IonWriterTestCase.java
test/com/amazon/ion/impl/SymbolTableTest.java
test/com/amazon/ion/impl/bin/IonManagedBinaryWriterTest.java

Before this change, each LST append caused the reader to copy all of the symbols from its current LocalSymbolTable into a new LocalSymbolTable instance and throw the old one away before appending the new symbols. This is tremendously wasteful and becomes noticeable as the number of symbols in the stream increases.
To demonstrate this, I started with a 6.4GB stream of binary Ion containing 98,000 unique symbols and over 11,000 LST appends. I then re-wrote the stream with equivalent structure, but using only 49,000 unique symbols (i.e. after 49,000 unique symbols, the next unique symbol from the original stream was written with lowest local SID, the next unique symbol assigned the next-lowest SID, etc.). I did the same with 6,000 unique symbols (1/16 the original …

Improves read performance of streams that use LST append with a large number of symbols.

---

.travis.yml
ion-java-cli/src/com/amazon/tools/cli/CommandType.java
ion-java-cli/src/com/amazon/tools/cli/IonJavaCli.java

Allow ion-java-cli to support `java -jar ion-java-cli version` command to print its version (1.0).

Implements version command for ion-java-cli.

---

src/com/amazon/ion/impl/IonReaderBinaryRawX.java
test/com/amazon/ion/streaming/ReaderTest.java

#318 
Fixes incremental reads and adds a test. When I created #318 I didn't notice that the branch in `readBytes` is actually redundant due to these lines `getBytes` (where `byteSize()` returns `_value_lob_remaining`):
```java
int value_len = byteSize(); // again validation
if (value_len > len) {
value_len = len;
}
```
NOTE: the test is skipped for text readers due to #319.

Fixes bug #318 in the binary reader's implementation of IonReader.getBytes.

---

src/com/amazon/ion/impl/bin/_PrivateIon_HashTrampoline.java

This expensive to instantiate. Luckily, it's a thread-safe pool that can be treated as a singleton.

Avoids repetitive reallocation of PooledBlockAllocatorProvider in _PrivateIon_HashTrampoline.

---

.github/ISSUE_TEMPLATE.md
.github/workflows/main.yml
ion-java-cli/src/com/amazon/tools/cli/IonJavaCli.java

Added GitHub Actions to trigger ion-test-driver for every pull request.
Current logic: Every PR will kick off an ion-test-driver run and analyze the result automatically, if there is anything changed between the new commit and the target commit, it will open an issue and shows more details there. [Example issue](https://github.com/amzn/ion-java/issues/329).
I tried to store the GitHub logic in one repo and reuse it in other implementations, but [Github community ticket](https://github.community/t/is-it-possible-to-use-the-same-workflow-in-different-repositories/17719) mentioned that they added this to their roadmap but didn't implemented it yet. So I create Github actions for each implementation for now.
**Related PR:**
ion-test-driver new option (--result-diff) is able to automatically …

Integrate ion-test-driver into pipeline.

---

.github/workflows/ion-test-driver.yml

Before we get main branch sha too early which will cause an async issue. Now I move this step right before ion-test-driver run.

Fixed async main branch change issue for ion-test-driver GitHub Actions.

---

src/com/amazon/ion/impl/IonTokenConstsX.java
test/com/amazon/ion/LoaderTest.java

For a file with text: `$33333333333333`, ion-java raise NumberFormatException exception instead of IonException.
The issue happens when we call the [hasNext()](https://github.com/amzn/ion-java/blob/30536fbee0cf93d7b21c1702cf4ba6df6a58965e/src/com/amazon/ion/impl/IonReaderTextRawX.java#L486) method. When we decode a SID that is bigger than INT_MAX, it will raise NumberFormatException in [parseInt method](https://github.com/amzn/ion-java/blob/30536fbee0cf93d7b21c1702cf4ba6df6a58965e/src/com/amazon/ion/impl/IonTokenConstsX.java#L516). 
hasNext() method is called before other logic (e.g. SymbolToken validate method), so I think we can just add a try...catch here.
**unit test:**
`Tests passed: 23159, ignored: 391 of 23550 tests - 30 s 635 ms`
**manually test:**
For the file with text: …

Catches exception of unkown sid bigger than INT_MAX.

---

src/com/amazon/ion/impl/IonUTF8.java
test/com/amazon/ion/IonExceptionTest.java

**Description:**
Assertions error raised sometimes in IonUTF8.java when uses unexpected encoding, e.g. `iso-8859-1`.
**Summary of the code:**
Changed assert to IonException and added unit test.
&nbsp;

Fix unexpected assertion error.

---

src/com/amazon/ion/impl/lite/IonContainerLite.java
src/com/amazon/ion/impl/lite/IonStructLite.java
src/com/amazon/ion/impl/lite/IonValueLite.java

Fixes #360.
All IonValueLite subclasses implement `getSystem()` by delegating that call to their internal `_context` field, which represents the parent value. The context will then delegate to its own context, and this process repeats up the tree until the top level is found. In deeply nested data, this linear search becomes especially expensive.
The `getSystem()` method is widely used. Among other examples, it is called several times per `add()` operation on a container.
This commit modifies `IonContainerLite` (the abstract base class for `IonStructLite` and `IonSequenceLite`) by adding an `IonSystem` field that is populated at instantiation time. Storing this reference guarantees that calls to `getSystem()` can always be resolved by either the current value or its immediate parent …

Adds IonSystem field to IonContainerLite

---

src/com/amazon/ion/impl/bin/PooledBlockAllocatorProvider.java
src/com/amazon/ion/impl/bin/_PrivateIon_HashTrampoline.java
src/com/amazon/ion/impl/bin/_Private_IonManagedBinaryWriterBuilder.java
test/com/amazon/ion/impl/bin/PooledBlockAllocatorProviderTest.java

Many applications need to initialize IonWriters repeatedly for
short-lived tasks. For example, a webserver might create a new
IonWriter for each HTTP response that it needs to write. In such
cases, the bulk of the compute time needed to serialize the
response data is often spent initializing the byte array buffer
backing the IonWriter rather than performing the write logic itself.
Each time that a (e.g.) binary IonWriter is initialized, a new
PooledBlockAllocatorProvider (PBAP) is initialized with it to dole
out new byte array buffers. It attempts to reuse these byte arrays
wherever possible during its lifespan. Unfortunately, the PBAP only
lives as long as the IonWriter itself. If a new IonWriter is created,
a new PBAP (and therefore new byte arrays) are created as well.
This change …

Makes the PooledBlockAllocatorProvider a singleton

---

src/com/amazon/ion/impl/IonWriterSystemText.java
src/com/amazon/ion/impl/_Private_IonTextAppender.java
src/com/amazon/ion/impl/_Private_IonTextWriterBuilder.java
src/com/amazon/ion/util/IonTextUtils.java
test/com/amazon/ion/impl/TextWriterTest.java

N/A
The Ion Docs section on [Down Converting to Json](https://amzn.github.io/ion-docs/guides/cookbook.html#down-converting-to-json) says:
> Floats are printed as JSON *number* with `nan` and `+-inf` converted to JSON *null*
Right now, `ion-java` just writes them as `nan`, `+inf`, and `-inf`. This PR makes `ion-java` write JSON *null* as expected.

Fixes handling of NaN and +/-Inf when downconverting to json

---

src/com/amazon/ion/impl/IonWriterUserBinary.java
src/com/amazon/ion/impl/_Private_IonWriterBase.java

The method `_Private_IonWriterBase#writeValueRecursively` is
recursive in two senses:
1. It visits all of the children in the provided IonReader's
current value recursively.
2. The method itself is implemented using recursion.
This patch modifies the implementation to be iterative,
eliminating a source of StackOverflowExceptions and offering
a modest reduction in CPU cost.
This benchmark creates an `IonStruct` that is 1,000 levels deep, wraps it in an `IonReader`, then uses `writeValueRecursively` to write it to a binary Ion stream 100k times. The source can be viewed [here](https://gist.github.com/zslayton/d9677b2e8355324a6dccba8f79988dc2).
This change does not affect allocations or garbage collection, only CPU time.
**Before**
```
Score           Error   Units
time …
```

Makes `writeValueRecursively` iterative

---

src/com/amazon/ion/impl/bin/IonRawBinaryWriter.java
src/com/amazon/ion/impl/bin/utf8/Utf8StringEncoder.java
src/com/amazon/ion/impl/bin/utf8/Utf8StringEncoderPool.java

Most of the expense involved in constructing new binary writers
comes from allocating/initializing the buffers needed to encode
Java's UTF-16 Strings to UTF-8.
This change refactors the UTF-8 encoding logic into its own
class (Utf8StringEncoder) and introduces a singleton
Utf8StringEncoderPool that allows these encoders to be reused
across instantiations of binary writers.
This test initializes a new binary writer, writes a small string (`"foo"`), then closes the writer in a tight loop. The source can be found [here](https://gist.github.com/zslayton/95730187f86f467ced87f13452ba9fb4).
**Before**
```
Benchmark                             Score           Error   Units
time                                 37.664 ±         3.661   ms/op
·gc.alloc.rate                      773.095 ± …
```

Adds a pool of UTF8 String encoders

---

.github/workflows/ion-java-performance-regression-detector.yml

**Description:**
This work flow will be invoked when there is new ion-java commit gets pushed to the master branch of amzn/ion-java.
**Step 1:**
Build ion-java from the new commit on GitHub runner.
**Step 2:**
Build ion-java-benchmark-cli on the same GitHub runner. In this way the benchmark results of ion-java from the new commit will be generated after the benchmark step.
**Step 3:**
Generate three shapes of test ion data (Ion List |  Ion Struct | Nested Ion Struct) by using the sub-command of  ion-java-benchmark-cli.
**Step 4:**
Upload all generated test ion data to artifacts.  
**Step 5:**
For each shape of test data, six ion-java-benchmark-cli invokes will be implemented to finish the benchmark process. After this process, the benchmark results generated from different …

Adds GitHub workflow to detect the performance regression of ion-java automatically.

---

test/com/amazon/ion/streaming/ReaderTest.java

Fixes #380
*Description of changes:* Adds a variety of utility methods to ReaderTest, e.g. `readInt`, `readLong`, etc. These are used with assertions to replace the every other value while-loop style that preceded it. 

Clean up assertions in ReaderTest

---

src/com/amazon/ion/impl/IonReaderBinaryIncremental.java
src/com/amazon/ion/impl/_Private_IncrementalReader.java
src/com/amazon/ion/impl/_Private_IonReaderBuilder.java
src/com/amazon/ion/impl/_Private_IonReaderFactory.java
src/com/amazon/ion/impl/_Private_Utils.java
src/com/amazon/ion/impl/lite/IonLoaderLite.java
src/com/amazon/ion/impl/lite/IonSymbolLite.java
src/com/amazon/ion/impl/lite/IonSystemLite.java
src/com/amazon/ion/system/IonReaderBuilder.java
src/com/amazon/ion/system/IonSystemBuilder.java
test/com/amazon/ion/BinaryByteArrayIteratorSystemProcessingTest.java
test/com/amazon/ion/BinaryStreamIteratorSystemProcessingTest.java
test/com/amazon/ion/BinaryTest.java
test/com/amazon/ion/DatagramTreeReaderSystemProcessingTest.java
test/com/amazon/ion/IonSystemTest.java
test/com/amazon/ion/IonTestCase.java
test/com/amazon/ion/LoadBinaryBytesSystemProcessingTest.java
test/com/amazon/ion/LoadBinaryStreamSystemProcessingTest.java
test/com/amazon/ion/impl/IonReaderBinaryIncrementalTest.java
test/com/amazon/ion/impl/OptimizedBinaryWriterTestCase.java
test/com/amazon/ion/streaming/OffsetSpanBinaryReaderTest.java
test/com/amazon/ion/streaming/OffsetSpanReaderTest.java
test/com/amazon/ion/streaming/SeekableReaderTest.java
test/com/amazon/ion/streaming/SpanReaderTest.java

#379 
Adds an option to IonSystemBuilder to allow IonSystem to create incremental readers via `IonSystem.newReader`, `IonSystem.singleValue`, `IonLoader.load`, and `IonSystem.iterate`. This allows users of the DOM to receive some performance benefits of the new reader implementation, although these benefits are not as dramatic as when the reader is used directly since more of the time is spent materializing IonValue objects.
Here's one example:
```
Benchmark                               (input)                                            (options)  Mode  Cnt          Score           Error   Units
Bench.run                               log.ion      read::{f:ION_BINARY,t:FILE,a:DOM,R:INCREMENTAL}    ss    5        490.506 ±        10.695 …
```

Adds an option to IonSystemBuilder to allow the incremental reader to be used by the DOM.

---

.github/workflows/main.yml

N/A
Upgrades from `actions/setup-java@v1` to `actions/setup-java@v2`. v2 is the current version, and it's harder to find the documentation for the old version now.

Updates actions/setup-java to v2 in Github Actions main workflow

---

src/com/amazon/ion/impl/IonReaderBinaryIncremental.java
src/com/amazon/ion/impl/IonReaderBinaryRawX.java
src/com/amazon/ion/impl/bin/IonRawBinaryWriter.java
src/com/amazon/ion/impl/bin/utf8/ByteBufferPool.java
src/com/amazon/ion/impl/bin/utf8/Pool.java
src/com/amazon/ion/impl/bin/utf8/Poolable.java
src/com/amazon/ion/impl/bin/utf8/PoolableByteBuffer.java
src/com/amazon/ion/impl/bin/utf8/Utf8StringDecoder.java
src/com/amazon/ion/impl/bin/utf8/Utf8StringDecoderPool.java
src/com/amazon/ion/impl/bin/utf8/Utf8StringEncoder.java
src/com/amazon/ion/impl/bin/utf8/Utf8StringEncoderPool.java

Fixes #370 
1. Created generic base classes for poolable objects (`Poolable` - the negative diff for `Utf8StringEncoder` shows what was extracted) and for pools of poolable objects (`Pool` - the negative diff for `Utf8StringEncoderPool` shows what was extracted).
2. Created `Utf8StringDecoder` (extends `Poolable`) and `Utf8StringDecoderPool` (extends `Pool`) to provide reusable logic and character buffers for decoding UTF-8 strings.
3. Modified `IonReaderBinaryIncremental` (the new incremental binary reader) and `IonReaderBinaryRawX` (the old binary reader) to use `Utf8StringDecoderPool` and `Utf8StringDecoder`.
4. Because `IonReaderBinaryRawX` requires an additional `ByteBuffer` for its string decoding (not required by the incremental …

Adds a pool of UTF-8 decoders, making reader instantiation less expensive.

---

README.md
pom.xml

Version 1.9.0 is chosen because functionality was added in a backward-compatible manner.

Prepares version 1.9.0 for release.

---

ion-java-cli/README.md

This PR set up a README file of Ion-java-cli including setup instruction and a link to its design doc.

Adds README for ion-java-cli

---

.github/workflows/ion-java-performance-regression-detector.yml

N/A
This fixes the performance regression detector. Right now, if you add a new test case and update the `ion-test` submodule commit, the workflow will fail if the _prior_ commit cannot pass the _new_ test case. The solution is to refresh the git submodules.

Fixes performance regression detector so that it refreshes the git submodules when checking out the prior commit

---

src/com/amazon/ion/impl/IonReaderBinaryRawX.java

#395 
* Adds a null check where the NPE was being thrown. If the field name symbol is null, skips the value. This will cause the import to be treated like any other malformed import.
* Adds the [test data](https://github.com/FasterXML/jackson-dataformats-binary/blob/dbcfff6c5e4ee7ddad7e0d63a37e00aca67889a2/ion/src/test/resources/data/issue-303.ion) provided in https://github.com/FasterXML/jackson-dataformats-binary/issues/303 to `amzn/ion-tests`

Fixes NullPointerException when reading malformed symbol table import

---

src/com/amazon/ion/IonFloat.java
src/com/amazon/ion/IonInt.java
src/com/amazon/ion/IonNumber.java
src/com/amazon/ion/impl/lite/IonDecimalLite.java
src/com/amazon/ion/impl/lite/IonFloatLite.java
src/com/amazon/ion/impl/lite/IonIntLite.java
test/com/amazon/ion/DecimalTest.java
test/com/amazon/ion/IntTest.java

…and makes IonDecimal, IonFloat, and IonInt implement IonNumber
Fixes #53 
This adds members to `IonNumber` and makes `IonNumber` the supertype of `IonFloat` and `IonInt`. (It was already the supertype of `IonDecimal`.) I chose `bigDecimalValue()` for the interface because `IonDecimal` and `IonFloat` already have this method. I also chose to add `isNumeric()` so that you can make sure it's not `nan` or `+/-inf` before trying to call `bigDecimalValue()` (since calling that method for `nan`, etc. would result in a `NumberFormatException`).

Adds members to the IonNumber interface

---

src/com/amazon/ion/impl/bin/IonRawBinaryWriter.java
src/com/amazon/ion/impl/bin/WriteBuffer.java
test/com/amazon/ion/impl/bin/WriteBufferTest.java

*Issue #, if available:* 
Fixes #399.
`IonRawBinaryWriter` can be configured to preallocate buffer bytes to
hold the length prefix of a new container or annotations wrapper. This
option trades processing speed for data size. Preallocating more bytes
makes the encoded data larger, but increases the chances that the
container's length (once calculated) can be written directly into the
existing buffer.
This patch modifies the writer such that, when finalizing the encoding
of a container or annotations wrapper, the writer will check to see if
the encoded length is small enough to fit in the type descriptor byte.
If it is, the encoded bytes are shifted backwards in the buffer to
eliminate the unnecessary preallocation. This means that the encoding of
small containers …

Compacts preallocated headers when possible

---

src/com/amazon/ion/impl/bin/IntList.java
src/com/amazon/ion/impl/bin/IonManagedBinaryWriter.java
src/com/amazon/ion/impl/bin/IonRawBinaryWriter.java
test/com/amazon/ion/impl/bin/IntListTest.java

This patch changes some very hot code paths in the binary writer
to eliminate unnecessary allocations.
In particular:
* Setting the annotations list no longer constructs a temporary
array of `SymbolToken`s.
* `prepareValue` (which is called for every value in the stream)
now uses a plain `for` loop instead of an iterator to encode
each annotation.
* `IonRawBinaryWriter` now uses a custom class called `IntList`
to store its annotation symbol ID ints instead of a
`List<Integer>`, which required each int to be boxed.
This benchmark uses the `ion-java-benchmark-cli` to rewrite an existing ~335MB Ion file.
**Command**
```
java -Xmx8G -jar IJBC.jar write --format ion_binary --ion-flush-period 1024 FILENAME
```
**Before**
```
Benchmark                      Mode  Cnt          Score      Error …
```

Eliminates allocations in the binary writer

---

src/com/amazon/ion/impl/bin/utf8/Pool.java

Resolves #403 
#403 was created in response to a user report that ArrayBlockingQueue was performing poorly under high contention. This PR proposes to use [ConcurrentLinkedQueue](https://docs.oracle.com/javase/9/docs/api/java/util/concurrent/ConcurrentLinkedQueue.html) instead, as we do in the binary writer's [PooledBlockAllocator](https://github.com/amzn/ion-java/blob/master/src/com/amazon/ion/impl/bin/PooledBlockAllocatorProvider.java#L37). Now, the implementation of both pools is practically identical.
I tested the performance by reading a small binary Ion payload using 256 different threads simultaneously. My results did not capture much impact to raw performance, as is shown below.
Before:
```
Benchmark …
```

Backs Pool with ConcurrentLinkedQueue instead of ArrayBlockingQueue.

---

src/com/amazon/ion/impl/ImportLocation.java
src/com/amazon/ion/impl/IonReaderBinaryIncremental.java
src/com/amazon/ion/impl/LocalSymbolTableImports.java
test/com/amazon/ion/impl/IonReaderBinaryIncrementalTest.java

Profiling has revealed that the incremental reader's existing handling of shared symbol tables performs poorly, and becomes noticeable when reading small values with shared symbol tables or streams that contain many symbol tables with imports.
This inefficiency was due to the fact that the reader stored symbols in a flat list, which required all imported symbols to be copied into the list every time the symbol table changed. After this change, only the local symbols are stored in that list; imported symbols are referenced from their underlying shared SymbolTables via [LocalSymbolTableImports](https://github.com/amzn/ion-java/blob/master/src/com/amazon/ion/impl/LocalSymbolTableImports.java), which is also used for this purpose by the other binary IonReader …

Optimizes the incremental reader's symbol table reading logic for tables with imports.

---

src/com/amazon/ion/impl/IonReaderBinaryIncremental.java
src/com/amazon/ion/impl/IonReaderLookaheadBuffer.java
src/com/amazon/ion/impl/bin/IntList.java
test/com/amazon/ion/impl/IonReaderLookaheadBufferTest.java

This PR includes two optimizations:
1. (Minor) Uses `IntList` introduced in #404 for storing annotation SIDs without upgrading to `Integer`.
2. Lazily parsing and resolving annotation SIDs. Previously, annotation SIDs were eagerly parsed (in `IonReaderLookaheadBuffer`) at the top-level, and parsed on-demand but in their entirety below the top-level (in `IonReaderBinaryIncremental.getAnnotationSids`). Now, as long as annotation iterator reuse is enabled, annotations at any level are both parsed and resolved lazily (when accessed via the iterator provided by `IonReader.iterateTypeAnnotations`). This enables performance improvements in cases where the user does not access some or all annotations on a value, as is the case when skip-scanning.
*Performance:*
I used …

Enables the incremental reader to iterate annotations lazily.

---

src/com/amazon/ion/IonBufferConfiguration.java
src/com/amazon/ion/impl/IonReaderBinaryIncremental.java

In order to ease migration from the previous reader implementation, the incremental reader does not require users to manually specify its initial buffer size, which defaults to 32KB. In cases where the user wants to read a small fixed-size stream (e.g. from a byte array), excessive memory will be allocated if the stream is smaller than 32KB.
This PR proposes a change that will right-size the buffer configuration in this case. This significantly improves performance in the above case without requiring the user to manually provide buffer configuration. Providing this configuration still leads to the best performance, but this gets close. I think it will be common for users to skip manual configuration due to the cognitive load required to reason about it.
I used …

Properly sizes the buffer when a fixed-size stream is provided to the incremental reader with default configuration.

---

pom.xml

This is directly based on 1.9.0 due to #416.  It effectively reverts
the 1.9.1 release.

Bumps version to 1.9.2

---

src/com/amazon/ion/impl/bin/WriteBuffer.java
test/com/amazon/ion/impl/bin/WriteBufferTest.java

This patch fixes a bug in the `WriteBuffer` that caused the
`shiftBytesLeft` method to corrupt data if it was called such that the
final `Block` in the list was emptied AND the second-to-last block
reclaimed some capacity. This would only occur if the writer
was configured to use length preallocation greater than 0 and if they
were writing more than 32KB of Ion (the default block size) between
flushes.
This change accounts for that case and, if the last `Block`
is emptied, returns it to the pool for reuse.

Fixes a bug in WriteBuffer#shiftBytesLeft

---

src/com/amazon/ion/impl/IonReaderBinaryRawX.java
src/com/amazon/ion/impl/IonReaderBinarySystemX.java
src/com/amazon/ion/impl/IonReaderLookaheadBuffer.java
test/com/amazon/ion/impl/IonReaderBinaryRawLargeStreamTest.java
test/com/amazon/ion/util/RepeatInputStream.java

#170 (for containers, not scalars)
The non-incremental reader does not need to fully buffer container values, so the inability to index into a byte array using an `int` is not a limitation for container values like it currently is for scalars.
This PR allows containers, when read by the non-incremental reader, to require up to 7 bytes of a `long` to represent their lengths. If my math is correct that's 72PB, which will probably be sufficient for a while. If it's not, that's impressive.
There are instances in this diff where a `long` is cast to an `int`. This is done only when it is known that the value being cast must fit in an `int`, either because the value represents the length of a scalar after validation of the limit, or because it …

Increases the non-incremental binary reader's container length limit from 2GB to 72PB.

---

pom.xml

Looks like we dropped this in the blur of the 1.9.2 release

Bumps version to 1.9.3-SNAPSHOT

---

src/com/amazon/ion/impl/bin/WriteBuffer.java
test/AllTests.java
test/com/amazon/ion/impl/bin/IonManagedBinaryWriterGoodTest.java
test/com/amazon/ion/impl/bin/IonManagedBinaryWriterTest.java
test/com/amazon/ion/impl/bin/IonManagedBinaryWriterTestCase.java
test/com/amazon/ion/impl/bin/WriteBufferTest.java

Fixes a bug in header compaction for empty containers. Also adds testing for all writer option combinations over all good ion-tests files.
Containers that end up being empty have preallocated lengths when preallocation is enabled. Such containers end up calling `WriteBuffer.shiftBytesLeft` with `length=0`. The pre-fix behavior of short-circuiting resulted in the preallocated bytes remaining in the buffer. However, the other compaction logic still changed the type ID byte to reflect the actual length of the container (0), causing errors to be raised when the reader encountered the still-present overpadded length bytes. Simply removing the short-circuit condition allows `WriteBuffer.shiftBytesLeft(0, ...)` to correctly behave as a truncation.
The new …

Fixes a bug in header compaction for empty containers.

---

src/com/amazon/ion/impl/IonReaderLookaheadBuffer.java
test/com/amazon/ion/impl/IonReaderBinaryIncrementalTest.java

The existing tests failed to cover the case where an oversized value occurs mid-stream. Tests in a consuming package uncovered this issue. Before this fix, a `BufferOverflowException` would be raised in this situation because the buffer's write index was not shifted left to make room for more data when an oversized value was skipped. After this fix, oversized values are able to be skipped properly, allowing processing of the rest of the values in the stream to proceed normally.

Fixes a bug that prevented the incremental reader from recovering from an oversized value that occurred mid-stream.

---

src/com/amazon/ion/impl/IonReaderBinaryIncremental.java
test/com/amazon/ion/impl/IonReaderBinaryIncrementalTest.java

Adds missing validation of symbol table lengths to the incremental reader. The data in the test contains a symbol table that ends when the outer header says it will, but contains child value headers that declare lengths that exceed the declared length of the outer header. This is invalid Ion and should raise an error. I will open an issue in ion-tests to add this data as a `bad` vector.

Adds missing validation for the length of symbol table child values.

---

build.properties
pom.xml
src/com/amazon/ion/util/JarInfo.java
src/main/resources/build.properties
test/com/amazon/ion/util/JarInfoTest.java

*Issue #, if available:* #432
*Description of changes:* Uses a `build.properties` file interpolated from Maven variables at build time to make project version and build time information available through `JarInfo`. This approach does not fail when multiple instances of `ion-java` are available on the classpath. 
For testing I built two different versions of `ion-java` with each with this patch applied (in `props`) or not (in `manifest`).
```plain
❯ ls props
ion-java-1.9.5-SNAPSHOT.jar  ion-java-1.9.99-SNAPSHOT.jar
❯ ls manifest
ion-java-1.9.5-SNAPSHOT.jar  ion-java-1.9.99-SNAPSHOT.jar
```
I created a test project `Hello.java` as so:
```java
import com.amazon.ion.util.JarInfo;
public class Hello {
public static void main(String... a) {
JarInfo info = new JarInfo(); …
```

Jar info changes

---

.github/workflows/ion-java-performance-regression-detector.yml

N/A
This PR updates the test data of benchmarking process in order to provide more varieties of test data, and also improves the visualization of the results of the workflow, here are some explanations of these changes:
**Test data:**
Updates the ion schema files which are used for generating test ion data. After updating the schema, the workflow is able to use the data with more complicated structures to benchmark the performance of IonJava.
Here are the schema files:
- [Sexpression.isl](https://github.com/linlin-s/ion-java-benchmark-cli/blob/08cd9acefc94ce0afa9a9a0c44ca3c23e77b100f/tst/com/amazon/ion/workflow/Sexpression.isl)
- [nestedList.isl](https://github.com/linlin-s/ion-java-benchmark-cli/blob/08cd9acefc94ce0afa9a9a0c44ca3c23e77b10 …

Updates ion-java-performance-regression-detector workflow.

---

src/com/amazon/ion/impl/IonReaderBinaryIncremental.java

The incremental reader's implementation of `decimalValue`, `bigDecimalValue`, and `bigIntegerValue` use scratch space ([example](https://github.com/amzn/ion-java/blob/master/src/com/amazon/ion/impl/IonReaderBinaryIncremental.java#L1698)). `decimalValue` and `bigIntegerValue` use this scratch space for all values, while `bigDecimalValue` only use it for values with coefficients that consume at least 8 bytes.
The scratch space is [incorrectly declared static](https://github.com/amzn/ion-java/blob/master/src/com/amazon/ion/impl/IonReaderBinaryIncremental.java#L1377), which causes the same space to be used by multiple readers when they are accessed concurrently.
The fix for the bug is simply to make the scratch space non-static; the fact that it is static at all …

Fixes a bug in the incremental reader that caused certain Decimal, BigDecimal, and BigInteger values to be read incorrectly in multi-reader contexts.

---

.github/workflows/ion-java-performance-regression-detector.yml

https://github.com/amzn/ion-java/issues/448
The purpose of having `ion-java-performance-regression-detection` workflow is to detect if the incoming commit has performance regression comparing to the existing commit on the top of `master` branch. Before updating the workflow, the workflow didn’t checkout the `pull_request` branch to fetch the incoming commit and compared the performance between the wrong commits. This PR fixes the issue by updating the `checkout` repository steps.
- Step: Checkout ion-java from the new commit.
When `checkout` the repository, refer to the `pull_request` branch to get the `HEAD` commit.
- Step: Build ion-java from the new commit
Add `git submodule init` and `git submodule update` to initialize the submodule …

Update ion-java-regression-detection workflow.

---

.github/workflows/create-gitHub-prerelease-after-fast-forward-check.yml
.github/workflows/version-bump-and-fast-forward-check.yml

N/A
This PR adds two workflows to create ion-java GitHub pre-release. In the workflow, there are some steps to help check version number bump and also check whether the new release is fast-forward compared to the last release. Here are some explanation and examples about how these workflows work.
- Version-bump-and-fast-forward-check:
This workflow will be triggered when there is a PR created. The first part of this workflow is to check whether this new PR contains version number change. If there is no version number bump included in this PR, the workflow will be executed successfully without executing the steps of checking fast-forward. Here is the example: https://github.com/linlin-s/ion-java/pull/23
- If there is version number bump in …

Adds workflows to create ion-java prerelease on GitHub.

---

.github/workflows/publish-release-artifacts.yml
build.gradle.kts

None
* Adds [Gradle plugin](https://github.com/CycloneDX/cyclonedx-gradle-plugin) for [CycloneDX](https://cyclonedx.org/) so that we can automatically generate a Software Bill of Materials (SBOM) that meets the National Telecommunications and Information Administration (NTIA) requirements.
* Updates the release workflow to generate and upload the BOM to the GitHub release.
* I looked around for how to distribute the SBOM, but as far as I can tell, the NTIA doesn't have any specific guidance for that. The [executive order](https://www.whitehouse.gov/briefing-room/presidential-actions/2021/05/12/executive-order-on-improving-the-nations-cybersecurity/) says we should "[provide] a purchaser a Software Bill of Materials (SBOM) for each …

Adds Software BOM to releases

---

README.md

Updated to working cookbook url https://amazon-ion.github.io/ion-docs/guides/cookbook.html
*Issue #, if available:*  Clicking on cookbook url returns a 404
*Description of changes:* Updated to working cookbook url in Readme file

Fixing Ion Cookbook url

---

build.gradle.kts
test/com/amazon/ion/impl/IonRoundtripConcurrencyStressTest.java

Fixes #459
*Issue #, if available:* #459
With the patch of #436 reverted, the `round_trip_INT` and `round_trip_DECIMAL` test cases reliably fail, demonstrating that these tests should  be sufficient to catch that sort of regression. They ought to be expanded to other reader/writer options, but this is a good start.
I really enjoyed how simple it is to write repeating and concurrent tests with [`tempus-fugit`](https://github.com/tobyweston/tempus-fugit). It would be even better if I could *also* parameterize the tests cleanly, but I haven't seen a way yet. I suppose I could write some custom runner that builds cooperation between `ConcurrentTestRunner` and `JUnitParamsRunner`... or perhaps we could move our tests to JDK 8+ while leaving implementation in the …

Add a concurrency stress test

---

.github/workflows/PR-content-check.yml
.github/workflows/ion-java-performance-regression-detector.yml
.github/workflows/ion-test-driver.yml

Signed-off-by: Linlin Sun <linls@amazon.com>
https://github.com/amazon-ion/ion-java/issues/465
This PR adds a workflow `PR-content-check` to help us check whether there is any source code changes in the incoming PR. If the changed is detected, the workflow will be completed and executed successfully. When` PR-content-check` workflow is completed successfully,` ion-test-driver`and `ion-java-regression-detection` workflows will be triggered. If the `PR-content-check` is failed, `ion-test-driver` and `ion-java-regression-detection` will not be executed.
This PR also updated the version of `actions/checkout`
_Test:_
- [Workflow execution status when there's no changes happened under `src` folder.](https://github.com/linlin-s/ion-java/pull/34) …

Add steps to check if there is any source code changed in the incoming pull request.

---

src/com/amazon/ion/impl/_Private_IonTextAppender.java

`ion-java` serializes Integers and Decimals using `BigInteger.toString()`, which is inefficient for integers that fit into a `long`. A simple way to speed up serialization is to check if the `BigInteger` fits into a `long`, extract the `long` value and use the `Long.toString()` method to serialize the number.
I have a JMH benchmark ([source](https://gist.github.com/camilo-amzn/85bf0af111583f8a980d4cc491b15408)) with [results](https://gist.github.com/camilo-amzn/7775a2502161a8adac93e0953f626fbc) that prove that:
a) speedups for small, `long`-sized numbers are from 2.5x to 4.8x using `Long.toString()`, and
b) adding the `compareTo()` conditionals doesn't make the worse case much slower to what already is. That means, for integers bigger than a `long`, serialization …

make BigInteger serialization faster on long-sized numbers

---

.github/workflows/ion-java-performance-regression-detector.yml

N/A
This PR fixes the error in ion-java-performance-regression-detection workflow caused by [separating ion-data-generator from ion-java-benchmark-cli](https://github.com/amazon-ion/ion-java-benchmark-cli/pull/55).

Fix the error caused by separating ion-data-generator from ion-java-benchmark-cli.

---

build.gradle.kts
gradle/wrapper/gradle-wrapper.properties

Also upgrade to Gradle 8.0.2, as the taskinfo Gradle plugin now works with Gradle versions > 7.5.1.
*Issue #, if available:* 
* Fixes #259 by obviating it
* Enables progress on:
* #64
* #266 
* #298
* #425 
This will allow adoption of Java 8 features like lambdas, functional interfaces, method references, interface default implementations... it will be so great to start using a Java version that's only 9 years old. 
This will also allow us to adopt JUnit 5 and other libraries that require a minimum version of Java 8.

Target Java 8

---

build.gradle.kts

Good stuff is in JUnit 5. Better parallelization and assertions, `assertThrows(...)`, better IDE integration, etc. etc. 
By adding `maxParallelForks` I cut test time from `5m 16s` to `3m 26s` on my laptop.

Use JUnit 5

---

build.gradle.kts

We already can't publish `-SNAPSHOT` versions, and the task graph part of this is always evaluating to `false`, rendering it impossible to sign release versions.

 Fix signing task `onlyIf` restriction 

---

test/com/amazon/ion/impl/IonRoundtripConcurrencyStressTest.java

Before this change, I observed that the concurrency stress test would fail locally on 20-30% of runs. The cause was that the `toIon` method was closing its `IonReader` instance *before* parsing the value. Because `IonReader.close()` returns the UTF-8 decoding buffer to a pool shared across threads, this led to a race condition where sometimes a different thread was able to modify the UTF-8 encoding buffer before the current thread was finished parsing from it.
We moved to Java 8 after the stress test was authored. Now, we can use try-with-resources to ensure the reader is closed at the right time. I applied this change to the `toBytes` method as well for consistency, even though the existing logic there was correct. I also marked the builders `immutable()` even …

Fixes concurrency stress test to avoid spurious failures.

---

src/com/amazon/ion/IonReader.java
src/com/amazon/ion/impl/IonReaderBinaryIncremental.java
src/com/amazon/ion/impl/IonReaderBinarySystemX.java
src/com/amazon/ion/impl/IonReaderTextSystemX.java
src/com/amazon/ion/impl/IonReaderTreeSystem.java
test/com/amazon/ion/streaming/ReaderTest.java

The ability to read decimal values as BigInteger does not appear to be used and is inefficient for decimal values with large exponents.
This is more-or-less a copy of #522, except that this is not dependent on any other PRs.

Removes support for reading decimal values as BigInteger

---

.github/workflows/ion-java-performance-regression-detector.yml
.github/workflows/main.yml
build.gradle.kts

None
Setting the target and source compatibility compiler options to JDK 8 is insufficient for ensuring JDK 8 compatibility of the JAR that we publish. We need to set the `release` option, which is not supported by JDK 8 `javac`, so we're dropping support for _building_ with JDK 8.
See https://saker.build/blog/javac_source_target_parameters/index.html
This is a two way door. In theory, it is possible to add some conditional logic to the Gradle build script to only set this option when compiling with JDK 9 or higher, but I don't think we have a compelling reason for doing that right now.

Fix JDK 8 compatibility

---

build.gradle.kts

None.
Avoid bundling jquery until we figure out whether there are any licensing requirements.

Set NoIndex for Javadoc jar to avoid bundling jquery

---

.github/workflows/ion-java-performance-regression-detector.yml
src/com/amazon/ion/impl/IonReaderTextRawTokensX.java

None.
Changes `skip_over_container` to use iteration instead of recursion.

Iteratively skip containers in Ion Text reader

---

src/com/amazon/ion/impl/bin/IonRawBinaryWriter.java
src/com/amazon/ion/impl/bin/WriteBuffer.java
test/com/amazon/ion/impl/bin/WriteBufferTest.java

N/A
This PR introduces an optimization by removing the patch buffer used for storing length data of containers or annotations. The PatchLength and PatchPoint are replaced with the length data. This eliminates the need for writing length data to the patch buffer and simplified the data transfer process. By pass the length information as a field with the PatchPoint, the unnecessary memory allocations will be eliminated, and this change also helps the maintainability of the codebase.
Here is the comparison results from benchmarking a write of data equivalent to the a stream of stream of 194617 nested binary data using IonWriter(binary). The output data will write into an in-memory buffer. (5 forks, 10 iterations, 10 warmups)
**Preallocation …

Removes patch buffer and writes the patch length to the outputStream directly.

---

src/com/amazon/ion/impl/lite/IonValueLite.java

https://github.com/amazon-ion/ion-java/pull/546#discussion_r1320264527
Uses Arrays.copyOf for growing iteration stacks, instead of growing/copying the arrays manually. This change is performance neutral.

Uses Arrays.copyOf for growing iteration stacks.

---

src/com/amazon/ion/impl/bin/Symbols.java
src/com/amazon/ion/impl/lite/IonBlobLite.java
src/com/amazon/ion/impl/lite/IonBoolLite.java
src/com/amazon/ion/impl/lite/IonClobLite.java
src/com/amazon/ion/impl/lite/IonContainerLite.java
src/com/amazon/ion/impl/lite/IonDatagramLite.java
src/com/amazon/ion/impl/lite/IonDecimalLite.java
src/com/amazon/ion/impl/lite/IonFloatLite.java
src/com/amazon/ion/impl/lite/IonIntLite.java
src/com/amazon/ion/impl/lite/IonListLite.java
src/com/amazon/ion/impl/lite/IonLobLite.java
src/com/amazon/ion/impl/lite/IonNullLite.java
src/com/amazon/ion/impl/lite/IonSequenceLite.java
src/com/amazon/ion/impl/lite/IonSexpLite.java
src/com/amazon/ion/impl/lite/IonStringLite.java
src/com/amazon/ion/impl/lite/IonStructLite.java
src/com/amazon/ion/impl/lite/IonSymbolLite.java
src/com/amazon/ion/impl/lite/IonTextLite.java
src/com/amazon/ion/impl/lite/IonTimestampLite.java
src/com/amazon/ion/impl/lite/IonValueLite.java

Improves the iterative traversal technique introduced in #542 and applies it to `IonValue.hashCode`. Makes performance optimizations that encourage method inlining, reduce the depth of the call stack, and eliminate redundant logic.
After this change, the hash codes generated by `IonValue.hashCode` are exactly the same as before. I verified this by gathering hash codes from a variety of synthetic and real-world datasets using the previous and current commits.
Datasets:
* entry.10n - 40 KB, containing deeply-nested structs with recurring structure, short- and medium-length strings, and numeric values.
* committed.10n - 140 B, single top-level struct with local symbol table.
* log.10n - 22MB, containing nested structs with recurring structure, symbols, annotations, …

Iteratively traverses the document during IonValue.hashCode; improves IonValue.writeTo performance.

---

src/com/amazon/ion/impl/lite/IonContainerLite.java
src/com/amazon/ion/impl/lite/IonValueLite.java
test/com/amazon/ion/ContainerTestCase.java

Applies the iterative technique in #542 to `IonValue.makeReadOnly`. 
Datasets:
* entry.ion - 225 KB, containing deeply-nested structs with recurring structure, short- and medium-length strings, and numeric values.
* committed.10n - 140 B, single top-level struct with local symbol table.
* log.10n - 22MB, containing nested structs with recurring structure, symbols, annotations, and numeric values.
| dataset                | before (us/op) | after (us/op)       |
| -----------------| ---------------|-----------------|
| entry.ion              |  0.759 	        | 0.775 (+2.10)  |
| committed.10n    |  0.762             | 0.758 (-0.52%)   |
| log.10n                 | 0.848              | 0.858 (+1.17%) |

Iteratively traverses the document during IonValue.makeReadOnly

---

src/com/amazon/ion/impl/lite/IonBlobLite.java
src/com/amazon/ion/impl/lite/IonBoolLite.java
src/com/amazon/ion/impl/lite/IonClobLite.java
src/com/amazon/ion/impl/lite/IonContainerLite.java
src/com/amazon/ion/impl/lite/IonDatagramLite.java
src/com/amazon/ion/impl/lite/IonDecimalLite.java
src/com/amazon/ion/impl/lite/IonFloatLite.java
src/com/amazon/ion/impl/lite/IonIntLite.java
src/com/amazon/ion/impl/lite/IonListLite.java
src/com/amazon/ion/impl/lite/IonNullLite.java
src/com/amazon/ion/impl/lite/IonSequenceLite.java
src/com/amazon/ion/impl/lite/IonSexpLite.java
src/com/amazon/ion/impl/lite/IonStringLite.java
src/com/amazon/ion/impl/lite/IonStructLite.java
src/com/amazon/ion/impl/lite/IonSymbolLite.java
src/com/amazon/ion/impl/lite/IonTimestampLite.java
src/com/amazon/ion/impl/lite/IonValueLite.java
test/com/amazon/ion/CloneTest.java
test/com/amazon/ion/IonValueTest.java

This PR introduces the concept of "shallow clone" vs. "deep clone". Values of every type have a "shallow clone" implementation. For scalars, shallow clone clones all information about the value. For containers, shallow clone clones the container but not its children. Deep clone is only applicable for containers, and clones the container and all child values. `IonContainerLite.deepClone` contains the bulk of the iterative clone logic added in this PR; this was previously performed recursively (via `IonValue.clone`) in `IonContainerLite`'s copy constructor.
A key goal of this PR was to be at least performance-neutral. In order to achieve that, I had to make some optimizations that were not required to simply get the new implementation to work. This involved:
* …

Makes IonValue.clone iterative and improves clone performance.

---

src/com/amazon/ion/impl/lite/IonValueLite.java
src/com/amazon/ion/util/Equivalence.java
test/com/amazon/ion/util/EquivalenceTest.java

Adds a configurable maximum comparison depth to Equivalence. The default is 1000, which should be ample for existing usages.
This change had no observable performance impact in local tests.

Adds a configurable maximum comparison depth to Equivalence.

---

src/com/amazon/ion/impl/lite/IonValueLite.java
test/com/amazon/ion/impl/IonWriterTestCase.java

Before 1.10.3, calling `IonValue.writeTo` and providing an `IonWriter` with annotations set caused those annotations to be overwritten with the annotations on the `IonValue`. 1.10.3 introduced behavior that caused the annotations set on the `IonWriter` to persist if no annotations were present on the `IonValue`. This PR restores the pre-1.10.3 behavior.
Separately, we can discuss which behavior we think is the least surprising or most correct.

Restores previous behavior when IonValue.writeTo is called with a writer that has annotations set.

---

src/com/amazon/ion/impl/lite/IonStructLite.java
test/com/amazon/ion/StructTest.java

The context is used to determine which container a child value belongs to (among other purposes). This change correctly sets the context of cloned values to the parent container, allowing those values to be removed from that parent container later.

Fixes a bug in that prevented the correct IonContext from being copied via IonStruct.cloneAndRemove and IonStruct.cloneAndRetain.

---

src/com/amazon/ion/impl/lite/IonStructLite.java
test/com/amazon/ion/StructTest.java

None
Fixes a NullPointerException that can occur when calling `cloneAndRemove` or `cloneAndRetain` on an empty IonStruct.

Fix NPE in IonStructLite.doClone()

---

src/com/amazon/ion/impl/bin/IonRawBinaryWriter.java
test/com/amazon/ion/impl/bin/IonRawBinaryWriterTest.java

None
Fixes a NPE that can occur when passing a null value to `setTypeAnnotationSymbols()`.

Fix NPE in IonRawBinaryWriter

---

.github/workflows/scorecard.yml

*Issue #, if available:* #575
This is the recommended setup for incorporating the OSSF Scorecard action so that we can evaluate what goes into our Sonatype Safety Rating on Maven Central. 
See: 
* https://github.com/marketplace/actions/ossf-scorecard-action#workflow-setup-required

 Add an OSSF Scorecard action

---

.github/workflows/main.yml

*Issue #, if available:* https://github.com/amazon-ion/ion-java/security/code-scanning/16
*Description of changes:* 
We have a spurious "binary artifacts" alert from OSSF scorecard, for `gradle-wrapper.jar`. 
According to ossf/scorecard#2039 this ought to be silenced if we use the [gradle/wrapper-validation-action](https://github.com/gradle/wrapper-validation-action) action.
Gradle publishes this workflow to allow validation of gradle wrapper JARs to ensure that they actually are the jars published by Gradle. See: https://github.com/gradle/wrapper-validation-action#add-to-an-existing-workflow

Add gradle wrapper validation

---

.github/workflows/main.yml
.github/workflows/prepare-release.yml
.github/workflows/test-inspect-version-action.yml

*Issue #, if available:* #575
*Description of changes:* If I understand correctly, adding these explicit top-level read permissions ought to implicitly deny other permissions for the jobs. If the workflows work on this PR then it looks like these permissions should  be sufficient :)

Add top-level permissions to more workflows

---

.github/workflows/ion-java-performance-regression-detector.yml

[#390](https://github.com/amazon-ion/ion-java/issues/390)
This PR optimized ion-java-regression-detection workflow, there are two mainly changes included:
**1. Refactoring ion-java-regression-detection workflow to enhance the efficiency of regression detection process:**
- In our ion-java-regression-detection workflow, we have a step dedicated to detecting regression. This step involves a benchmarking process that tests various data and usage patterns. All these benchmarking tasks operate under a single job and run sequentially. To enhance efficiency, we implemented the matrix strategy. This change allows each usage pattern to be executed on separate jobs, running concurrently rather than one after another. As a result of this …

Optimize ion-java-regression-detection workflow to improve the accuracy.

---

src/com/amazon/ion/IonCursor.java
src/com/amazon/ion/IvmNotificationConsumer.java
src/com/amazon/ion/impl/IonReaderContinuableApplication.java
src/com/amazon/ion/impl/IonReaderContinuableCore.java

This is the first in what will be a series of pull requests that introduce a re-entrant, non-blocking binary reader implementation.
The core interface is `IonCursor`, which provides four operations:
* `nextValue()`
* `stepIntoContainer()`
* `stepOutOfContainer()`
* `fillValue()`
The first three look similar to methods provided by the `IonReader` interface, but they differ in that they are re-entrant: if there is not enough data to complete the operation, it may be retried and completed later when more data is available in the stream.
`fillValue()` is new. It requests the cursor to buffer the entirety of the current value, and works on both scalars and containers. Scalars must be filled before they can be parsed. Containers never need to be filled, but filling …

Adds IonCursor interface for reentrant reading; adds adapter interfaces from IonCursor to IonReader.

---

.github/workflows/ion-java-performance-regression-detector.yml

None, but see for example, #618, in which all performance regression workflow tasks are failing because the workflow is trying to check out a branch from the source repository that only exists in the forked repository.
Fixes the checkout step so that it specifies the repository of the PR head. Also changes the checkout step to handle the submodules at the same time.

Fix checkout step in regression workflow

---

src/com/amazon/ion/impl/IonReaderContinuableApplicationBinary.java
src/com/amazon/ion/impl/IonReaderContinuableTopLevelBinary.java
src/com/amazon/ion/impl/LocalSymbolTable.java
src/com/amazon/ion/impl/_Private_IonBinaryWriterBuilder.java
src/com/amazon/ion/impl/_Private_LocalSymbolTable.java
src/com/amazon/ion/impl/_Private_Utils.java
test/com/amazon/ion/DatagramTest.java
test/com/amazon/ion/impl/IonReaderContinuableTopLevelBinaryTest.java
test/com/amazon/ion/system/IonBinaryWriterBuilderTest.java

Restores previous behavior for three cases, which map to the three modified unit test classes in the diff.
1. [DatagramTest.java](https://github.com/amazon-ion/ion-java/compare/local-symtab-consistency?expand=1#diff-7ec89a6bf5726ac2177fdafdf09ab2215c6e3e217f91a22fae8ebbe0dbc2f5c4): before this PR, the new binary reader always returned an immutable view of its local symbol table. However, there are cases where the reader's symbol table is transferred either to a writer or to an IonDatagram. In those cases the user can add to the symbol table, requiring it to be mutable. All existing tests covered the transfer of a symbol table from a *text* reader only. The new test tests transferring a symbol table from the binary reader and verifying that subsequent changes to …

Restores the previous binary reader implementation's local symbol table handling behavior for several edge cases.

---

src/com/amazon/ion/impl/IonCursorBinary.java
src/com/amazon/ion/impl/IonReaderContinuableTopLevelBinary.java
test/com/amazon/ion/streaming/SeekableReaderTest.java

The `SpanProvider` and `SeekableReader` facets allow users to retrieve `Span` objects that point to the value at which a reader is currently positioned, and later seek a reader to that position.
Usually, users seek *back* to spans previously created by the same reader. However, sometimes users will create a span using one reader and then try to seek a different reader to that span. This works as long as both readers point at the same data. Existing tests only tested seeking to spans created by the same reader.
Before this change, if the reader receiving the span to seek to had not yet read any data (i.e., had not yet encountered an IVM), it would be in a state where it considered all type ID bytes invalid. This change fixes that by determining the span's Ion …

Makes the binary reader set the encoding version when seeked to a span.

---

src/com/amazon/ion/impl/IonCursorBinary.java
test/com/amazon/ion/streaming/SeekableReaderTest.java

Seeking the reader to a Span is supposed to cause the reader to treat that Span as if it were at the top level. Before this fix, the added test failed because the reader retained the `parent` pointer to the parent container after the seek, causing the `expectTopLevel` assertion to fail.

Ensures that spans are treated as if they are at the top level even when hoisted from below the top level.

---

src/com/amazon/ion/impl/IonReaderContinuableCoreBinary.java
test/com/amazon/ion/streaming/ReaderIntegerSizeTest.java

Before this change, the new reader implementation classified all Ion `int` values that consumed 4 binary Ion UInt bytes as Java `long`. This was conservative, ensuring that `IonReader.getIntegerSize()` would always return a Java type at least as large as necessary to hold the value (but sometimes larger). The goal was to simplify the implementation of `getIntegerSize`.
However, some applications depend on `int` values being classified accurately. Typically this is the case when an object mapping library like Jackson is used on top of ion-java for round-tripping values from Java classes. When a class is defined with a capital-I `Integer` field and that field is round-tripped as a `Long`, raw casts to `Integer` will fail. Additionally, unit tests that simply …

Accurately classifies all int values by size, rather than conservatively classifying all 4-byte ints as Java longs.

---

src/com/amazon/ion/impl/_Private_RecyclingQueue.java
src/com/amazon/ion/impl/_Private_RecyclingStack.java
src/com/amazon/ion/impl/bin/IonRawBinaryWriter.java

N/A
This PR introduces optimizations to improve memory usage and avoid unnecessary allocations. The following changes are included in this PR:
1. Instead of maintaining the patch list for both the container level and `IonRawBinaryWriter`, we only keep the `IonRawBinaryWriter` level patch list (this patch list is composed by the patch list for containers within the current scope)during the writing process. Previously, we needed to append the child container's patch list after the parent container to maintain the accurate sequence of the patch points. With the change, we use a patch point placeholder for the parent container's patch information. If there is a patch point created for the current container, we override the placeholder with …

Implements patch list as a single contiguous array of reusable PatchPoint instances.

---

src/com/amazon/ion/impl/bin/IonEncoder_1_1.java
src/com/amazon/ion/impl/bin/Ion_1_1_Constants.java
src/com/amazon/ion/impl/bin/OpCodes.java
test/com/amazon/ion/impl/bin/IonEncoder_1_1Test.java

None
Adds functions to write symbols (addressed and inline), strings, blobs, clobs, and annotations that have symbol addresses.

Adds support for text and lob types and some annotations

---

src/com/amazon/ion/impl/IonCursorBinary.java
src/com/amazon/ion/impl/IonReaderContinuableCoreBinary.java
test/com/amazon/ion/impl/IonReaderContinuableTopLevelBinaryTest.java

Addresses feedback from #641 
While adding more tests I was reminded that we added float16 support to the Ion 1.1 spec, so I added support for normalized float16 values in this PR. I opened the #648 for denormalized values.

Adds support for reading binary normalized half-precision floats; adds more tests for numeric types.

---

src/main/java/com/amazon/ion/impl/IonReaderContinuableCoreBinary.java
src/main/java/com/amazon/ion/impl/IonTypeID.java
src/main/java/com/amazon/ion/impl/bin/OpCodes.java
src/test/java/com/amazon/ion/impl/IonReaderContinuableTopLevelBinaryTest.java

Read Ion 1.1 decimals as BigDecimal or Decimal. Only the latter supports negative zero. The changes to IonTypeID are to comply with https://github.com/amazon-ion/ion-docs/pull/286.

Adds support for reading binary Ion 1.1 decimals.

---

src/main/java/com/amazon/ion/impl/IonReaderContinuableApplicationBinary.java
src/main/java/com/amazon/ion/impl/IonReaderContinuableCoreBinary.java
src/test/java/com/amazon/ion/impl/IonReaderContinuableTopLevelBinaryTest.java

Note: no source changes were needed in this PR to support blob/clob, as the only changes from Ion 1.0 were already made in IonTypeID.

Adds support for reading binary Ion 1.1 string values, symbol values with inline text, blobs, and clobs.

---

src/main/java/com/amazon/ion/impl/Ion11Writer.kt
src/main/java/com/amazon/ion/impl/IonWriter_1_1.kt

Adds an interface that can be used for raw writers (and extended for other writer types that build on top of it).

Adds IonWriter_1_1 interface

---

src/main/java/com/amazon/ion/impl/IonCursorBinary.java
src/main/java/com/amazon/ion/impl/IonReaderContinuableCoreBinary.java
src/test/java/com/amazon/ion/impl/IonReaderContinuableTopLevelBinaryTest.java

Makes some optimizations and simplifications/cleanups, and adds a few more tests.
There are two key optimizations:
1. 1- and 2-byte short circuiting when reading FlexInt and FlexUInts
2. Avoiding creating BigInteger coefficients when possible when the reader asks for a Decimal (not BigDecimal, as this optimization was already applied there).
Here are some performance comparisons (in milliseconds per operation, lower is better):
**Ints (all fit in long, mostly 8 bytes)**
|Ion 1.0|Ion 1.1 before this PR|Ion 1.1 after this PR|
|-|-|-|
|27.880|23.247|23.197|
**Ints (requiring BigInteger)**
|Ion 1.0|Ion 1.1 before this PR|Ion 1.1 after this PR|
|-|-|-|
|30.809|34.238|33.945|
**Decimals (small, no BigInteger coefficients), via bigDecimalValue**
|Ion 1.0|Ion 1.1 before …

Optimizes parsing of binary Ion 1.1 numeric types.

---

.github/workflows/main.yml
src/main/java/com/amazon/ion/_private/SuppressFBWarnings.kt
src/main/java/com/amazon/ion/impl/IonReaderContinuableCoreBinary.java
src/main/java/com/amazon/ion/impl/IonTypeID.java
src/main/java/com/amazon/ion/impl/_Private_IonConstants.java
src/main/java/com/amazon/ion/impl/bin/Ion_1_1_Constants.java

None
I realized that in #661, I forgot to push some changes in one file, and so the code in the PR wouldn't even compile. To prevent that from happening again, I'm making the CI build run for PRs regardless of the branch.
In doing so, I also discovered some SpotBugs warnings. Some of the warnings are for things that we are intentionally doing, so I added a `SuppressFBWarnings` annotation that can be used to mark when we're doing this intentionally. In some cases, I added some code to make the compiler happy.

Run CI builds for all branches

---

src/main/java/com/amazon/ion/impl/IonTypeID.java
src/main/java/com/amazon/ion/impl/IonWriter_1_1.kt
src/main/java/com/amazon/ion/impl/bin/FlexInt.kt
src/main/java/com/amazon/ion/impl/bin/IonRawBinaryWriter_1_1.kt
src/main/java/com/amazon/ion/impl/bin/Ion_1_1_Constants.java
src/main/java/com/amazon/ion/impl/bin/OpCodes.java
src/main/java/com/amazon/ion/impl/bin/WriteBuffer.java
src/test/java/com/amazon/ion/impl/bin/IonRawBinaryWriterTest_1_1.kt

None
Adds support for SExp and Structs in the `IonRawBinaryWriter_1_1`.

Adds support for writing Ion 1.1 sexps and structs

---

src/main/java/com/amazon/ion/impl/bin/Ion_1_1_Constants.java
src/test/java/com/amazon/ion/impl/bin/IonRawBinaryWriterTest_1_1.kt

See https://github.com/amazon-ion/ion-java/pull/671#discussion_r1425861190
Changes the `SID_TO_FLEX_SYM_SWITCH_MARKER` constant from `0` to `FlexSym.ZERO`.

Fix SID_TO_FLEX_SYM_SWITCH_MARKER

---

src/main/java/com/amazon/ion/impl/IonCursorBinary.java
src/main/java/com/amazon/ion/impl/IonReaderContinuableApplicationBinary.java
src/main/java/com/amazon/ion/impl/IonReaderContinuableCoreBinary.java
src/main/java/com/amazon/ion/impl/IonTypeID.java
src/test/java/com/amazon/ion/TestUtils.java
src/test/java/com/amazon/ion/impl/IonReaderContinuableTopLevelBinaryTest.java
src/test/java/com/amazon/ion/impl/bin/IonRawBinaryWriterTest_1_1.kt

Length-prefixed structs with both SID and VarSym field names. Support for delimited structs will follow in a separate PR.

Adds support for reading Ion 1.1 length-prefixed structs.

---

src/main/java/com/amazon/ion/impl/IonCursorBinary.java
src/main/java/com/amazon/ion/impl/IonReaderContinuableApplicationBinary.java
src/main/java/com/amazon/ion/impl/IonReaderContinuableCoreBinary.java
src/main/java/com/amazon/ion/impl/IonTypeID.java
src/main/java/com/amazon/ion/impl/MarkerList.java
src/test/java/com/amazon/ion/TestUtils.java
src/test/java/com/amazon/ion/impl/IonReaderContinuableTopLevelBinaryTest.java
src/test/java/com/amazon/ion/impl/bin/IonRawBinaryWriterTest_1_1.kt

This required adding FlexSym support, which is why this PR is bigger than the title might suggest. You'll notice there are some methods that look similar to others, and may be candidates for DRYing up. I'd like to leave that for a future pass where we can set aside the time to analyze the potential performance impacts.

Adds support for reading binary Ion 1.1 annotations.

---

src/main/java/com/amazon/ion/impl/IonWriter_1_1.kt
src/main/java/com/amazon/ion/impl/bin/IonRawBinaryWriter.java
src/main/java/com/amazon/ion/impl/bin/IonRawBinaryWriter_1_1.kt
src/main/java/com/amazon/ion/impl/bin/Ion_1_1_Constants.java
src/main/java/com/amazon/ion/impl/bin/OpCodes.java
src/main/java/com/amazon/ion/impl/bin/WriteBuffer.java
src/test/java/com/amazon/ion/impl/bin/IonRawBinaryWriterTest_1_1.kt
src/test/java/com/amazon/ion/impl/bin/WriteBufferTest.java

None
Updates the signature of `stepInEExp()` and implements it.
There are a couple of incidental changes that I've called out with a 🗺️ comment.
~Potentially controversial... this PR uses the end delimiter to signal the end of a macro's args if that macro has rest-parameter in it's signature.~

Adds support for macros to IonRawBinaryWriter_1_1

---

src/main/java/com/amazon/ion/impl/IonReaderContinuableCoreBinary.java
src/test/java/com/amazon/ion/impl/IonReaderContinuableTopLevelBinaryTest.java

Closes #674 
Closes #677 
See the linked issue. Note: I am not changing the documentation or associated error messages to officially endorse doing this. In fact, this would be one of the conversions we'd want to remove as part of #523. For now, we preserve the previous undocumented behavior to avoid breaking a small number of users that depend on it.

Adds the ability to read an Ion int as a Java double, Decimal, or BigDecimal for consistency with the previous implementation.

---

src/main/java/com/amazon/ion/BufferConfiguration.java
src/main/java/com/amazon/ion/IonBufferConfiguration.java
src/main/java/com/amazon/ion/impl/IonCursorBinary.java
src/main/java/com/amazon/ion/impl/IonReaderContinuableApplicationBinary.java
src/main/java/com/amazon/ion/system/IonReaderBuilder.java
src/test/java/com/amazon/ion/impl/IonReaderContinuableTopLevelBinaryTest.java
src/test/java/com/amazon/ion/system/IonReaderBuilderTest.java

Before this change, if the binary reader encountered an oversized value (due to either corruption of the header or an excessively large scalar), and no IonBufferConfiguration had been set, `NullPointerException` would be thrown. After this change, `IonException` is thrown with a helpful message. I added some tests to verify in both of the cases listed above that `IonException`s are thrown.

Handles the case where the reader unexpectedly encounters an oversized value, throwing IonException with a helpful message.

---

config/proguard/rules.pro

None.
When building IonJava using JDK 17 and running proguard, the resulting jar is incompatible with scala build tool and some bytecode manipulation libraries. This updates the proguard config so that proguard doesn't make those incompatible changes to our classes.
Why does this work? The `includecode` keyword tells proguard that the code of the "keep" classes may not be modified during optimization.

Updates proguard config to fix JDK 17 toolchain + Scala Build Tool compatibility issue

---

src/main/java/com/amazon/ion/impl/IonReaderContinuableCoreBinary.java
src/main/java/com/amazon/ion/impl/IonReaderTextSystemX.java
src/test/java/com/amazon/ion/streaming/ReaderIntegerSizeTest.java

Fixes #685 
Before the change, both the text and binary readers would fail with NPE on the added line 108 of ReaderIntegerSizeTest, where the method is called when the reader is not positioned on a value. The fixes ensure that `null` is returned in this case instead.

Ensures NullPointerException is not thrown from IonReader.getIntegerSize().

---

src/main/java/com/amazon/ion/impl/IonCursorBinary.java
src/main/java/com/amazon/ion/impl/IonReaderContinuableCoreBinary.java
src/main/java/com/amazon/ion/impl/IonReaderContinuableTopLevelBinary.java
src/test/java/com/amazon/ion/impl/IonCursorBinaryTest.java
src/test/java/com/amazon/ion/impl/IonReaderContinuableCoreBinaryTest.java
src/test/java/com/amazon/ion/system/IonReaderBuilderTest.java

Adds range checks so that `IonException` will be thrown rather than `IndexOutOfBoundsException` when malformed data would cause the reader to attempt to read beyond the end of the stream. This ends up having minimal performance impact with the current factoring.

Adds checks for malformed data that overflows the buffer.

---

src/main/java/com/amazon/ion/impl/IonRawTextWriter_1_1.kt
src/main/java/com/amazon/ion/impl/IonRawWriter_1_1.kt
src/main/java/com/amazon/ion/impl/bin/IonRawBinaryWriter_1_1.kt
src/test/java/com/amazon/ion/impl/IonRawTextWriterTest_1_1.kt
src/test/java/com/amazon/ion/impl/bin/IonRawBinaryWriterTest_1_1.kt

None.
Adds a raw test writer for Ion 1.1

Adds IonRawTextWriter_1_1

---

src/main/java/com/amazon/ion/impl/IonCursorBinary.java
src/test/java/com/amazon/ion/impl/IonReaderContinuableTopLevelBinaryTest.java

Description of changes:
InputStream implementations are allowed to skip fewer bytes than requested, and doing so does not necessarily indicate that the end of the stream has been reached. S3's `S3ObjectInputStream` has this behavior in certain cases.
Before this fix, the binary reader would throw an IonException for unexpected EOF if this happened when trying to skip of a scalar value that was not entirely buffered. After the fix, the reader will continue requesting to skip bytes from the stream until EOF is definitely reached or all requested bytes have been skipped.
The test`shouldNotFailWhenAnInputStreamProvidesFewerBytesThanRequestedWithoutReachingEofWithAnUnboundedBufferAndTheReaderSkipsTheValue` is the one that reproduced the problem, and now succeeds. The fix is similar to that of …

Handles the case where InputStream.skip provides fewer bytes than requested before reaching EOF.

---

src/main/java/com/amazon/ion/impl/IonCursorBinary.java

Closes #678 
This allows these objects to be garbage collected even if the user holds onto the IonReader reference after calling `close()`.

Sets binary reader buffers to null on close().

---

src/main/java/com/amazon/ion/impl/IonReaderContinuableCoreBinary.java
src/test/java/com/amazon/ion/impl/IonReaderContinuableCoreBinaryTest.java

#684 (note: this should also be done for the text reader)
The pre-1.11.0 binary reader would allow this in some cases, returning some form of `0` rather than throwing. If that behavior is desirable in certain applications, those applications should use `IonReader.isNullValue()` to check nullness and decide whether using a zero value in that case makes sense.

Ensures the binary IonReader throws when a value method that returns a primitive type is invoked on a null value.

---

src/main/java/com/amazon/ion/impl/IonReaderTextSystemX.java
src/test/java/com/amazon/ion/streaming/ReaderTest.java

Closes #702 
The assertion on line 609 was unnecessary; the assertion on line 611 was both wrong (should have been `>=`) and unnecessary because the next line throws an error that is more helpful than the assertion.
Before this change, the added test failed with AssertionError, which was wrong.

Removes assertions in IonReaderSystemTextX.stringValue().

---

src/main/java/com/amazon/ion/BufferConfiguration.java
src/main/java/com/amazon/ion/IonBufferConfiguration.java
src/main/java/com/amazon/ion/apps/BaseApp.java
src/main/java/com/amazon/ion/impl/BlockedBuffer.java
src/main/java/com/amazon/ion/impl/IonCursorBinary.java
src/main/java/com/amazon/ion/impl/IonReaderTextSystemX.java
src/main/java/com/amazon/ion/impl/ResizingPipedInputStream.java
src/main/java/com/amazon/ion/impl/UnifiedInputBufferX.java
src/main/java/com/amazon/ion/impl/UnifiedInputStreamX.java
src/main/java/com/amazon/ion/impl/_Private_IonConstants.java
src/main/java/com/amazon/ion/impl/_Private_Utils.java
src/test/java/com/amazon/ion/impl/IonCursorBinaryTest.java
src/test/java/com/amazon/ion/impl/ResizingPipedInputStreamTest.java
src/test/java/com/amazon/ion/impl/UnifiedInputBufferXTest.java
src/test/java/com/amazon/ion/impl/UnifiedInputStreamXTest.java

Arrays in Java must be indexed by integers (JLS 10.4), but the true maximum array size may be less than `Integer.MAX_VALUE`. True maximum array size is a JVM implementation detail, and varies by type and by JVM. We have this pinned at `Integer.MAX_VALUE - 8` because that's a fairly common value in the JDK itself, in classes such as `ConcurrentHashMap`, `InputStream`, `Hashtable`, `ByteArrayChannel`, etc.
In testing against a variety of JVMs and types the smallest maximum size I've seen is `Integer.MAX_VALUE - 2`, and the smallest maximum size I've seen reported is `Integer.MAX_VALUE - 6`
This change adds a constant  `_Private_IonConstants.ARRAY_MAXIMUM_SIZE` and uses the new constant where appropriate. 
Need for this safeguard was exposed by another bug which …

Add a _Private_IonConstants.ARRAY_MAXIMUM_SIZE

---

src/main/java/com/amazon/ion/impl/IonCursorBinary.java
src/test/java/com/amazon/ion/impl/IonReaderContinuableCoreBinaryTest.java

https://github.com/FasterXML/jackson-dataformats-binary/issues/469
A value's end index is calculated by adding the reader's current index in the buffer (`peekIndex`) to the value's declared length. Before this fix, the validation for a too-large end index (`endIndex < 0`) happened too early (before `peekIndex` had been added). This allowed for the possibility that a very large but valid value length could overflow when `peekIndex` was added, as exercised by the added test. When this happened for blob/clob values, `IonReader.byteSize()` would return a negative number, causing `NegativeArraySizeException` to be thrown from `IonReader.newBytes()`. After the fix, the reader throws `IonException` upon encountering the overflowing end index.
By …

Fixes a bug that allowed NegativeArraySizeException to be thrown from IonReader.newBytes().

---

src/main/java/com/amazon/ion/impl/IonReaderTextRawX.java
src/test/java/com/amazon/ion/util/TextTest.java

https://github.com/FasterXML/jackson-dataformats-binary/issues/471
Sometimes errors conveyed via `IonException` are recoverable, and sometimes they are not. In cases where these exceptions are not recoverable but the user tries anyway (by calling another method on the reader), the reader should fail cleanly by throwing another IonException. Before this fix, the added test failed with `AssertionError` [here](https://github.com/amazon-ion/ion-java/blob/master/src/main/java/com/amazon/ion/impl/IonReaderTextRawTokensX.java#L2668) because a save point had been started on a value that was later found to be invalid. The proposed fix clears the current save point if the current value is found to be malformed. This allows the reader to throw …

Allows the text reader to fail cleanly when the user attempts to recover after catching IonException, but recovery is not possible.

---

src/main/java/com/amazon/ion/impl/IonCursorBinary.java
src/test/java/com/amazon/ion/impl/IonReaderContinuableCoreBinaryTest.java

https://github.com/FasterXML/jackson-dataformats-binary/issues/473
Before this fix, the added test `expectIncompleteContainerToFailCleanlyAfterFieldSid` would fail with `ArrayIndexOutOfBoundsException`. The other two tests succeeded before and after the fix; I just wanted to be sure these cases were covered.

Fixes a bug that caused the binary reader not to fail cleanly when parsing incomplete containers in certain cases.

---

src/test/java/com/amazon/ion/impl/IonCursorBinaryTest.java

*Issue #, if available:* None
*Description of changes:* As the PR title says. 

Fix test name and doc comments

---

src/main/java/com/amazon/ion/impl/lite/IonContainerLite.java
src/main/java/com/amazon/ion/impl/lite/IonStructLite.java
src/main/java/com/amazon/ion/impl/lite/IonValueLite.java
src/test/java/com/amazon/ion/CloneTest.java

Releases v1.10.3 - v1.10.5 changed `IonValue.clone()` and `IonValue.makeReadOnly()` from recursive to iterative (see #557 and #549). One side effect of this change is that on clone, IonStructs no longer eagerly copied the cloned struct's (and all of its child structs') field maps, which are lazily created for structs with more than 5 fields as an optimization to enable faster field access.
In #630 we identified and fixed a bug that affected concurrent access of cloned, read-only structs with more than 5 members. The struct's field map was being populated in one thread while being accessed in another, resulting in non-deterministic behavior. The fix in #630 was to force a struct's field map to be populated upon being marked read-only, making it impossible for it …

Fixes a bug that made concurrent access of a large nested IonStruct unsafe when only its parent had been made read-only.

---

src/main/java/com/amazon/ion/impl/IonReaderContinuableApplicationBinary.java

The `symbolTokensById` cache was added to avoid repeatedly allocating `SymbolToken` wrappers when symbol lookup APIs that return `SymbolToken` were called. This provided a minor (<10%) speedup due to reduced allocation rate / GC churn in cases where such `SymbolToken` APIs were called frequently. However, it should be very uncommon for this to be the case, as users tend to use the equivalent APIs that return `String` instead, as most do not need to deal with symbols with unknown text.
There is some usage of these APIs within the IonJava DOM, but when using the DOM, other sources of slowdown tend to dominate. There is, however, a case where this cache can significantly _hurt_ performance within the DOM: when a small binary Ion value is loaded into the DOM from a …

Removes the binary reader's SymbolToken cache, which provided a minor optimization for certain cases but a major regression for others.

---

README.md
src/main/java/com/amazon/ion/IonValue.java

None
Recommends using `IonElement` instead of `IonValue`.

Adds recommendation to use IonElement

---

src/main/java/com/amazon/ion/impl/IonCursorBinary.java
src/test/java/com/amazon/ion/impl/IonReaderContinuableCoreBinaryTest.java

Related: PR #705 
While #705 addressed the case where the length plus the current buffer index overflows a long, this PR addresses the case where the length overflows by itself.

Adds a check for overflow when reading VarUInts.

---

build.gradle.kts
config/spotbugs/baseline.xml
src/main/java/com/amazon/ion/system/IonSystemBuilder.java
src/test/java/com/amazon/ion/system/IonSystemBuilderTest.java

These changes allow the user to set their own configurations for the `IonTextWriterBuilder` and `IonBinaryWriterBuilder` when using the `IonSystemBuilder`, bringing more flexibility.
Because this involved adding getters/setters, I had to update the SpotBugs `baseline.xml` file which was preventing the build from succeeding, and to fix a little bug in the Gradle configuration.

Allow custom writer configurations in IonSystemBuilder

---

src/main/java/com/amazon/ion/Timestamp.java
src/main/java/com/amazon/ion/_Private_Trampoline.kt
src/main/java/com/amazon/ion/impl/IonWriterSystemText.java
src/main/java/com/amazon/ion/impl/_Private_IonTextWriterBuilder.java
src/main/java/com/amazon/ion/system/IonTextWriterBuilder.java
src/test/java/com/amazon/ion/TimestampTest.java
src/test/java/com/amazon/ion/impl/TextWriterTest.java

The Timestamp class holds fractional precision in a BigDecimal, where in many cases that precision can be compactly conveyed (e.g. `0d-1000000`, which is a tuple of `(0, 1000000)`). In text, all those digits must be written explicitly. To avoid attempting to write an excessive number of digits, this PR proposes a configurable maximum, with the default set arbitrarily to 10,000, which is a preposterous number of digits. If the maximum is exceeded, an error is raised (rather than silently losing precision).
To avoid adding more public methods to `Timestamp`, I propose having all of `Timestamp`'s `toString`-like methods just use the default. In the unlikely event that a user needs to raise the limit, they can use a text writer to serialize the timestamp. The …

Adds a configurable limit to the number of timestamp fractional second digits that are written to text representations.

---

src/main/java/com/amazon/ion/impl/IonCursorBinary.java
src/test/java/com/amazon/ion/impl/IonReaderContinuableTopLevelBinaryTest.java

Fuzzing identified a case where this mattered. This is now captured in the added unit test. In summary, if the previous value was a struct, and the current value begins with an incomplete annotation wrapper, the reader would attempt to read additional bytes from the input to determine if the value was a symbol table. This could result in `ArrayIndexOutOfBoundsException`, as in this case, if those bytes are not available. Clearing the typeId between values ensures that the reader will never enter the symbol table determination logic when positioned on an incomplete annotation wrapper, allowing that logic to remain unchanged. After this fix, an `IonException` for unexpected EOF is thrown in this case.
By submitting this pull request, I confirm that my contribution …

Ensures that the cursor's value marker is fully reset between values.

---

build.gradle.kts
src/main/java/com/amazon/ion/_Private_Trampoline.kt

None
I noticed recently that some of our files are lacking a license header. I've added the `spotless` plugin to ensure that we have a license header on all new java and kotlin files going forward. I also included a check for unused imports in java, but that might be redundant with `spotbugs`. In kotlin, it's already checked by `ktlint`.
If you happen to forget to add license headers, you can have this tool add them automatically by running `./gradlew spotlessApply`.

Adds check for license headers and unused imports

---

src/main/java/com/amazon/ion/impl/IonCursorBinary.java
src/test/java/com/amazon/ion/GoodIonMultithreadedTest.java
src/test/java/com/amazon/ion/impl/IonReaderContinuableTopLevelBinaryTest.java

This is pretty basic for now. We can augment it over time to exercise a wider variety of access patterns. If you have any suggestions, please comment.
As proposed, the test randomly chooses a child value of each file to test. Testing every value at every depth would be more robust, but is likely more suited to a suite of long-running tests that are executed periodically, rather than the unit tests that are executed on each build. On my machine, the proposed test takes about 3 seconds.
During development I recorded some stats about the value type and container depths that were selected on various runs. I believe these show that the values tested are reasonably distributed across the types and depths available in the test data.
Types (key=type, value=number of …

Adds testing of IonValue's multithreaded contract over the 'good' ion-tests files.

---

src/main/java/com/amazon/ion/impl/bin/AbstractIonWriter.java

Employs the exact same technique from #368. The code is almost identical in both places; this PR does not aim to address the existing issue of duplication, which would require some refactoring. The fix from #368 affects the text writer, while this PR affects the binary writer.

Makes AbstractIonWriter.writeValues iterative.

---

src/test/java/com/amazon/ion/StructTest.java

Adds multithreaded access testing to the relevant hand-written tests in StructTest and the generated test `testRandomChanges()`.

Adds more multithreaded access testing to StructTest.

---

src/main/java/com/amazon/ion/impl/IonCursorBinary.java
src/main/java/com/amazon/ion/impl/IonReaderContinuableApplicationBinary.java
src/main/java/com/amazon/ion/impl/IonTypeID.java
src/test/java/com/amazon/ion/impl/IonCursorBinaryTest.java
src/test/java/com/amazon/ion/impl/IonReaderContinuableTopLevelBinaryTest.java

Any suggestions for simplification are appreciated. No performance testing has yet been done.

Adds support for reading binary Ion 1.1 delimited containers.

---

src/main/java/com/amazon/ion/impl/macro/Macro.kt
src/main/java/com/amazon/ion/impl/macro/MacroCompiler.kt
src/test/java/com/amazon/ion/impl/macro/MacroCompilerTest.kt

None
This updates the `MacroCompiler` to take care of a few "todo" items, support all the `*`, `+`, `!`, and `?` cardinality sigils, and remove the `[]` grouping syntax.

Fix macro parameter cardinality and minor todos

---

src/main/java/com/amazon/ion/impl/IonCursorBinary.java
src/test/java/com/amazon/ion/impl/IonCursorBinaryTest.java
src/test/java/com/amazon/ion/impl/IonReaderContinuableTopLevelBinaryTest.java

The `IonCursor` interface extends `Closeable`, which includes documentation on `close` that states that calling `close` after the resource is already closed has no effect. We do not define the behavior of the cursor when methods other than `close` are called after the cursor is closed, but I think it is reasonable for the cursor to remain in a `NEEDS_DATA` state, indicating that it is not positioned on a value.
Before the proposed changes, the added tests would fail with `NullPointerException` when the cursor attempted to access its buffer, which is set to `null` during `close`. Entering the `TERMINATED` state in "slow" mode allows the cursor to make use of existing termination checks that gate all of the slow mode APIs.
By submitting this pull request, I confirm …

Ensures that using a cursor after close has no effect.

---

.github/workflows/publish-release-artifacts.yml
build.gradle.kts

None
This skips the `spotless` checks when the build is running as part of the "Publish Release Artifacts" workflow, and also splits up the various gradle targets of that workflow into a few different workflow steps.

Improve automated release workflow

---

src/main/java/com/amazon/ion/impl/IonCursorBinary.java
src/main/java/com/amazon/ion/impl/bin/IonEncoder_1_1.java
src/test/java/com/amazon/ion/impl/IonReaderContinuableTopLevelBinaryTest.java
src/test/java/com/amazon/ion/impl/bin/IonEncoder_1_1Test.java
src/test/java/com/amazon/ion/impl/bin/IonRawBinaryWriterTest_1_1.kt

https://github.com/amazon-ion/ion-docs/issues/294
https://github.com/amazon-ion/ion-docs/pull/312
No negative performance impact observed.
Results (data: 7.8 MB of random 32- and 64-bit floats)
Read:
* Ion 1.0: 19.404 ms/op
* Ion 1.1 - BE: 19.667 ms/op
* Ion 1.1 - LE: 19.661 ms/op
Write:
* Ion 1.0: 9.166 ms/op
* Ion 1.1 - BE: 7.569 ms/op
* Ion 1.1 - LE: 7.365 ms/op
These results were gathered from a branch of ion-java-benchmark-cli with local edits to support Ion 1.1. Take the 1.0 vs 1.1 write results with a small grain of salt because they're not directly apples-to-apples: the 1.0 code exercises the user-level writer while the 1.1 code exercises the raw writer (because we don't have a user-level one yet). This shouldn't make a huge …

Makes Ion 1.1 floats little-endian.

---

src/main/java/com/amazon/ion/system/IonSystemBuilder.java

This reverts the part of commit 515870636d29b58b9bd3d2bf5f51c9b5e8980dd2 (#802) that changes the default charset to UTF-8.

Revert "Change IonSystemBuilder's default charset to UTF-8 (#802)"

---

src/main/java/com/amazon/ion/IonEncodingVersion.java
src/main/java/com/amazon/ion/system/IonBinaryWriterBuilder_1_1.java
src/main/java/com/amazon/ion/system/_Private_IonBinaryWriterBuilder_1_1.java
src/test/java/com/amazon/ion/IonEncodingVersionTest.java
src/test/java/com/amazon/ion/system/IonBinaryWriterBuilderTest.java
src/test/java/com/amazon/ion/system/IonBinaryWriterBuilder_1_1_Test.java
src/test/java/com/amazon/ion/system/IonWriterBuilderTestBase.java

The existing binary writer structure is complicated and confusing. Rather than attempting to further extend that, I propose a new builder interface for Ion 1.1 that mimics method signatures available on the 1.0 writer builder. For now I've chosen to include only the configuration options that I think we will definitely need. We can add more as we discover they are necessary. We will also want to add Ion 1.1-specific options, e.g. perhaps global flags for inline symbols.
I also propose the `IonEncodingVersion` pseudo-enum class for managing Ion encoding versions supported by the library. Making this a parameterized class enables the following new pattern:
```
IonBinaryWriterBuilder writerBuilder_1_0 = IonEncodingVersion.ION_1_0.binaryWriterBuilder(); …
```

Adds the IonEncodingVersion pseudo-enum and IonBinaryWriterBuilder_1_1 interface.

---

src/main/java/com/amazon/ion/impl/IonCursorBinary.java
src/test/java/com/amazon/ion/impl/IonCursorBinaryTest.java

Ensures that encountering an incomplete binary IVM causes clean failure.

Ensures that encountering an incomplete binary IVM causes clean failure.

---

src/main/java/com/amazon/ion/impl/IonCursorBinary.java
src/main/java/com/amazon/ion/impl/IonReaderContinuableApplicationBinary.java
src/main/java/com/amazon/ion/impl/bin/IonEncoder_1_1.java
src/main/java/com/amazon/ion/impl/bin/Ion_1_1_Constants.java
src/main/java/com/amazon/ion/impl/bin/WriteBuffer.java
src/test/java/com/amazon/ion/impl/IonReaderContinuableApplicationBinaryTest.java
src/test/java/com/amazon/ion/impl/IonReaderContinuableTopLevelBinaryTest.java
src/test/java/com/amazon/ion/impl/bin/IonEncoder_1_1Test.java
src/test/java/com/amazon/ion/impl/bin/IonRawBinaryWriterTest_1_1.kt
src/test/java/com/amazon/ion/impl/bin/WriteBufferTest.java

None
I found these problems while working on some round-trip testing of the Ion 1.1 writer. See 🗺️ comments descriptions of each issue.
All unit tests are passing—you can see that the `verify-jre-compatibility` workflow jobs are passing—but the main `build-and-test` job is failing because of a ktlint problem that I will look into later. The ktlint problem was not introduced by this change.

Fix several bugs in Ion 1.1 implementation

---

.editorconfig
build.gradle.kts
src/main/java/com/amazon/ion/system/_Private_IonBinaryWriterBuilder_1_1.java

None
Updates the KtLint version, cleans up the `.editorconfig` file, fixes some style violations in `build.gradle.kts`, and adds suppression annotations for two unhelpful spotbugs violations.
This means that `./gradlew check` now passes on the `ion-11-encoding` branch.

Minor fixes to get all of the quality checks to pass again.

---

src/main/java/com/amazon/ion/impl/bin/IonManagedWriter_1_1.kt

None
Makes sure that `IonManagedWriter_1_1` closes its `OutputStream`. Also reduces the visibility of some members of `IonManagedWriter_1_1` that should not have been public.

Make IonManagedWriter_1_1 close its OutputStream

---

src/main/java/com/amazon/ion/impl/IonReaderContinuableApplicationBinary.java
src/test/java/com/amazon/ion/streaming/SeekableReaderTest.java

Before this fix, the code assumed the following, which was included in a comment:
> // Note: because `symbols` only grows, `snapshot.listView` will always fit within `symbols`.
This was valid as long as the same reader that produced a span would always be hoisted to that span. However, the `SeekableReader` facet allows *different* readers to share spans as long as they are reading the same stream. When this is the case, the constraint asserted by the comment no longer holds: the reader that produced the span may have progressed far enough in the stream to encounter more symbols than would fit in the other reader's `symbols` array. In that case, before this fix, an `ArrayIndexOutOfBoundsException` would be thrown. After this fix, the reader that is hoisted to the …

Fixes a bug that prevented seeking to a span created from a different reader in a stream with a large number of symbols.

---

src/main/java/com/amazon/ion/impl/IonReaderContinuableCoreBinary.java
src/test/java/com/amazon/ion/impl/IonCursorTestUtilities.java
src/test/java/com/amazon/ion/impl/IonReaderContinuableCoreBinaryTest.java

Op codes `E1` - `E3` were being handled incorrectly.
This is only a partial fix. See TODO item in code diff for handling `E3`.

Attempt to fix Ion 1.1 symbols for OpCodes E1-E3

---

src/main/java/com/amazon/ion/impl/BufferedAppendableFastAppendable.kt
src/main/java/com/amazon/ion/impl/BufferedOutputStreamFastAppendable.kt
src/main/java/com/amazon/ion/impl/bin/IonManagedWriter_1_1.kt
src/main/java/com/amazon/ion/impl/bin/ManagedWriterOptions_1_1.kt
src/test/java/com/amazon/ion/Ion11Test.kt

None
* Adds a `_Private_FastAppendable` wrapper for `Appendable` that buffers until `flush()` is called.
* Added a basic test in `Ion11Test` to ensure that it handles encoding directives properly.
* I renamed `BlockedBufferingOutputStreamFastAppendable` to just `BufferedOutputStreamFastAppendable` and updated its `flush()` and `close()` behavior to be consistent with `OutputStreamFastAppendable`.
I know I've got another import change in this diff. I'm working separately to eliminate those.

Adds BufferedAppendableFastAppendable

---

.github/workflows/main.yml
build.gradle.kts

None
I think this should fix some of the strange `spotlessCheck` failures that we've been seeing on `ion-11-encoding` PRs.

Fix Spotless rachetFrom to only compare to the most recent ancestor on `master`

---

src/main/java/com/amazon/ion/IonEncodingVersion.java
src/main/java/com/amazon/ion/impl/IonRawTextWriter_1_1.kt
src/main/java/com/amazon/ion/impl/_Private_IonTextWriterBuilder.java
src/main/java/com/amazon/ion/impl/_Private_IonTextWriterBuilder_1_0.java
src/main/java/com/amazon/ion/impl/_Private_IonTextWriterBuilder_1_1.java
src/main/java/com/amazon/ion/impl/bin/IonManagedWriter_1_1.kt
src/main/java/com/amazon/ion/system/IonBinaryWriterBuilder_1_1.java
src/main/java/com/amazon/ion/system/IonTextWriterBuilder.java
src/main/java/com/amazon/ion/system/IonTextWriterBuilder_1_1.java
src/main/java/com/amazon/ion/system/IonWriterBuilder_1_1.java
src/main/java/com/amazon/ion/system/_Private_IonBinaryWriterBuilder_1_1.java
src/main/java/com/amazon/ion/util/IonTextUtils.java
src/main/java/com/amazon/ion/util/Printer.java
src/test/java/com/amazon/ion/Ion11Test.kt
src/test/java/com/amazon/ion/impl/IonRawTextWriterTest_1_1.kt
src/test/java/com/amazon/ion/streaming/SeekableReaderTest.java
src/test/java/com/amazon/ion/system/IonBinaryWriterBuilder_1_1_Test.java
src/test/java/com/amazon/ion/system/IonTextWriterBuilderTestBase.java
src/test/java/com/amazon/ion/system/IonTextWriterBuilder_1_0_Test.java
src/test/java/com/amazon/ion/system/IonTextWriterBuilder_1_1_Test.java

Adds an Ion 1.1 text writer builder, accessible via `IonEncodingVersion.ION_1_1.textWriterBuilder()`. The diff looks big but it's mostly just from moving stuff around.

Adds the IonTextWriterBuilder_1_1 interface.

---

src/main/java/com/amazon/ion/impl/bin/IonManagedWriter_1_1.kt

Performance measured by https://github.com/amazon-ion/ion-java-benchmark-cli/tree/ion-1-1 using a 20MB binary Ion log file.
Before this PR:
236 ms / op
After this PR:
189 ms / op
If this can be made more Kotlin-idiomatic I'm open to it. We should also try making `newSymbols` a map if the `newSymbols.indexOf` lookup starts showing up in profiles.

Improves performance by representing the LST using a Map instead of SymbolTable in IonManagedWriter_1_1.

---

src/main/java/com/amazon/ion/impl/bin/FlexInt.kt

Successful inlining of the method after this change is confirmed by before/after profiles. Performance measured by https://github.com/amazon-ion/ion-java-benchmark-cli/tree/ion-1-1 using a 20MB binary Ion log file.
Before this PR:
192 ms / op
After this PR:
182 ms / op (-5%)

Makes FlexInt.writeFlexIntOrUIntInto inlineable for common sizes.

---

src/main/java/com/amazon/ion/impl/IonCursorBinary.java
src/test/java/com/amazon/ion/Ion11Test.kt
src/test/java/com/amazon/ion/impl/IonReaderContinuableTopLevelBinaryTest.java

None
There is a bug that I discovered where Ion 1.1 binary data such as `E0 01 01 EA FD 0F 01 FF 61 D3 09 A1 62` (equivalent to `$ion_1_1 {a:{$4:b}}`) is interpreted incorrectly. The field _text_ from `a` was not properly being reset and was leaking into the next field name, so that even though `$4` was being parsed correctly the reader would see that field _text_ was available and return that instead. I was only able to reproduce this for cases such as mentioned above where there is a field name with inline text and then the first nested field inside that value is a SID field name.
The bug was fixed by clearing `fieldTextMarker` in the `reset()` method. Since this is the second such bug I've found related to things not being cleared …

Fix leaking field name text in IonCursorBinary

---

src/main/java/com/amazon/ion/impl/IonReaderContinuableCore.java
src/main/java/com/amazon/ion/impl/IonReaderContinuableCoreBinary.java
src/main/java/com/amazon/ion/impl/IonReaderNonContinuableSystem.java
src/test/java/com/amazon/ion/BinaryByteArrayIteratorSystemProcessingTest.java
src/test/java/com/amazon/ion/BinaryReaderSystemProcessingTest.java

This requires checking with the "core" reader whether a symbol token was encoded as a SID or with inline text. Note: the system reader is not considered to be performance-critical.

Adds support for Ion 1.1 inline symbols to the system-level binary reader.

---

build.gradle.kts

None
Automated release workflow for `v1.11.8` failed because the spotbugs task was using Java 21. This forces it to use Java 8.

Set Java toolchain for spotbugs task

---

src/main/java/com/amazon/ion/impl/IonCursorBinary.java
src/main/java/com/amazon/ion/impl/IonReaderContinuableApplicationBinary.java
src/main/java/com/amazon/ion/impl/MarkerList.java
src/test/java/com/amazon/ion/Ion_1_1_RoundTripTest.kt
src/test/java/com/amazon/ion/impl/IonReaderContinuableTopLevelBinaryTest.java

Fixes #866 
* Un-disables inline symbols / delimited containers tests in `Ion_1_1_RoundTripTest`. Fixes bugs uncovered due to the increased coverage.
* Adds support for reading symbol tables with inline system symbols (#866)
* Adds coverage of edge cases addressed in this PR to `IonReaderContinuableTopLevelBinaryTest`.
* Adds reader configuration dimensions to `Ion_1_1_RoundTripTest`.

Fixes various bugs in Ion 1.1 binary parsing

---

src/main/java/com/amazon/ion/impl/_Private_IonWriter.java
src/main/java/com/amazon/ion/impl/bin/IonManagedWriter_1_1.kt
src/test/java/com/amazon/ion/impl/bin/IonManagedWriter_1_1_Test.kt

For now, this will only be possible via `_Private_` methods in `_Private_IonWriter`. We can use these in the benchmark CLI to enable correct system-level transcoding from Ion 1.0 to Ion 1.1, once the Ion 1.1 system symbol table is finalized. Note: system symbols do not get transformed, as they always have text, even when provided by a system reader. This should allow this to just work even if Ion 1.1 shared symbols occupy a different address space.

Adds the ability to transform Ion 1.0 symbol IDs to Ion 1.1 equivalents when performing a system-level transcoding.

---

.github/workflows/ion-test-driver.yml

*Issue #, if available:* #795
It appears that the issue causing the ion-test-driver failure is related to an issue found in pip 22.0. This PR adds the setup-python action to force a pip upgrade (and ensure python version).
A run of the workflow can be seen [here](https://github.com/nirosys/ion-java/actions/runs/9408550614/job/25916753044?pr=3).
In addition to the setup-python change, I also had to roll-back the revision of ion-test-driver that was being used to before the 1.0 and 1.1 split was made. The workflow was pulling master, which has been using the directory split for a while, but it appears the iontests used by this repo is from before versioned directories were added. 
---
By submitting this pull request, I confirm that my contribution is made under the …

Address ion-test-driver failure by upgrading pip with setup-python action.

---

build.gradle.kts
src/main/java/com/amazon/ion/impl/_Private_IonTextWriterBuilder_1_1.java
src/test/java/com/amazon/ion/FakeSymbolToken.java
src/test/java/com/amazon/ion/conformance/Config.kt
src/test/java/com/amazon/ion/conformance/ConformanceTestBuilder.kt
src/test/java/com/amazon/ion/conformance/ConformanceTestDslInterpreterTest.kt
src/test/java/com/amazon/ion/conformance/ConformanceTestInvalidSyntaxException.kt
src/test/java/com/amazon/ion/conformance/ConformanceTestRunner.kt
src/test/java/com/amazon/ion/conformance/expectations.kt
src/test/java/com/amazon/ion/conformance/fragments.kt
src/test/java/com/amazon/ion/conformance/structure.kt
src/test/java/com/amazon/ion/conformance/util.kt
src/test/java/com/amazon/ion/util/formatting.kt

#748
* Adds an interpreter for the conformance DSL
* Makes `FakeSymbolToken` implement `_Private_SymbolToken` so that we can be sure that `FakeSymbolToken` will work everywhere we need it to.
* Fixes a bug in `_Private_IonTextWriterBuilder_1_1`

Adds runner for Ion conformance tests

---

src/main/java/com/amazon/ion/impl/IonCursorBinary.java
src/main/java/com/amazon/ion/impl/IonTypeID.java
src/test/java/com/amazon/ion/TestUtils.java
src/test/java/com/amazon/ion/impl/IonCursorBinaryTest.java
src/test/java/com/amazon/ion/impl/IonReaderContinuableTopLevelBinaryTest.java

Allows IonCursorBinary to parse macro addresses from all macro invocation opcodes defined in the [proposed Ion 1.1 spec](https://github.com/amazon-ion/ion-docs/blob/ion-11-specification/src/binary-encoding.adoc). Depends on the system symbol / macro proposal here: https://github.com/amazon-ion/ion-docs/pull/326.
Future PRs will add the ability for higher-level readers to resolve these macro addresses to macro definitions and evaluate the invocations.

Adds binary read support for macro invocation headers.

---

src/main/java/com/amazon/ion/impl/IonCursorBinary.java
src/main/java/com/amazon/ion/impl/IonReaderContinuableCoreBinary.java
src/test/java/com/amazon/ion/impl/IonCursorBinaryTest.java
src/test/java/com/amazon/ion/impl/IonCursorTestUtilities.java
src/test/java/com/amazon/ion/impl/IonReaderContinuableCoreBinaryTest.java
src/test/java/com/amazon/ion/impl/IonReaderContinuableTopLevelBinaryTest.java

See the [tagless encodings](https://github.com/amazon-ion/ion-docs/blob/ion-11-specification/src/binary-encoding.adoc#tagless_encodings) section in the binary Ion 1.1 spec.
This PR implements support for tagless types at the raw / core level. It is assumed that a higher-level reader (i.e., one capable of interpreting macro invocations) knows which tagless type to expect next and positions the core reader accordingly. Macro evaluation will be added in a future PR.

Adds support for reading binary tagless types.

---

src/main/java/com/amazon/ion/impl/IonCursorBinary.java
src/main/java/com/amazon/ion/impl/Marker.java
src/test/java/com/amazon/ion/impl/IonCursorBinaryTest.java

Before this PR, FlexSyms could not be read incrementally (i.e., without all bytes available up front) because the relevant methods did not distinguish between the signed integer value `-1` and the `-1` commonly used to convey that the end of the input has been reached. This PR fixes that defect by using `Marker` to store the FlexSym's value, and a boolean return to convey whether the end of input was reached.

Fixes incremental reading of FlexSyms.

---

src/main/java/com/amazon/ion/impl/bin/FixedInt.kt
src/main/java/com/amazon/ion/impl/bin/IonEncoder_1_1.java
src/main/java/com/amazon/ion/impl/bin/PresenceBitmap.kt
src/main/java/com/amazon/ion/impl/bin/WriteBuffer.java
src/main/java/com/amazon/ion/impl/macro/Macro.kt
src/test/java/com/amazon/ion/TestUtils.java
src/test/java/com/amazon/ion/impl/bin/PresenceBitmapTest.kt

This relates to #741 and #742
Adds a class to help manage presence bitmaps for binary E-Expressions.
In doing so, I also made these incidental changes:
* Extract some FixedInt functionality to a `FixedInt` class (actually a singleton with static methods).
* Add a shorter `toString()` representation for `Macro.Parameter` that looks like the serialized text representation of a parameter. (Not actually used by the code in this PR, but it was useful while I was debugging things.)
* Added a `uint8` type to the `ParameterEncoding` enum so that I could test with a tagless type.
* Added a `writeFixedIntOrUIntAt()` method to `WriteBuffer`.
_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …

Adds PresenceBitmap

---

build.gradle.kts
src/main/java/com/amazon/ion/impl/IonReaderContinuableCoreBinary.java
src/test/java/com/amazon/ion/IonReaderValueCoercionTest.java

While the documentation for `IonReader#doubleValue` and `decimalValue` indicates that those methods will throw an exception when then the current value's `IonType` is not `FLOAT` or `DECIMAL` respectively, versions of `ion-java` up to and including v1.10.5 would quietly coerce numeric values to the requested type. The new binary reader implementation hewed to the documentation's stated contract, but this ended up being a breaking change for a small number of users who depended on the undocumented behavior.
This PR restores the previously supported numeric type coercions for `doubleValue`, `decimalValue`, and `bigDecimalValue` and adds unit tests to prevent future regressions. It also replaces uses of the deprecated `$buildDir` accessor in `build.gradle.kts` with the now-recommended …

Restores float <-> decimal conversions in the binary reader

---

src/main/java/com/amazon/ion/impl/bin/PresenceBitmap.kt
src/main/java/com/amazon/ion/impl/macro/Macro.kt
src/main/java/com/amazon/ion/impl/macro/MacroCompiler.kt
src/test/java/com/amazon/ion/impl/bin/PresenceBitmapTest.kt
src/test/java/com/amazon/ion/impl/macro/MacroCompilerTest.kt

None
Changes the `ParameterCardinality` enum so that the variants match the terms used in the spec.

Rename cardinality enum to match spec

---

src/main/java/com/amazon/ion/impl/IonCursorBinary.java
src/test/java/com/amazon/ion/impl/IonCursorBinaryTest.java

This will be used basically as follows:
1. The application-level reader will advance the IonCursorBinary to the next token. The cursor conveys that it is positioned on a macro invocation.
2. The application-level reader retrieves the macro address from the cursor and retrieves the signature. If the signature requires an AEB, It initializes a `PresenceBitmap` (see #895) from the signature.
3. If it has a `PresenceBitmap`, the reader calls the cursor's `fillArgumentEncodingBitmap` (added in this PR), providing the result of `PresenceBitmap.byteSize()`. This ensures the AEB byte(s) are buffered in a `byte[]` and allows the reader to retrieve the start and end indices.
4. The reader calls `PresenceBitmap.readFrom()`, providing the buffer and AEB start index …

Adds support for lexing the argument encoding bitmap (presence bits).

---

src/main/java/com/amazon/ion/impl/IonCursorBinary.java
src/test/java/com/amazon/ion/impl/IonCursorBinaryTest.java

Ensures that errors are raised cleanly when any component of an Ion 1.0 annotation header results in overflow of a Java long. Identified by oss-fuzz.

Fixes handling of annotation wrapper length overflows.

---

src/test/java/com/amazon/ion/conformance/ConformanceTestDslInterpreterTest.kt
src/test/java/com/amazon/ion/conformance/fragments.kt
src/test/java/com/amazon/ion/conformance/structure.kt

Implements https://github.com/amazon-ion/ion-tests/pull/121
Now name strings can be alternated with fragments in an `each` clause.

Updates 'each' clauses to allow alternating name-strings and fragments

---

src/main/java/com/amazon/ion/impl/IonCursorBinary.java
src/test/java/com/amazon/ion/impl/IonCursorBinaryTest.java

Implements the low-level parsing of binary argument groups according to the following spec:
> **Argument group encoding for tagged encodings**
> FlexUInt    0: Delimited
>          1..N: Size in bytes = N
> Empty tagged argument groups must use bitmap 00  (or delimited start/end, but that's wasteful.)
> 
> **Argument group encoding for tagless encodings**
> FlexUInt    0: Final 'batch'
>          1..N: Batch that is N bytes long
> Truly empty tagless argument groups should use bitmap 00, but it's legal to use the final batch zero too.
The public methods added to IonCursorBinary are expected to be called by higher-level readers with awareness of the macro signatures applicable at the current stream position. The basic sequence of method calls required to parse …

Adds support for parsing binary argument groups.

---

src/main/java/com/amazon/ion/impl/IonCursorBinary.java
src/test/java/com/amazon/ion/impl/IonCursorBinaryTest.java

According to the Ion spec, annotation wrappers must wrap a value. This change allows for cleaner failure (via `IonException`) when this is violated.

Adds checks for annotation wrappers with length 0.

---

src/main/java/com/amazon/ion/impl/IonReaderContinuableCoreBinary.java
src/test/java/com/amazon/ion/impl/IonReaderContinuableCoreBinaryTest.java

According to the Ion spec, timestamp values cannot have length 0. This change allows for cleaner failure (via `IonException`) when this is violated.

Adds checks for timestamp values with length 0.

---

src/main/java/com/amazon/ion/impl/macro/Environment.kt
src/main/java/com/amazon/ion/impl/macro/Macro.kt
src/main/java/com/amazon/ion/impl/macro/MacroEvaluator.kt
src/test/java/com/amazon/ion/impl/macro/MacroEvaluatorTest.kt

#730, #731 
An initial macro evaluator implementation.
There are a few things that should be improved, but I haven't done them yet.
* I want to move the `Expander` interface and implementations out of `MacroEvaluator` before adding more system macros so that `MacroEvaluator.kt` doesn't get ridiculously large.
* Testing only covers happy cases right now.

Adds macro evaluator implementation

---

build.gradle.kts
settings.gradle.kts
src/jmh/java/com/amazon/ion/IonValueGetTypeBenchmark.java
src/main/java/com/amazon/ion/impl/lite/IonBlobLite.java
src/main/java/com/amazon/ion/impl/lite/IonBoolLite.java
src/main/java/com/amazon/ion/impl/lite/IonClobLite.java
src/main/java/com/amazon/ion/impl/lite/IonDatagramLite.java
src/main/java/com/amazon/ion/impl/lite/IonDecimalLite.java
src/main/java/com/amazon/ion/impl/lite/IonFloatLite.java
src/main/java/com/amazon/ion/impl/lite/IonIntLite.java
src/main/java/com/amazon/ion/impl/lite/IonListLite.java
src/main/java/com/amazon/ion/impl/lite/IonNullLite.java
src/main/java/com/amazon/ion/impl/lite/IonSexpLite.java
src/main/java/com/amazon/ion/impl/lite/IonStringLite.java
src/main/java/com/amazon/ion/impl/lite/IonStructLite.java
src/main/java/com/amazon/ion/impl/lite/IonSymbolLite.java
src/main/java/com/amazon/ion/impl/lite/IonTimestampLite.java
src/main/java/com/amazon/ion/impl/lite/IonValueLite.java

Also adds a 'jmh' target that allows us to add microbenchmarks for targeted performance testing. These benchmarks are run using `./gradlew jmh`. Example output:
```
Benchmark                                  Mode  Cnt    Score   Error  Units
IonValueGetTypeBenchmark.getTypeContainer  avgt    5  469.625 ± 5.799  ns/op
IonValueGetTypeBenchmark.ionValueGetType   avgt    5    7.863 ± 0.139  ns/op
```
This is optional and can be removed from this PR if reviewers have objections. I think it's nice because it reduces the effort required to add new JMH benchmarks that are more targeted than the `ion-java-benchmark-cli`. Note that we followed this same pattern in [ion-java-path-extraction](https://github.com/amazon-ion/ion-java-path-extraction/). New benchmarks need not …

Optimizes IonValue.getType() to avoid vtable/itable lookups when invoked on IonStruct values.

---

src/main/java/com/amazon/ion/impl/IonRawTextWriter_1_1.kt
src/main/java/com/amazon/ion/impl/IonRawWriter_1_1.kt
src/main/java/com/amazon/ion/impl/_Private_IonTextWriterBuilder_1_1.java
src/main/java/com/amazon/ion/impl/bin/IonManagedWriter_1_1.kt
src/main/java/com/amazon/ion/impl/bin/IonRawBinaryWriter_1_1.kt
src/main/java/com/amazon/ion/impl/bin/LengthPrefixStrategy.kt
src/main/java/com/amazon/ion/impl/bin/ManagedWriterOptions_1_1.kt
src/main/java/com/amazon/ion/system/IonBinaryWriterBuilder_1_1.java
src/main/java/com/amazon/ion/system/_Private_IonBinaryWriterBuilder_1_1.java
src/test/java/com/amazon/ion/Ion_1_1_RoundTripTest.kt
src/test/java/com/amazon/ion/impl/IonRawTextWriterTest_1_1.kt
src/test/java/com/amazon/ion/impl/bin/IonRawBinaryWriterTest_1_1.kt

None
I'm renaming this because I'm going to be using the length prefix strategy for things that could have a length prefix, but are not a container (i.e. expression groups, macro invocations). 
I'm doing this as a separate PR to avoid having a single, enormous PR.

Renames DelimitedContainerStrategy to LengthPrefixStrategy

---

src/main/java/com/amazon/ion/SystemSymbols.java
src/main/java/com/amazon/ion/impl/IonReaderContinuableApplication.java
src/main/java/com/amazon/ion/impl/IonReaderContinuableApplicationBinary.java
src/main/java/com/amazon/ion/impl/IonReaderContinuableCore.java
src/main/java/com/amazon/ion/impl/IonReaderContinuableCoreBinary.java
src/main/java/com/amazon/ion/impl/bin/IonRawBinaryWriter_1_1.kt
src/main/java/com/amazon/ion/impl/macro/MacroCompiler.kt
src/main/java/com/amazon/ion/impl/macro/MacroEvaluator.kt
src/main/java/com/amazon/ion/impl/macro/MacroEvaluatorAsIonReader.kt
src/main/java/com/amazon/ion/impl/macro/MacroRef.kt
src/test/java/com/amazon/ion/impl/EncodingDirectiveCompilationTest.java
src/test/java/com/amazon/ion/impl/macro/MacroCompilerTest.kt

The logic for reading encoding directives is very similar to reading Ion 1.0 symbol tables. However, this PR proposes to put the encoding directive code in the "core"-level reader instead of the "application"-level reader because templates may expand to system values, which need to be surfaced to the "application"-level reader. This required moving some existing functionality from IonReaderContinuableApplicationBinary to IonReaderContinuableCoreBinary.
As part of this PR I modified MacroCompiler to work specifically with IonReaderContinuableCore instead of IonReader. I left a TODO to figure out how to reconcile this with the text reader.
I put a few basic tests in the new EncodingDirectiveCompilationTest, though we'll need to add more to improve coverage. I do …

Adds the ability to compile Ion encoding directives from binary Ion 1.1 streams.

---

src/main/java/com/amazon/ion/impl/IonCursorBinary.java
src/main/java/com/amazon/ion/impl/IonReaderContinuableApplicationBinary.java
src/main/java/com/amazon/ion/impl/IonReaderContinuableCoreBinary.java
src/main/java/com/amazon/ion/impl/bin/PresenceBitmap.kt
src/main/java/com/amazon/ion/impl/macro/MacroEvaluator.kt
src/main/java/com/amazon/ion/impl/macro/MacroEvaluatorAsIonReader.kt
src/test/java/com/amazon/ion/impl/EncodingDirectiveCompilationTest.java
src/test/java/com/amazon/ion/impl/bin/PresenceBitmapTest.kt
src/test/java/com/amazon/ion/impl/macro/MacroEvaluatorTest.kt

This PR connects the binary reader to the MacroEvaluator, and multiplexes between reading from the stream and from the MacroEvaluatorAsIonReader depending on whether a macro is currently being evaluated. The MacroEvaluator currently expects all parameters to be fully materialized before expansion; on-demand deserialization of parameters during expansion has been discussed as an optimization for the future.
Some basic tests are added to demonstrate the functionality, though the bulk of the coverage is expected to come from conformance test vectors concerned with macro expansion. No performance testing has been done yet. The plan is to iterate on performance once the functionality is well-covered by conformance tests.
I've intentionally left some TODOs in the code …

Adds support for evaluating user-defined macros from binary streams.

---

src/main/java/com/amazon/ion/IonWriter.java
src/main/java/com/amazon/ion/MacroAwareIonWriter.kt
src/main/java/com/amazon/ion/SystemSymbols.java
src/main/java/com/amazon/ion/WriteAsIon.kt
src/main/java/com/amazon/ion/impl/IonRawTextWriter_1_1.kt
src/main/java/com/amazon/ion/impl/IonRawWriter_1_1.kt
src/main/java/com/amazon/ion/impl/IonReaderContinuableCoreBinary.java
src/main/java/com/amazon/ion/impl/_Private_IonTextWriterBuilder_1_1.java
src/main/java/com/amazon/ion/impl/bin/IonManagedWriter_1_1.kt
src/main/java/com/amazon/ion/impl/bin/IonRawBinaryWriter_1_1.kt
src/main/java/com/amazon/ion/impl/bin/ManagedWriterOptions_1_1.kt
src/main/java/com/amazon/ion/impl/bin/SymbolInliningStrategy.kt
src/main/java/com/amazon/ion/impl/macro/Expression.kt
src/main/java/com/amazon/ion/impl/macro/Macro.kt
src/main/java/com/amazon/ion/impl/macro/MacroCompiler.kt
src/main/java/com/amazon/ion/impl/macro/MacroRef.kt
src/main/java/com/amazon/ion/system/IonBinaryWriterBuilder_1_1.java
src/main/java/com/amazon/ion/system/_Private_IonBinaryWriterBuilder_1_1.java
src/test/java/com/amazon/ion/Ion_1_1_RoundTripTest.kt
src/test/java/com/amazon/ion/impl/IonRawTextWriterTest_1_1.kt
src/test/java/com/amazon/ion/impl/bin/IonManagedWriter_1_1_Test.kt
src/test/java/com/amazon/ion/impl/bin/IonRawBinaryWriterTest_1_1.kt
src/test/java/com/amazon/ion/impl/macro/ExpressionBuilderDsl.kt
src/test/java/com/amazon/ion/impl/macro/MacroEvaluatorTest.kt

#733, #737, #742
I've split it into multiple commits to make it easier to review.
* [Tyler's patch for IonReaderContinuableCoreBinary](https://github.com/amazon-ion/ion-java/commit/2734c880eed22950b139f0784fd9c5b8922be343) is a temporary thing that will end up being a merge conflict and needing to be removed once #933 is merged.
* [Renames finish() to flush() in raw writer and fixes flush() implement…](https://github.com/amazon-ion/ion-java/commit/3e93ea33b4658e0934e243ad8452254a5d9e6e95). This is something that was bothering me, and there was a bug in the raw text writer's implementation of `finish()` because it didn't actually flush the output.
* [Adds MacroAwareIonWriter, WriteAsIon …

Adds support for writing macros in IonManagedWriter_1_1

---

src/main/java/com/amazon/ion/impl/IonRawTextWriter_1_1.kt
src/main/java/com/amazon/ion/impl/PrivateIonRawWriter_1_1.kt
src/main/java/com/amazon/ion/impl/bin/IonManagedWriter_1_1.kt
src/main/java/com/amazon/ion/impl/bin/IonRawBinaryWriter_1_1.kt
src/test/java/com/amazon/ion/impl/bin/IonManagedWriter_1_1_Test.kt

None.
This is a minor readability improvement for text-encoded encoding directives. It also sets up an internal-only interface for the raw writer that we can also use for some minor optimizations.

Adds custom formatting for encoding directives when writing text

---

src/main/java/com/amazon/ion/MacroAwareIonWriter.kt
src/main/java/com/amazon/ion/impl/IonReaderContinuableCoreBinary.java
src/main/java/com/amazon/ion/impl/_Private_IonTextWriterBuilder_1_1.java
src/main/java/com/amazon/ion/impl/bin/IonManagedWriter_1_1.kt
src/main/java/com/amazon/ion/impl/bin/ManagedWriterOptions_1_1.kt
src/main/java/com/amazon/ion/impl/macro/Expression.kt
src/main/java/com/amazon/ion/impl/macro/Macro.kt
src/main/java/com/amazon/ion/impl/macro/MacroCompiler.kt
src/main/java/com/amazon/ion/impl/macro/MacroEvaluator.kt
src/main/java/com/amazon/ion/system/_Private_IonBinaryWriterBuilder_1_1.java
src/test/java/com/amazon/ion/impl/EncodingDirectiveCompilationTest.java
src/test/java/com/amazon/ion/impl/bin/IonManagedWriter_1_1_Test.kt
src/test/java/com/amazon/ion/impl/macro/ExpressionBuilderDsl.kt
src/test/java/com/amazon/ion/impl/macro/MacroCompilerTest.kt
src/test/java/com/amazon/ion/impl/macro/MacroEvaluatorTest.kt

Follow up to https://github.com/amazon-ion/ion-java/pull/934#discussion_r1747577719
Removes `MacroRef` from the `Expression` model and the macro writer APIs so that we don't have to deal with potentially stale references, and so that we can automatically add macro dependencies to the macro table.

Remove MacroRef from user-facing APIs

---

src/main/java/com/amazon/ion/impl/IonCursorBinary.java
src/main/java/com/amazon/ion/impl/IonTypeID.java
src/main/java/com/amazon/ion/impl/SystemSymbols_1_1.kt
src/main/java/com/amazon/ion/impl/bin/IonRawBinaryWriter_1_1.kt
src/main/java/com/amazon/ion/impl/bin/OpCodes.java
src/test/java/com/amazon/ion/impl/IonCursorBinaryTest.java
src/test/java/com/amazon/ion/impl/bin/IonRawBinaryWriterTest_1_1.kt

None.
This adds an implementation of Ion 1.1 Symbols. Rather than try to kludge them into the existing `SymbolToken` interface, my plan is to treat them like a special case of symbols with inline text.
Also updates OpCode `0xEE` to mean "system symbol" so that we're not sharing `EF` between system symbols and system macros because that was unnecessarily complicated to implement, and we didn't know if it was going to be a macro or a symbol until we read the second byte.

Adds Ion 1.1 system symbols

---

src/main/java/com/amazon/ion/impl/BufferedOutputStreamFastAppendable.kt
src/test/java/com/amazon/ion/Ion_1_1_RoundTripTest.kt

Before this change, the Ion 1.1 managed text writer would close its OutputStream twice: once when closing its system-level raw writer and once when closing its user-level raw writer. This was not caught by tests because they used ByteArrayOutputStream, whose close() implementation does nothing. Other OutputStreams like FileOutputStream do not tolerate being written to (in this case, by the user-level raw writer) after close.

Ensures the Ion 1.1 managed writer does not close its OutputStream twice.

---

src/main/java/com/amazon/ion/impl/IonRawTextWriter_1_1.kt
src/main/java/com/amazon/ion/impl/IonRawWriter_1_1.kt
src/main/java/com/amazon/ion/impl/bin/IonManagedWriter_1_1.kt
src/main/java/com/amazon/ion/impl/bin/IonRawBinaryWriter_1_1.kt
src/main/java/com/amazon/ion/impl/bin/Ion_1_1_Constants.java
src/main/java/com/amazon/ion/impl/bin/WriteBuffer.java
src/test/java/com/amazon/ion/Ion_1_1_RoundTripTest.kt
src/test/java/com/amazon/ion/impl/bin/IonManagedWriter_1_1_Test.kt
src/test/java/com/amazon/ion/impl/bin/IonRawBinaryWriterTest_1_1.kt
src/test/java/com/amazon/ion/impl/bin/WriteBufferTest.java

None
* Updates the FlexSym related methods in `WriteBuffer` to be able to write system symbols.
* Adds APIs that accept `SystemSymbol` to `IonRawWriter_1_1`.
* Adds support for writing Ion 1.1 system symbols for both the text and binary writers. 
* Updates `IonManagedWriter_1_1` to use system symbols for writing encoding directives and to move all of the system symbols out of user-symbol space.
* (Temporarily) disabled tests that use the Ion 1.1 reader and writer for a round trip of any sort because the reader does not have full support for system symbols yet.

Write support for Ion 1.1 system symbols

---

src/main/java/com/amazon/ion/impl/IonReaderContinuableCoreBinary.java
src/main/java/com/amazon/ion/impl/macro/MacroCompiler.kt
src/main/java/com/amazon/ion/impl/macro/MacroCompilerContinuable.kt
src/main/java/com/amazon/ion/impl/macro/MacroCompilerIonReader.kt
src/test/java/com/amazon/ion/impl/macro/MacroCompilerTest.kt

We will use `MacroCompilerContinuable` for binary and `MacroCompilerIonReader` for text. If there's a better way to achieve this in Kotlin, I'm open to it.

Enables MacroCompiler to operate over an IonReader.

---

src/main/java/com/amazon/ion/SystemSymbols.java
src/main/java/com/amazon/ion/impl/IonCursorBinary.java
src/main/java/com/amazon/ion/impl/IonReaderContinuableApplicationBinary.java
src/main/java/com/amazon/ion/impl/IonReaderContinuableCoreBinary.java
src/main/java/com/amazon/ion/impl/IonTypeID.java
src/main/java/com/amazon/ion/impl/LocalSymbolTableImports.java
src/main/java/com/amazon/ion/impl/SystemSymbols_1_1.kt
src/main/java/com/amazon/ion/impl/_Private_Utils.java
src/main/java/com/amazon/ion/impl/bin/IonManagedWriter_1_1.kt
src/main/java/com/amazon/ion/impl/bin/Ion_1_1_Constants.java
src/test/java/com/amazon/ion/Ion_1_1_RoundTripTest.kt
src/test/java/com/amazon/ion/impl/EncodingDirectiveCompilationTest.java
src/test/java/com/amazon/ion/impl/IonCursorBinaryTest.java
src/test/java/com/amazon/ion/impl/IonCursorTestUtilities.java
src/test/java/com/amazon/ion/impl/IonReaderContinuableApplicationBinaryTest.java
src/test/java/com/amazon/ion/impl/IonReaderContinuableCoreBinaryTest.java
src/test/java/com/amazon/ion/impl/IonReaderContinuableTopLevelBinaryTest.java
src/test/java/com/amazon/ion/impl/bin/IonManagedWriter_1_1_Test.kt

None.
* Adds support for reading system symbols in FlexSyms and using the `EE` op code.
* Changes a lot of tests from using `A0` for "unknown symbol" to `60` and `90` for empty symbol to `75`.
* Removes the `@Disabled` annotation from disabled tests in `IonManagedWriter_1_1_Test`
* Adds the byte value to the string representation of `IonTypeID`. (I.e. was `SYMBOL(1)`, now `0xEE(SYMBOL,1)`) That was useful to me while debugging things.
* Limitations:
* I disabled the entirety of `EncodingDirectiveCompilationTest`. For some reason, I couldn't seem to understand how these tests were supposed to work in the first place, so I was unable to update them to get them to work with my changes. Because almost all of the other tests are working, I …

Adds read support for Ion 1.1 system symbols

---

build.gradle.kts

This is a DirectoryProperty, which in a few places was used or carried forward as a String without being appropriately converted first.
That resulted in the use and creation of a project-root directory called `gradle.api.file.Directory, fixed(class org.gradle.api.internal.file.DefaultFilePropertyFactory$FixedDirectory, ` which was then used by the `generateJarInfo` and `generateLicenseReport` tasks.
This fixes it.
**Before**
```plain
❯ ./gradlew :build
❯ find property
```
```plain
property(org.gradle.api.file.Directory, fixed(class org.gradle.api.internal.file.DefaultFilePropertyFactory$FixedDirectory,
property(org.gradle.api.file.Directory, fixed(class org.gradle.api.internal.file.DefaultFilePropertyFactory$FixedDirectory, /Volumes …
```

Fix use of `layout.buildDirectory`

---

src/main/java/com/amazon/ion/impl/IonReaderTextRawX.java
src/main/java/com/amazon/ion/impl/IonReaderTextUserX.java
src/test/java/com/amazon/ion/impl/IonRawTextReaderTest_1_1.java

See the added tests for examples. There's more to do to support Ion 1.1 text syntax, but this PR allows the text reader to recognize the proposed syntax for e-expressions and expression groups (as I understand it -- see https://github.com/amazon-ion/ion-docs/issues/344#issuecomment-2383717456), both inside and outside of TDL.

Adds support for reading Ion 1.1 text syntax for e-expressions and expression groups.

---

src/main/java/com/amazon/ion/impl/LocalSymbolTableImports.java
src/test/java/com/amazon/ion/impl/LocalSymbolTableImportsTest.kt

*Issue #, if available:* #952
*Description of changes:* Ion 1.1 readers use the `EMPTY` local imports instead of one which contains the system symbol table at position 0. That causes a failure with `NegativeArraySizeException` when we try to get the imported tables, as occurs when transcribing values from an `IonReader` to an IonWriter in `IonWriter.writeValues(IonReader)`.
This fixes that issue by causing `LocalSymbolTableImports.EMPTY.getImportedTables()` to yield an empty array.

Account for missing system symbol table (#952)

---

src/main/java/com/amazon/ion/impl/IonRawTextWriter_1_1.kt
src/main/java/com/amazon/ion/impl/PrivateIonRawWriter_1_1.kt
src/main/java/com/amazon/ion/impl/bin/IonManagedWriter_1_1.kt
src/main/java/com/amazon/ion/impl/bin/IonRawBinaryWriter_1_1.kt
src/main/java/com/amazon/ion/impl/bin/Ion_1_1_Constants.java
src/main/java/com/amazon/ion/impl/macro/MacroCompiler.kt
src/test/java/com/amazon/ion/impl/EncodingDirectiveCompilationTest.java
src/test/java/com/amazon/ion/impl/bin/IonManagedWriter_1_1_Test.kt
src/test/java/com/amazon/ion/impl/macro/MacroCompilerTest.kt

https://github.com/amazon-ion/ion-docs/issues/343
https://github.com/amazon-ion/ion-docs/issues/344
This updates `ion-java` to use the TDL syntax proposed in the above issues. (But this PR does not include updating the E-Expression syntax for expression groups.)
Overall, I think the proposed syntax results in simpler code for writing macro definitions in the managed writer and simpler code for compiling the macro templates. So it seems like the proposed changes are positive for users and implementors.

Updates TDL syntax for macro invocations, expr groups, and variable expansions

---

src/main/java/com/amazon/ion/impl/EncodingDirectiveReader.kt
src/main/java/com/amazon/ion/impl/IonRawTextWriter_1_1.kt
src/main/java/com/amazon/ion/impl/IonReaderContinuableCoreBinary.java
src/main/java/com/amazon/ion/impl/IonReaderTextSystemX.java
src/main/java/com/amazon/ion/impl/IonReaderTextUserX.java
src/test/java/com/amazon/ion/impl/EncodingDirectiveCompilationTest.java

Macro evaluation in Ion text will come in a future PR. At that point, all tests in `EncodingDirectiveCompilationTest` will be parameterized to exercise both binary and text.

Adds support for parsing Ion 1.1 encoding directives in the text reader.

---

src/main/java/com/amazon/ion/impl/EncodingDirectiveReader.kt
src/main/java/com/amazon/ion/impl/IonCursorBinary.java
src/main/java/com/amazon/ion/impl/IonReaderTextSystemX.java
src/main/java/com/amazon/ion/impl/LocalSymbolTableImports.java
src/test/java/com/amazon/ion/impl/EncodingDirectiveCompilationTest.java

RC2 focused on byte array inputs. This PR adds testing for InputStream inputs (which are handled slightly differently in some cases by the binary reader), and includes a fix to IonCursorBinary to make the tests pass.
Before this fix, some of the tests would fail because the cursor's checkpoint was not advanced after reading a macro invocation header, causing the header to be read repetitively.
This PR also includes some minor cleanups that somehow didn't make it into the final revision of my previous PR.

Ensures macros can be evaluated from both byte array and InputStream sources.

---

src/main/java/com/amazon/ion/impl/macro/Macro.kt
src/main/java/com/amazon/ion/impl/macro/MacroEvaluator.kt
src/test/java/com/amazon/ion/impl/macro/MacroEvaluatorTest.kt

None
Adds support for `if_some`, `if_none`, `if_single`, and `if_multi` to the `MacroEvaluator`.

Adds implementations of if_* special forms

---

src/main/java/com/amazon/ion/impl/macro/Macro.kt
src/main/java/com/amazon/ion/impl/macro/ParameterFactory.kt
src/main/java/com/amazon/ion/impl/macro/SystemMacro.kt
src/main/java/com/amazon/ion/impl/macro/TemplateMacro.kt
src/test/java/com/amazon/ion/impl/EncodingDirectiveCompilationTest.java
src/test/java/com/amazon/ion/impl/bin/IonManagedWriter_1_1_Test.kt

None
This splits up the `Macro.kt` file, which was getting pretty large, and adds system addresses to the system macros.

Add system addresses to system macros

---

src/main/java/com/amazon/ion/impl/IonReaderContinuableCoreBinary.java
src/test/java/com/amazon/ion/impl/IonReaderContinuableTopLevelBinaryTest.java

#741 
Adds support for reading the System EExpression op-code.
In the process, I discovered two issues that seem like they are not caused by my changes. I tried to create an equivalent test using non-system macros to determine whether these issues already existed, but I ran into some trouble getting it set up. If you agree that it seems like I haven't introduced a problem in this PR, then I'll go ahead and create GH issues to follow up on these bugs.
* There's a bug somewhere that causes the reader to get into a bad state if a top-level e-expression that produces no values is followed by another e-expression.
* There's a (pre-existing?) problem that causes an exception to be thrown from `slowFillValue()` when attempting to read …

Add support for reading system e-expressions

---

src/main/java/com/amazon/ion/impl/IonRawTextWriter_1_1.kt
src/main/java/com/amazon/ion/impl/bin/IonManagedWriter_1_1.kt

*Description of changes:* `IonManagedWriter_1_1` does not implement `IonWriter.getSymbolTable`, which means that there is no way for a user to drive creation of a symbol apart from use. Based on offline discussion exposing this function is preferable at present to implementing `getSymbolTable` in this writer. 
Any better ideas are welcome.

Make IonMangedWriter_1_1.intern public

---

src/main/java/com/amazon/ion/impl/IonRawTextWriter_1_1.kt
src/main/java/com/amazon/ion/impl/IonRawWriter_1_1.kt
src/main/java/com/amazon/ion/impl/bin/IonManagedWriter_1_1.kt
src/main/java/com/amazon/ion/impl/bin/IonRawBinaryWriter_1_1.kt
src/main/java/com/amazon/ion/impl/macro/SystemMacro.kt
src/test/java/com/amazon/ion/impl/IonRawTextWriterTest_1_1.kt
src/test/java/com/amazon/ion/impl/bin/IonManagedWriter_1_1_Test.kt
src/test/java/com/amazon/ion/impl/bin/IonRawBinaryWriterTest_1_1.kt

Part of #742
* Adds `stepInEExp(SystemMacro)` to the `IonRawWriter_1_1` interface.
* Implements for both text and binary
* Adds logic in `IonManagedWriter_1_1` to write using local macro names/addresses if possible, but fallback to using the system e-expression syntax if the system macro has already been shadowed in the system table.

Add support for writing System E-Expression invocations

---

src/main/java/com/amazon/ion/impl/IonReaderContinuableCoreBinary.java
src/test/java/com/amazon/ion/impl/IonReaderContinuableTopLevelBinaryTest.java

Fixes #962
The diff is smaller than it looks. The scope of the `while` loop is extended over everything in `IonReaderContinuableCoreBinary.nextValue()`. The reader goes around the loop again any time the end of the active e-expression evaluation is reached. Doing so allows it to properly consume the next value from the stream instead of returning while still "between" values.

Fixes a bug that caused the binary reader to stop consuming from the stream after evaluating an e-expression that produced no values.

---

src/main/java/com/amazon/ion/impl/EncodingDirectiveReader.kt
src/main/java/com/amazon/ion/impl/bin/IonRawBinaryWriter_1_1.kt
src/test/java/com/amazon/ion/impl/bin/IonRawBinaryWriterTest_1_1.kt

*Description of changes:* 
Before this patch, if you used an EExpression to exceed the parameter limit for an EExpression (e.g. by adding a superfluous `(.none)` to the end of the arguments because you forgot to delete that placeholder after implementing support for rendering a field) then you got a less-scrutable `ArrayIndexOutOfBoundsException` from  `IonRawBinaryWriter_1_1.stepOut()` when it tried to work with the presence bitmap.
Please let me know if this is not the right fix or not the right place for the fix, etc. 

Fail more gracefully for a too-many-arguments case

---

src/main/java/com/amazon/ion/impl/IonReaderContinuableCoreBinary.java
src/main/java/com/amazon/ion/impl/IonReaderTextSystemX.java
src/main/java/com/amazon/ion/impl/macro/EExpressionArgsReader.java
src/main/java/com/amazon/ion/impl/macro/SystemMacro.kt
src/test/java/com/amazon/ion/impl/IonRawTextReaderTest_1_1.java
src/test/java/com/amazon/ion/impl/IonReaderContinuableTopLevelBinaryTest.java

I wanted to verify #962 works properly for text too, and in adding those tests I found missing support for system macro invocations and implicit rest parameters, added here.

Adds support for reading text Ion 1.1 system macros and implicit rest parameters.

---

src/main/java/com/amazon/ion/impl/IonCursorBinary.java
src/test/java/com/amazon/ion/impl/IonReaderContinuableTopLevelBinaryTest.java

Fixes #963 by properly setting the cursor's checkpoint after reading tagged values in an expression group.

---

src/main/java/com/amazon/ion/impl/macro/MacroEvaluator.kt
src/main/java/com/amazon/ion/impl/macro/ParameterFactory.kt
src/main/java/com/amazon/ion/impl/macro/SystemMacro.kt
src/test/java/com/amazon/ion/impl/macro/MacroEvaluatorTest.kt

None
* Adds implementations of `make_field`, `make_blob` and `repeat`.
* Both `make_field` and `repeat` need to be able to track some state over their evaluation, so I added a field to `ExpansionInfo` that `Expanders` can use for that purpose rather than having to create a pool of various `Expander` instances.
* There are a few drive-by fixes
* in `MacroEvaluator`, updated `MakeStringExpander` and `MakeSymbolExpander` to not accept `null`, as per the spec.
* in `MacroEvaluatorTest`, updated comments to have the `(%x)` syntax for argument expansion.

Adds implementations of repeat, make_field, and make_blob

---

src/main/java/com/amazon/ion/impl/IonCursorBinary.java
src/main/java/com/amazon/ion/impl/IonReaderContinuableCoreBinary.java
src/main/java/com/amazon/ion/impl/IonReaderTextSystemX.java
src/main/java/com/amazon/ion/impl/bin/IonRawBinaryWriter_1_1.kt
src/main/java/com/amazon/ion/impl/macro/MacroCompiler.kt
src/test/java/com/amazon/ion/impl/EncodingDirectiveCompilationTest.java

Includes various small fixes for tagless parameters, expression groups, and system macro invocations. See comments inline for a guide.

Includes various small fixes for tagless parameters, expression groups, and system macro invocations.

---

src/main/java/com/amazon/ion/impl/EncodingDirectiveReader.kt
src/main/java/com/amazon/ion/impl/IonReaderContinuableCoreBinary.java
src/main/java/com/amazon/ion/impl/IonReaderTextSystemX.java
src/main/java/com/amazon/ion/impl/macro/MacroEvaluatorAsIonReader.kt
src/test/java/com/amazon/ion/impl/EncodingDirectiveCompilationTest.java

Builds on #973 to allow the readers to correctly interpret the `set_macros`, `add_macros`, `set_symbols`, and `add_symbols` system macros as encoding directives. 
As noted in the JavaDoc atop the EncodingDirectiveReader class, this PR includes some duplication between the top-level `EncodingDirectiveReader` and the one built into the core binary reader. We have a path to unifying these implementations in the future, but that is out of scope for this PR.

Allows readers to interpret macro invocations as encoding directives.

---

src/main/java/com/amazon/ion/impl/IonCursorBinary.java
src/main/java/com/amazon/ion/impl/macro/EncodingContext.kt
src/test/java/com/amazon/ion/impl/EncodingDirectiveCompilationTest.java

Fixes reading of macro table appends.

---

src/main/java/com/amazon/ion/impl/IonRawTextWriter_1_1.kt
src/main/java/com/amazon/ion/impl/IonReaderContinuableCoreBinary.java
src/main/java/com/amazon/ion/impl/PrivateIonRawWriter_1_1.kt
src/main/java/com/amazon/ion/impl/SystemSymbols_1_1.kt
src/main/java/com/amazon/ion/impl/bin/IonManagedWriter_1_1.kt
src/main/java/com/amazon/ion/impl/bin/IonRawBinaryWriter_1_1.kt
src/main/java/com/amazon/ion/impl/macro/MacroCompiler.kt
src/main/java/com/amazon/ion/impl/macro/SystemMacro.kt
src/test/java/com/amazon/ion/impl/bin/IonManagedWriter_1_1_Test.kt

*Issue #, if available:* NA
* Add a definition of `default`
* Use qualified module reference for system macros where relevant
* Support use of system macros in TDL
* Updating system symbols to match spec as of now
* Associate SystemMacro values directly with SystemSymbols_1_1 values
* Add SystemSymbol lookup by name

Various changes in support of system macros

---

src/main/java/com/amazon/ion/impl/IonCursorBinary.java
src/main/java/com/amazon/ion/impl/IonReaderContinuableTopLevelBinary.java
src/test/java/com/amazon/ion/impl/IonReaderContinuableCoreBinaryTest.java
src/test/java/com/amazon/ion/impl/IonReaderContinuableTopLevelBinaryTest.java

With the addition of e-expressions, this new code path is exercised. Before e-expressions, an optimization within the reader would have already filled the values in the container, if possible, causing a previous branch to be taken. I added a TODO to apply this optimization to e-expressions too, but that's out of scope for this PR.

Fixes a bug that caused the binary reader to prematurely assume EOF had been reached in an e-expression.

---

src/main/java/com/amazon/ion/impl/IonReaderContinuableCoreBinary.java
src/main/java/com/amazon/ion/impl/macro/ReaderAdapterContinuable.kt
src/test/java/com/amazon/ion/impl/IonReaderContinuableTopLevelBinaryTest.java

Closes #984
The top-level binary reader implementation calls `fillValue()` before materializing scalar values. However, the `ReaderAdapterContinuable` operates over the core-level reader. Therefore, it must explicitly fill the scalar values it materializes. This adapter is used by both the `EExpressionArgsReader` and the `MacroCompiler`. The fix allows the reader to read from data that is not entirely present in the buffer up-front.

Ensures that macro arguments are present in the binary reader's buffer before attempting to materialize them.

---

src/main/java/com/amazon/ion/impl/IonReaderContinuableCoreBinary.java
src/main/java/com/amazon/ion/impl/SystemSymbols_1_1.kt
src/main/java/com/amazon/ion/impl/bin/IonManagedWriter_1_1.kt
src/test/java/com/amazon/ion/impl/bin/IonManagedWriter_1_1_Test.kt

Rather than rendering an encoding context directive the managed writer now uses `set_symbols`, `set_macros`, `add_symbols`, or `add_macros` as appropriate. Symbols and macros are not set until the user defines a symbol or macro- until that point system symbols and macros are still more succinctly expressible. 

Use add/set_macros/symbols in ManagedWriter

---

src/main/java/com/amazon/ion/impl/IonCursorBinary.java
src/main/java/com/amazon/ion/impl/TaglessEncoding.kt
src/main/java/com/amazon/ion/impl/bin/IonRawBinaryWriter_1_1.kt
src/main/java/com/amazon/ion/impl/macro/Macro.kt
src/main/java/com/amazon/ion/impl/macro/ParameterFactory.kt
src/main/java/com/amazon/ion/impl/macro/SystemMacro.kt
src/test/java/com/amazon/ion/impl/IonCursorBinaryTest.java
src/test/java/com/amazon/ion/impl/IonReaderContinuableCoreBinaryTest.java
src/test/java/com/amazon/ion/impl/bin/IonManagedWriter_1_1_Test.kt
src/test/java/com/amazon/ion/impl/bin/IonRawBinaryWriterTest_1_1.kt

Names like `compact_int` are out of date; the spec now says e.g. `flex_int`. See [E-expressions#Tagless Encodings](https://amazon-ion.github.io/ion-docs/books/ion-1-1/binary/e_expressions.html#tagless-encodings)

Rename compact_* parameter encodings to flex_*

---

src/main/java/com/amazon/ion/impl/IonReaderContinuableApplicationBinary.java
src/main/java/com/amazon/ion/impl/IonReaderContinuableCore.java
src/main/java/com/amazon/ion/impl/IonReaderContinuableCoreBinary.java
src/main/java/com/amazon/ion/impl/IonReaderNonContinuableSystem.java
src/main/java/com/amazon/ion/impl/SystemSymbols_1_1.kt
src/main/java/com/amazon/ion/impl/_Private_IonWriter.java
src/main/java/com/amazon/ion/impl/bin/IonManagedWriter_1_1.kt
src/test/java/com/amazon/ion/Ion_1_1_RoundTripTest.kt
src/test/java/com/amazon/ion/impl/IonReaderContinuableCoreBinaryTest.java
src/test/java/com/amazon/ion/impl/IonReaderContinuableTopLevelBinaryTest.java
src/test/java/com/amazon/ion/impl/bin/IonManagedWriter_1_1_Test.kt

* Write system symbol tokens using their SymbolSymbols_1_1 value, allowing binary to use the `0xEE` opcode and FlexSym system opcodes.
* Clean up / correct IVM writing.
* Clean up / correct context resetting when an IVM is encountered in both the application and system binary readers.
* Allow the core reader to resolve symbol text when it is available, which is only the case in Ion 1.1. This allows the system reader wrapper to correctly roundtrip Ion 1.1 data, though this is not the lowest-level transcode that can be done because it consumes encoding directives. A future PR will need to add an "encoding-level" transcode that can preserve encoding directives and macro invocations.
* Add tests to exercise the fixes.
By submitting this pull request, I confirm that …

Applies various fixes to writing and reading of Ion 1.1 system symbols in binary.

---

src/test/java/com/amazon/ion/conformance/Config.kt
src/test/java/com/amazon/ion/conformance/ConformanceTestBuilder.kt
src/test/java/com/amazon/ion/conformance/ConformanceTestDslInterpreterTest.kt
src/test/java/com/amazon/ion/conformance/ConformanceTestRunner.kt
src/test/java/com/amazon/ion/conformance/fragments.kt

None
* Updates the conformance test runner to support both `bytes` and `binary` for binary fragments. This is a temporary change until https://github.com/amazon-ion/ion-tests/pull/129 is merged and `ion-java` is updated to have the latest commit of `ion-tests`.
* Refactors `ConformanceTestRunner` into an abstract class. We can create one subclass for each reader configuration. This makes it easier to run a subset of tests (which is faster than running all of them) or to focus on a specific reader implementation. We can also have separate skip lists for the different readers if we so choose. It also means that the test report uses the reader configuration as the top level grouping rather than the very lowest level differentiator.
* …

Improve conformance test runner

---

src/main/java/com/amazon/ion/impl/EncodingDirectiveReader.kt
src/main/java/com/amazon/ion/impl/IonReaderContinuableCoreBinary.java
src/main/java/com/amazon/ion/impl/IonReaderTextSystemX.java
src/main/java/com/amazon/ion/impl/bin/IonManagedWriter_1_1.kt
src/main/java/com/amazon/ion/impl/macro/EncodingContext.kt
src/main/java/com/amazon/ion/impl/macro/MacroCompiler.kt
src/main/java/com/amazon/ion/impl/macro/MacroTable.kt
src/main/java/com/amazon/ion/impl/macro/MutableMacroTable.kt
src/main/java/com/amazon/ion/impl/macro/SystemMacro.kt
src/test/java/com/amazon/ion/impl/EncodingDirectiveCompilationTest.java

*Issue #, if available:* Fixes #993
*Description of changes:* 
Prior to this, the EncodingDirectiveReader implementations could only allow reference in TDL to macros defined in the encoding directive being read. Now, they can understand references to macros belonging to the currently-operative encoding context. 
- Adds a DEFAULT EncodingContext
- Adds a MacroTable abstraction
- Adds a SystemMacro MacroTable
The approach I've taken is to have immutable and mutable macro tables (presently only the SystemMacro macro table is immutable) and immutable and immutable encoding contexts. The default (static, shared) encoding context is immutable. 
When you want to append to it you create a new, mutable EncodingContext with a mutable macro table. The mutable macro table takes an antecedent table …

System macros in tdl

---

src/test/java/com/amazon/ion/conformance/expectations.kt

None.
Implements `denotes` for float, decimal, timestamp, and for structs that don't have duplicate field names.

Implement remaining 'denotes' expectations for conformance test runner

---

src/main/java/com/amazon/ion/MacroAwareIonReader.kt
src/main/java/com/amazon/ion/MacroAwareIonWriter.kt
src/main/java/com/amazon/ion/impl/IonCursorBinary.java
src/main/java/com/amazon/ion/impl/IonReaderContinuableApplicationBinary.java
src/main/java/com/amazon/ion/impl/IonReaderContinuableCoreBinary.java
src/main/java/com/amazon/ion/impl/_Private_IonReaderBuilder.java
src/main/java/com/amazon/ion/impl/bin/IonManagedBinaryWriter.java
src/main/java/com/amazon/ion/impl/bin/IonManagedWriter_1_1.kt
src/main/java/com/amazon/ion/impl/macro/IonReaderFromReaderAdapter.kt
src/main/java/com/amazon/ion/impl/macro/MacroEvaluator.kt
src/main/java/com/amazon/ion/impl/macro/MacroEvaluatorAsIonReader.kt
src/main/java/com/amazon/ion/impl/macro/ReaderAdapter.kt
src/main/java/com/amazon/ion/impl/macro/ReaderAdapterContinuable.kt
src/main/java/com/amazon/ion/impl/macro/ReaderAdapterIonReader.kt
src/test/java/com/amazon/ion/Ion_1_1_RoundTripTest.kt
src/test/java/com/amazon/ion/impl/EncodingDirectiveCompilationTest.java
src/test/java/com/amazon/ion/impl/IonReaderContinuableCoreBinaryTest.java
src/test/java/com/amazon/ion/impl/IonReaderContinuableTopLevelBinaryTest.java
src/test/java/com/amazon/ion/impl/bin/IonManagedBinaryWriterTest.java

Supports macro-aware transcoding from binary to text, preserving symbol tables, encoding directives, and e-expression invocations. Support for transcoding from text and to binary will be added in a future PR.
All of the API design and behavior introduced by this PR is negotiable. This is not considered a "public" API, so we have room to change it if necessary.
I deliberately did not try to build this into `IonWriter.writeValues(IonReader)`, which could be used for system-level transcoding of Ion 1.0 streams. That works well in Ion 1.0 because symbol tables are still part of the data model, and at the system level they just look like regular structs. E-expressions are different because they occur only in the encoding, not in the data model, and as a result there …

Adds support for macro-aware transcoding from binary to text.

---

src/main/java/com/amazon/ion/IonEncodingVersion.java
src/main/java/com/amazon/ion/apps/macroize/InvocationSubstitute.java
src/main/java/com/amazon/ion/apps/macroize/Macroize.java
src/main/java/com/amazon/ion/apps/macroize/MacroizeMacroMatcher.java
src/main/java/com/amazon/ion/apps/macroize/MacroizeSpec.java
src/main/java/com/amazon/ion/apps/macroize/ManualEncodingContext.java
src/main/java/com/amazon/ion/apps/macroize/PrefixTextPattern.java
src/main/java/com/amazon/ion/apps/macroize/SubstringTextPattern.java
src/main/java/com/amazon/ion/apps/macroize/SuggestedSignature.java
src/main/java/com/amazon/ion/apps/macroize/TextPattern.java
src/main/java/com/amazon/ion/apps/macroize/ThrowingProcedure.java
src/main/java/com/amazon/ion/apps/macroize/ThrowingSupplier.java
src/main/java/com/amazon/ion/apps/macroize/VerbatimTextPattern.java
src/main/java/com/amazon/ion/impl/bin/WriteBuffer.java
src/main/java/com/amazon/ion/impl/lite/IonDatagramLite.java
src/main/java/com/amazon/ion/impl/macro/MacroMatcher.java
src/test/java/com/amazon/ion/DatagramTest.java
src/test/java/com/amazon/ion/apps/macroize/MacroizeTest.java

This is an early (`v0.1`) version of the tool with many TODOs and known limitations (see the JavaDoc on MacroizeSpec.java). However, I think it's useful enough to make available now while we continue iterating. I also have a version of the tool that does basic macro detection, but that will be added in a future PR.
The tool may be invoked by building the ion-java jar and using
`java -cp ion-java.jar com.amazon.ion.apps.macroize.Macroize`

Adds a Macroize tool to enable conversion of Ion 1.0 data to Ion 1.1 using specified macros and text patterns.

---

src/main/java/com/amazon/ion/impl/IonCursorBinary.java
src/main/java/com/amazon/ion/impl/IonReaderContinuableCoreBinary.java
src/main/java/com/amazon/ion/impl/IonReaderTextSystemX.java
src/main/java/com/amazon/ion/impl/bin/IonManagedWriter_1_1.kt
src/main/java/com/amazon/ion/impl/macro/Expression.kt
src/main/java/com/amazon/ion/impl/macro/MacroCompiler.kt
src/main/java/com/amazon/ion/impl/macro/MacroEvaluator.kt
src/main/java/com/amazon/ion/impl/macro/MacroEvaluatorAsIonReader.kt
src/main/java/com/amazon/ion/impl/macro/ParameterFactory.kt
src/main/java/com/amazon/ion/impl/macro/SystemMacro.kt
src/test/java/com/amazon/ion/conformance/ConformanceTestRunner.kt
src/test/java/com/amazon/ion/conformance/expectations.kt
src/test/java/com/amazon/ion/conformance/fragments.kt
src/test/java/com/amazon/ion/impl/macro/MacroEvaluatorTest.kt

None
* Updates `ion-java` to a commit of `ion-tests` that includes system macro and other test cases.
* Implements the `make_timestamp`, `delta`, and `sum` system macros
* Updates the `repeat` system macro to be aligned with the specification (i.e. allow a repeat count of 0, and allow repeating an empty stream)
* Update all system macros to use tagged parameters
* Conformance runner improvements:
* Change `Annot` -> `annot` (for compliance with the spec)
* Adds support for `mactab` fragments
* Adds support for demangling E-expressions in `toplevel` fragments

Macro implementations and conformance test fixes

---

src/main/java/com/amazon/ion/SystemSymbols.java
src/main/java/com/amazon/ion/impl/EncodingDirectiveReader.kt
src/main/java/com/amazon/ion/impl/IonCursorBinary.java
src/main/java/com/amazon/ion/impl/IonReaderContinuableCoreBinary.java
src/main/java/com/amazon/ion/impl/IonReaderTextSystemX.java
src/main/java/com/amazon/ion/impl/SystemSymbols_1_1.kt
src/main/java/com/amazon/ion/impl/bin/IonManagedWriter_1_1.kt
src/main/java/com/amazon/ion/impl/macro/SystemMacro.kt
src/test/java/com/amazon/ion/Ion_1_1_RoundTripTest.kt
src/test/java/com/amazon/ion/impl/EncodingDirectiveCompilationTest.java
src/test/java/com/amazon/ion/impl/IonReaderContinuableApplicationBinaryTest.java
src/test/java/com/amazon/ion/impl/IonReaderContinuableCoreBinaryTest.java
src/test/java/com/amazon/ion/impl/IonReaderContinuableTopLevelBinaryTest.java
src/test/java/com/amazon/ion/impl/bin/IonManagedWriter_1_1_Test.kt
src/test/java/com/amazon/ion/impl/bin/IonRawBinaryWriterTest_1_1.kt
src/test/java/com/amazon/ion/impl/macro/MacroEvaluatorTest.kt

None
Changes `$ion_encoding` to the default module as described in https://github.com/amazon-ion/ion-docs/pull/369
This does not implement any new functionality. It just makes the current functionality match the new syntax.

Use default module instead of $ion_encoding

---

src/main/java/com/amazon/ion/MacroAwareIonReader.kt
src/main/java/com/amazon/ion/impl/IonReaderContinuableCoreBinary.java
src/main/java/com/amazon/ion/impl/_Private_IonReaderBuilder.java
src/test/java/com/amazon/ion/Ion_1_1_RoundTripTest.kt
src/test/java/com/amazon/ion/impl/EncodingDirectiveCompilationTest.java
src/test/java/com/amazon/ion/impl/IonReaderContinuableCoreBinaryTest.java

* Value-by-value transcoding allows for the user to stop transcoding after a certain number of user values have been transcoded. ion-java-benchmark-cli makes use of this when `--limit` is specified. It also uses it for `--ion-flush-period`, which requires the writer to be flushed every N values.
* The reader builder has been generalized to create MacroAwareIonReaders using the same compression and format detection logic as the regular readers. This allows macro-aware transcoding to be performed on both `byte[]` and `InputStream`. We now also parameterize the macro-aware transcoding tests in `EncodingDirectiveCompilationTest` to cover all combinations of input type (`byte[]` or `InputStream`) and output format (binary or text). Once support for macro-aware …

Allows values to be macro-aware transcoded value-by-value, adds support for creating macro-aware readers from InputStream, and improves testing.

---

src/main/java/com/amazon/ion/impl/IonReaderTextSystemX.java
src/main/java/com/amazon/ion/impl/IonReaderTextUserX.java
src/main/java/com/amazon/ion/impl/_Private_IonReaderBuilder.java
src/main/java/com/amazon/ion/impl/_Private_IonReaderFactory.java
src/main/java/com/amazon/ion/impl/macro/EExpressionArgsReader.java
src/test/java/com/amazon/ion/impl/EncodingDirectiveCompilationTest.java
src/test/java/com/amazon/ion/impl/IonRawTextReaderTest_1_1.java

Builds on #1000 and #1005.
Supports macro-aware transcoding from text, preserving symbol tables, encoding directives, and e-expression invocations. This will be useful for:
* Allowing human-authored macros to be transcoded directly to binary for size/performance testing.
* Allow text Ion 1.1 to be re-written with pretty printing without evaluating e-expressions.
This change required moving a few symbol table-related methods from the user reader to the system reader, as we had to do in binary. That's because Ion 1.1 e-expressions need to be interpreted at the system level (because they may expand to system values), and may therefore affect the encoding context (including the symbol table).
By submitting this pull request, I confirm that my contribution is made …

Adds support for macro-aware transcoding from text.

---

src/main/java/com/amazon/ion/impl/_Private_IonTextWriterBuilder_1_1.java
src/main/java/com/amazon/ion/impl/bin/ManagedWriterOptions_1_1.kt
src/test/java/com/amazon/ion/impl/EncodingDirectiveCompilationTest.java

I noticed this when implementing macro-aware transcoding. When transcoding from binary, where symbol IDs are generally available, those symbol IDs were being transcoded to text using symbol identifier syntax, e.g., `$1`. This was due to an incorrect default in the Ion 1.1 text writer builder.
After this change, transcoded text Ion 1.1 goes from looking like this:
```
$ion_1_1 (:$ion::set_symbols (:: "foo" "bar")) $1 $2 (:$ion::add_symbols (:: "baz")) $1 $3 (:$ion::set_symbols (:: "abc" "def")) $1 $2 
```
To this:
```
$ion_1_1 (:$ion::set_symbols (:: "foo" "bar")) foo bar (:$ion::add_symbols (:: "baz")) foo baz (:$ion::set_symbols (:: "abc" "def")) abc def 
```
These two streams are data model equivalent, but the latter is easier for humans to read. Anyone who …

Makes the Ion 1.1 text writer write symbol tokens inline by default, instead of using symbol identifiers.

---

ion-java-cli/src/main/java/com/amazon/tools/cli/OutputFormat.java

Simplify ion-java-cli OutputFormat

---

src/main/java/com/amazon/ion/impl/macro/EExpressionArgsReader.java
src/main/java/com/amazon/ion/impl/macro/MacroEvaluatorAsIonReader.kt
src/test/java/com/amazon/ion/impl/EncodingDirectiveCompilationTest.java

Before the fix, the reader would add duplicate FieldName expressions in cases like the one illustrated by the added test.

Fixes a bug that prevented nested struct macro invocations from being evaluated properly.

---

src/main/java/com/amazon/ion/impl/IonCursorBinary.java
src/main/java/com/amazon/ion/impl/IonReaderContinuableApplicationBinary.java
src/main/java/com/amazon/ion/impl/IonReaderContinuableCoreBinary.java
src/main/java/com/amazon/ion/impl/macro/EExpressionArgsReader.java
src/test/java/com/amazon/ion/impl/EncodingDirectiveCompilationTest.java
src/test/java/com/amazon/ion/impl/IonCursorBinaryTest.java
src/test/java/com/amazon/ion/impl/IonReaderContinuableTopLevelBinaryTest.java

This PR ensures that binary macro invocations can be filled and skipped, regardless of whether they are delimited or length-prefixed, and regardless of the types of arguments they contain. The bulk of the additions in this PR are added test cases to exercise the various combinations.
I've also included some TODOs to be left for future PRs. We generally need more coverage of early-step-out cases when evaluating macros, and we need to add more testing of the continuable reader when input runs out at various locations within a macro invocation.

Fixes various implementation gaps and bugs related to skipping and filling binary macro invocations.

---

src/main/java/com/amazon/ion/impl/IonCursorBinary.java
src/test/java/com/amazon/ion/impl/IonReaderContinuableTopLevelBinaryTest.java

*Description of changes:* A few suggestions from #1022, and comment updates. 

Suggestions from PR #1022

---

src/main/java/com/amazon/ion/impl/IonReaderContinuableCoreBinary.java
src/test/java/com/amazon/ion/impl/IonReaderContinuableTopLevelBinaryTest.java

Fixes #1023
Before this change, if `stepOut()` was called while the reader was evaluating a macro, that `stepOut()` would always be passed along to the MacroEvaluator. However, If the macro produced a stream of values (e.g. `delta`) instead of a container, then this would fail. After this change, in this case, the reader should terminate evaluation and step out of the container in which the macro invocation occurs.

Adds support for early step out of macro invocations that expand to streams.

---

src/main/java/com/amazon/ion/impl/macro/MacroEvaluator.kt

Profiling showed significant time being spent in IdentityHashMap methods here. This PR proposes using a simple boolean check. I measured performance using ion-java-benchmark-cli over some real-world data containing many macro invocations.
Before: 311 ms/op
After: 269 ms/op (-13.5%)

Optimizes membership checking for the MacroEvaluator Session's ExpansionInfo pool.

---

src/main/java/com/amazon/ion/impl/IonReaderContinuableCoreBinary.java
src/main/java/com/amazon/ion/impl/IonReaderTextSystemX.java
src/main/java/com/amazon/ion/impl/macro/EExpressionArgsReader.java

Currently, `EExpressionArgsReader.beginEvaluatingMacroInvocation` is not called recursively and performs eager materialization, so it is possible to reuse a single list. When we move away from eager materialization of e-expression arguments, this will change (if it's still relevant).
Results:
253 ms / op -> 250 ms/op (-1.2%)
Allocation rate: 219 KB/op -> 201 KB/op (-8.2%)

Reuses the EExpressionArgsReader's list of expressions instead of allocating a new one for each invocation.

---

src/main/java/com/amazon/ion/impl/macro/Environment.kt
src/main/java/com/amazon/ion/impl/macro/MacroEvaluator.kt

`IntArray.toList()` was showing up fairly significantly in allocation profiles. Simply changing to `IntArray.asList()` gets most of the same benefit. The proposed solution is slightly better and enables removal of an existing TODO in the code. More significant improvements are likely to be achieved via pooling.
Speed: 250 ms/op -> 250 ms/op (0%)
Allocation: 201 KB/op -> 194 KB/op (-3.5%)

Uses the MacroEvaluator's argument indices IntArray as-is instead of allocating a new List.

---

src/main/java/com/amazon/ion/impl/macro/EExpressionArgsReader.java

64 performed slightly better and resulted in a lower allocation rate for my sample of real-world data. We can continue to tune this as we test with a wider variety of sample data, but smaller data generally will not suffer from a larger initial size here (within reason). Performance plateaued at 64 for my data.
Speed: 250 ms/op -> 248 ms/op (-<1%)
Allocation rate: 194 KB/op -> 189 KB/op (-2.6%)

Tunes the initial size of the EExpressionArgReader's expressions ArrayList.

---

src/main/java/com/amazon/ion/impl/IonReaderTextUserX.java
src/test/java/com/amazon/ion/TextSpanHoistingTest.java

Fixes #1042
I'm truly not sure if there is impact with the bug, but the fix is trivial, so it seemed best just to fix it.

Fix Hoisted Text Span Symbol Table Bug

---

src/main/java/com/amazon/ion/impl/IonReaderTextSystemX.java
src/test/java/com/amazon/ion/IntTest.java
src/test/java/com/amazon/ion/streaming/ReaderIntegerSizeTest.java

This PR fixes the integer size calculation for `IonReader.getIntegerSize()`.
*List of changes:*
- Adds changes for integer boundary check
- Adds tests for within the boundary values

Fixes `IonReader.getIntegerSize()` calculation

---

.github/workflows/main.yml
.gitignore
build.gradle.kts

This cherry-picks improvements to our build process etc. from the `ion-11-encoding` branch:
- #848
- #949 
- #1027
There are several more build process improvements not taken from that branch, but they generally relate to Kotlin code and concerns not yet present in `master` and we can integrate those changes with the rest of the Ion 1.1 changes when we merge them.

Build cherry picks

---

.github/workflows/codeql-analysis.yml
.github/workflows/main.yml
build.gradle.kts

- Removes JDK 8 from the build, while still targeting Java 8. 
- Pins CodeQL build to Java 11 instead of letting it autodetect (it tends to settle on Java 8 because we target taht)
- Upgrades JMH from version 0.7.2 to version 0.7.3
- Upgrades Spotless from version 6.11.0 to version 7.0.2
- Additionally, disable :spotbugsJmh as otherwise it gets stuck trying to use Java 8 spotbugs to analyze classes from latter JDKs
These combined changes are necessary to get our release build to work while building with modern JDKs.

Upgrade plugins and JDKs for build stability

---

.github/workflows/main.yml
build.gradle.kts

*Description of changes:* #1061 set the compiler for the toolchain used to Java 8 (see JavaCompile task [docs](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.compile.JavaCompile.html#org.gradle.api.tasks.compile.JavaCompile:javaCompiler)). Rather, we should use the `release` flag to target the Java version we want, which ensures the specified language level is used regardless of which compiler actually performs the compilation. 
As the Building Java Projects Gradle [docs](https://docs.gradle.org/current/userguide/building_java_projects.html#sec:compiling_with_release) say:
> The `release` flag provides guarantees similar to toolchains. It validates that the Java sources are not using language features introduced in later Java versions, and also that the code does not access APIs …

Use '--release' flag to target Java 8

---

src/test/java/com/amazon/ion/conformance/ConformanceTestRunner.kt
src/test/java/com/amazon/ion/conformance/expectations.kt
src/test/java/com/amazon/ion/conformance/structure.kt

None.
* Refactors handling of expectations so that `not` and `and` will cause a specific test to be skipped rather than balking for the whole test file.
* Fixes `denotes (Decimal ...` implementation so that it can distinguish between positive and negative 0 and so that the exponent is compared using the right type.
* Adds some new test cases to the skip list (for now).

Fixes denotes expectation for Decimal and other minor improvements

---

src/main/java/com/amazon/ion/IonCursor.java
src/main/java/com/amazon/ion/impl/IonCursorBinary.java
src/main/java/com/amazon/ion/impl/IonReaderContinuableApplicationBinary.java
src/main/java/com/amazon/ion/impl/IonReaderContinuableCoreBinary.java
src/main/java/com/amazon/ion/impl/IonReaderContinuableTopLevelBinary.java
src/main/java/com/amazon/ion/impl/IonReaderNonContinuableSystem.java
src/main/java/com/amazon/ion/impl/lite/IonLoaderLite.java
src/main/java/com/amazon/ion/impl/macro/ReaderAdapterContinuable.kt
src/test/java/com/amazon/ion/impl/IonCursorBinaryTest.java
src/test/java/com/amazon/ion/impl/IonCursorTestUtilities.java
src/test/java/com/amazon/ion/impl/IonReaderContinuableCoreBinaryTest.java

None.
Change `IonCursor.Event` from an enum to a class containing `static final byte`s to improve performance of reading Ion binary.
| Git Ref                             |            Ion 1.0 |             Ion 1.1 |
|:------------------------------------|-------------------:|--------------------:|
| ion-java@1.11.10         | `122.392 ±  2.965` |                 N/A |
| HEAD of ion-11-encoding branch (after merging #1071) | `135.759 ±  9.804` | `147.104 ±  9.982` |
| This PR                 | `114.862 ±  2.747` |  `136.631 ± 11.923` |
Most (maybe even all) of this difference comes just from changing `Event`, but I changed the other two anyway. For some reason, if I only change `Event`, the Ion 1.1 performance is about 10% worse, but I …

Change `Event` and other `IonCursorBinary` enums to byte constants

---

.github/workflows/ion-java-performance-regression-detector.yml

None
* Refactors common elements out of the "use case" in the strategy matrix. This is because the individual workflow tasks get the strategy values appended to the display name in GitHub, and by removing the common stuff, we can actually get useful names. See for example [this workflow run](https://github.com/amazon-ion/ion-java/actions/runs/14786765939), where all of the tasks have a truncated name like "Detect Regression (nestedStruct, read --mode AverageTime --forks 3 --warmups 2 --iterations 10 -...". By refactoring it, we should get useful names like "Detect Regression (nestedStruct, read --api streaming)".
* One of the "common" things was not actually in common between all of the configurations. The `read` tests were not using …

Improve performance regression detector workflow

---

src/main/java/com/amazon/ion/IonReader.java
src/test/java/com/amazon/ion/IonReaderCloseableTest.java

Fixes #1059: Make IonReader extend AutoCloseable for proper resource management
*Issue #1059 
*Description of changes:* 
This change enhances the IonReader interface with comprehensive documentation for the close() method to clarify resource management behavior and enable proper try-with-resources usage. The interface already extended Closeable (which extends AutoCloseable), but lacked explicit documentation about the close() method contract.

Add documentation for IonReader.close() method

---

.github/workflows/ion-test-driver.yml

See: https://docs.github.com/en/actions/reference/security/secure-use#good-practices-for-mitigating-script-injection-attacks
These changes prevent potential script injection attacks by ensuring that the GitHub context values are stored in intermediate environment variables and used as variables rather than being directly interpolated into shell scripts. This follows the security best practice recommended in the GitHub documentation.

Follows best practices for mitigating script injection attacks in GitHub Actions workflows.

---

.github/workflows/main.yml
ion-java-cli/src/main/java/com/amazon/tools/cli/OutputFormat.java
src/test/java/com/amazon/ion/impl/IonReaderBinaryLargeStreamTest.java

None.
Copies changes from `ion-11-encoding` branch back over to `master`.
All commits have links to the prior PRs that approved the changes.

Copies changes from `ion-11-encoding` branch that are not specific to Ion 1.1

---

src/main/java/com/amazon/ion/impl/IonReaderContinuableApplicationBinary.java
src/main/java/com/amazon/ion/impl/IonReaderContinuableTopLevelBinary.java
src/main/java/com/amazon/ion/impl/LocalSymbolTable.java
src/main/java/com/amazon/ion/impl/_Private_ByteTransferReader.java
src/main/java/com/amazon/ion/impl/_Private_LocalSymbolTable.java
src/main/java/com/amazon/ion/impl/bin/AbstractIonWriter.java
src/main/java/com/amazon/ion/impl/bin/IonManagedBinaryWriter.java
src/test/java/com/amazon/ion/impl/OptimizedBinaryWriterSymbolTableTest.java
src/test/java/com/amazon/ion/impl/OptimizedBinaryWriterTestCase.java

Resolves #381 
This optimization allows for byte-copy from the reader's binary Ion stream to the writer's binary Ion stream under the following conditions:
* The reader's data source is a byte array
* The reader's symbol table is a subset of the writer's symbol table (i.e. all of the symbol IDs in the source point to the same text in the destination context, though the destination context may have additional symbol IDs with mappings)
* The value to be copied is not annotated (sidesteps annotation wrapper merging)
* The reader is not in a struct (sidesteps verbatim field name transfer)
These requirements can be difficult to satisfy (particularly the symbol table requirement, because it requires using some advanced APIs), but when satisfied …

Resurrect copy optimization

---

src/main/java/com/amazon/ion/impl/bin/AbstractIonWriter.java

In #790 (released in 1.11.5) we made `IonWriter.writeValues(IonReader)` iterative instead of recursion in order to eliminate unbounded recursion from the library.
While working on #1093 I noticed that this had caused negative performance impact for certain datasets:
Dataset: deeply nested single value
Benchmarking code: [ion-java-benchmark-cli](https://github.com/amazon-ion/ion-java-benchmark-cli/tree/read-tests-writevalues), modified so that the `read` command tests `IonWriter.writeValues(IonReader)` with stream copy optimization *disabled*. I will formally add an option to the tool that does this in a separate PR.
CLI command: `./benchmark-cli read --mode AverageTime --time-unit microseconds --iterations 2 --warmups 2 --forks 2 --ion-reader non_incremental …

Shortens AbstractIonWriter.writeValues, allowing the JIT to optimize it more efficiently, improving performance by up to 12%.

---

src/main/java/com/amazon/ion/BufferConfiguration.java
src/main/java/com/amazon/ion/IonBufferConfiguration.java

Errors from `IonBufferConfiguration.build()` did not specify that OversizedSymbolTableHandlers are required in addition to OversizedValueHandlers if a maximum buffer size is set because the parent BufferConfiguration created the error message, which only knows about OversizedValueHandlers. This updates the error message to indicate that both are required.

Specify that OversizedSymbolTableHandler is required for limited buffers

---

build.gradle.kts
config/proguard/rules.pro
src/main/java/com/amazon/ion/_private_/SuppressFBWarnings.kt
src/main/java/com/amazon/ion/bytecode/BytecodeGenerator.kt
src/main/java/com/amazon/ion/bytecode/BytecodeIonReader.kt
src/main/java/com/amazon/ion/bytecode/bin10/ByteArrayBytecodeGenerator10.kt
src/main/java/com/amazon/ion/bytecode/bin10/InputStreamBytecodeGenerator10.kt
src/main/java/com/amazon/ion/bytecode/bin11/ByteArrayBytecodeGenerator11.kt
src/main/java/com/amazon/ion/bytecode/bin11/InputStreamBytecodeGenerator11.kt
src/main/java/com/amazon/ion/bytecode/bin11/OpCode.kt
src/main/java/com/amazon/ion/bytecode/ir/Debugger.kt
src/main/java/com/amazon/ion/bytecode/util/AppendableConstantPoolView.kt
src/main/java/com/amazon/ion/bytecode/util/ByteSlice.kt
src/main/java/com/amazon/ion/bytecode/util/BytecodeBuffer.kt
src/main/java/com/amazon/ion/bytecode/util/ConstantPool.kt
src/test/java/com/amazon/ion/bytecode/util/BytecodeBufferTest.kt
src/test/java/com/amazon/ion/bytecode/util/ConstantPoolTest.kt

None
* Key Changes
* Adds `BytecodeGenerator` interface 
* Adds `BytecodeBuffer`, based on `IntList`, this is specialized for building up bytecode as efficiently as possible
* Adds `ConstantPool`, a specialized List-like collection for use as the bytcode's constant pool
* Adds `OpCodes`, which has constants for reading Ion 1.1 binary data
* Adds `ByteSlice` for representing lobs in the constant pool
* Stubs
* `BytecodeIonReader`
* `ByteArrayBytecodeGenerator10`
* `ByteArrayBytecodeGenerator11`
* `InputStreamBytecodeGenerator10`
* `InputStreamBytecodeGenerator11`
* Incidental Changes
* Replaces our `@SuppressFBWarnings` lookalike with a `compileOnly` dependency on the annotation vended by SpotBugs.
By submitting this pull request, I …

Adds stubs for BytecodeGenerators and BytecodeIonReader and core pieces for their interactions
