.gitmodules, README.md
Cleans up some references.
Makes the submodule refer to the HTTP URL for the repository.
Fixes #67
=> Cleans up README.md and ion-tests submodule.

.travis.yml
Tested on my user fork in Travis CI:
https://travis-ci.org/almann/ion-java
=> Adds Travis CI configuration.

README.md
Adds project badges for easy access to Maven Central anJavadoc in README.
See rendered version at:
https://github.com/almann/ion-java/tree/badges
=> Adds Maven Central and Javadoc Badges.

test/software/amazon/ion/SystemProcessingTestCase.java
The test is validating correct behavior and it's passing
=> Removing @Ignore from valid test

src/software/amazon/ion/ValueFactory.java
PR to address Todd's comments on https://github.com/amzn/ion-java/issues/42, since it was merged before he the chance to review it 
original change: https://github.com/amzn/ion-java/commit/3026661ef926f5823987cb8644f2c96a7a801023#diff-7d0bcbafb673d6fd55f9ac96b4097993
=> Allow Empty symbols, toddjonker review

src/software/amazon/ion/impl/IonReaderBinaryRawX.java, test/software/amazon/ion/TestUtils.java
https://github.com/amzn/ion-java/issues/55
=> Caught binary nested annotation error, removed nested test from skip list

test/software/amazon/ion/TestUtils.java
was added back by mistake in a bad merge
=> removing bad/annotationNested.10n from skip list

src/software/amazon/ion/impl/lite/IonContainerLite.java, test/software/amazon/ion/TestUtils.java
Adding a check to only perform the SID lookups if and only if we don't
have a name. If we have a name simply copying the name is sufficient
=> Performance improvment for struct clones

src/software/amazon/ion/IonLoader.java, src/software/amazon/ion/IonSequence.java, src/software/amazon/ion/IonValue.java, src/software/amazon/ion/Timestamp.java, src/software/amazon/ion/system/IonBinaryWriterBuilder.java, src/software/amazon/ion/util/Equivalence.java
=> miscellaneous javadoc cleanup

src/software/amazon/ion/impl/IonReaderBinarySystemX.java, test/software/amazon/ion/TestUtils.java
https://github.com/amzn/ion-java/issues/138
See title, spec: Spec: http://amzn.github.io/ion-docs/docs/binary.html#2-and-3-int
=> Throwing for negative zero in binary

src/software/amazon/ion/Decimal.java
You can use ternary expressions, if you only return a conditional value
No known issue
Changed some if statements to ternary expressions
=> changed some if-statements to ternary expressions

.travis.yml
Enable pushing coverage to codecov
Enable codecov
=> (Build) Enable codecov

src/software/amazon/ion/impl/IonReaderTextRawTokensX.java, src/software/amazon/ion/impl/IonReaderTextSystemX.java, test/software/amazon/ion/BadIonTest.java, test/software/amazon/ion/TestUtils.java
#99 
Throws error when reading clobs with non ascii characters
=> Clob nonascii error 99

src/software/amazon/ion/Timestamp.java, test/software/amazon/ion/TimestampTest.java
In #195, the `Timestamp.add*` methods were changed to extend the resulting Timestamp's precision when called on a less-precise timestamp, addressing #136. For example, calling `addMonth` on a Timestamp with only `YEAR` precision will return a Timestamp with `MONTH` precision. Previously, a Timestamp truncated to `YEAR` precision was returned. This change provides the old behavior as an option that can be accessed through the `Timestamp.adjust*` suite of methods.
Note: there are a lot of diffs in TimestampTest, but it's more complicated than it looks because I did a refactor to remove a lot of duplicated code. The `testAdjust*` tests are copied from the`testAdd*` tests as of the [revision before #195](https://github.com/amzn/ion-java/blob/b73931ead1c0e8da6dbcd9e079 …
=> Adds Timestamp.adjust* methods, which perform date arithmetic without extending precision.

pom.xml
=> Bumps version to 1.3.0

README.md
=> Updates README.md to refer to 1.3.0.

pom.xml
=> Bumps version to 1.3.1-SNAPSHOT.

README.md, pom.xml
=> Bumps version to 1.3.1.

README.md, pom.xml
=> Release 1.4.0

pom.xml
=> adding SNAPSHOT suffix in pom.xml

README.md
=> Adding groupId change notice to Readme.md

src/com/amazon/ion/impl/IonReaderTextRawX.java, src/com/amazon/ion/impl/IonReaderTextSystemX.java, test/com/amazon/ion/RoundTripTest.java
https://github.com/amzn/ion-java/issues/237
=> Triggers sid resolution when getting annotations in text documents

src/com/amazon/ion/util/Equivalence.java, test/com/amazon/ion/util/EquivalenceTest.java
When experimenting with writing single-precision Ion floats, I realized that many such floats were not comparing equivalent after round trip. That's because `IonReader.doubleValue` extends the value to double-precision, which can result in a value that is slightly different than the original single-precision input. Specifying an epsilon to be used when comparing these values allows the user to opt in to ignoring this small difference.
To avoid telescoping static methods, I added a builder. To avoid ballooning method signatures, I added a configuration object (note: for the existing static methods, the configuration is constant). New options (e.g. giving "timestamp instant equals" its own option independent of "strict") should be added to the builder. Most …
=> Adds an Equivalence option to specify an epsilon to use when comparing float values.

src/com/amazon/ion/impl/bin/IonRawBinaryWriter.java
`ContainerInfo` is a mutable internal class that is used to maintain state about a container, annotation, decimal, or timestamp. Instances are stored in a stack, previously using a `LinkedList`. A new instance was created and pushed onto the stack on every `stepIn`, `writeDecimal` (except when the value was null or zero), `writeTimestamp` (except when the value was null), and whenever a value had at least one annotation. On each corresponding `stepOut`, or on the completion of the value, the instance at the top of the stack was popped and released for garbage collection. This led to `ContainerInfo`s and the `LinkedList.Node`s used to wrap them accounting for a significant portion of the total allocations in applications that write long streams of binary Ion data. …
=> Makes IonRawBinaryWriter reuse ContainerInfo objects, reducing allocations and garbage.

src/com/amazon/ion/impl/bin/IonRawBinaryWriter.java
…cutting down on allocations and garbage caused by autoboxing.
`currentFieldSid` gets set every time the user sets a field name on the binary writer, which must happen before every value that is contained in a struct. Previously, an `Integer` was used to hold the current field symbol ID, with `null` indicating that no symbol ID had been assigned to the current value. However, because field name symbol IDs must be positive, a negative number can be used for this purpose, allowing for an `int` primitive to be used.
Boxing an `int` into an `Integer` each time a field name is set can have a real impact on applications that produce long streams of binary Ion data. Profiling such an application revealed that `Integer` boxing from this code path was IonJava's largest …
=> Makes IonRawBinaryWriter's currentFieldSid an int primitive instead of an Integer

.travis.yml, README.md, pom.xml
Bumps the version to 1.5.0 in preparation for release.
=> Release 1.5.0

pom.xml
=> Bumps version to 1.5.1-SNAPSHOT.

README.md, pom.xml
=> Release 1.5.1

pom.xml
Update pom.xml to next SNAPSHOT version 
=> Update pom.xml to next SNAPSHOT version 

pom.xml
Moves to new sonatype (Nexus) URL for publishing ion-java
=> Move to new sonatype URL

src/com/amazon/ion/impl/bin/IonRawBinaryWriter.java
This PR optimizes the process by which the binary IonWriter writes strings.
Performance is substantially improved for Strings small enough to benefit from buffer re-use. Strings that are too large to fit in the buffer see only a modest benefit.
&nbsp; | Time Required | GC Time
| ----------- | :--------------: | :---------: |
| Before | 1,396.812 ± 95.650 ms/op | 5,771ms | 
| After | 804.164 ± 32.502 ms/op | 844ms | 
| &nbsp; | 42.43% faster | 85.38% lower |
&nbsp; | Time Required | GC Time
| ----------- | :--------------: | :---------: |
| Before | 569.213 ± 3.963 ms/op | 0ms | 
| After | 401.250 ± 23.278   ms/op | 0ms | 
| &nbsp; | 29.51% faster | 0% lower |
&nbsp; | Time Required | GC Time
| ----------- | :--------------: | :---------: |
| Before | 1,083.512 ± 41.708 ms/op | 455ms | 
| …
=> Optimizations for writing binary strings.

src/com/amazon/ion/impl/bin/IonRawBinaryWriter.java
The benchmark used for #268 had an irregularity: it wrote millions of values without ever calling `finish()` on the IonWriter, causing thousands of pages of ~32k buffer space to be created and reclaimed on each iteration. This meant that there was an intense amount of GC happening that was not related to the core functionality being tested.
The PR introduced three string size categories: `SMALL`, `MEDIUM`, and `LARGE`. The `SMALL` category (`length()` <= `64` chars) was especially beneficial when the garbage collector was under heavy load. However, a corrected version of the benchmark that calls `ionWriter.finish()` every 100 values reduced that GC to zero.
Since the common use case will be to _not_ buffer 100s of MBs of data without ever flushing, I've merged …
=> Simplified string encoding.

src/com/amazon/ion/IonWriter.java, src/com/amazon/ion/impl/_Private_IonBinaryWriterBuilder.java, src/com/amazon/ion/impl/bin/IonManagedBinaryWriter.java, src/com/amazon/ion/impl/bin/_Private_IonManagedBinaryWriterBuilder.java, src/com/amazon/ion/system/IonBinaryWriterBuilder.java, test/com/amazon/ion/impl/BinaryWriterTest.java, test/com/amazon/ion/impl/IonWriterTestCase.java, test/com/amazon/ion/impl/bin/IonManagedBinaryWriterTest.java
=> Disables LST append writing by default and adds option to enable it

README.md, pom.xml
=> Release 1.6.0

pom.xml
=> Fixing staging nexus URL

pom.xml
=> Adding SNAPSHOT version suffix

src/com/amazon/ion/impl/bin/PooledBlockAllocatorProvider.java
Quick fix to stop memory leaks. Addressing Issue #225 will help decide
on what to do with the block allocator implementations in the long term.
=> Fix(allocator): Allow GC on freed blocks over 64MB

README.md, pom.xml
=> Release 1.6.1

pom.xml
=> Create next SNAPSHOT v.1.6.2

src/com/amazon/ion/impl/IonWriterSystemText.java, test/com/amazon/ion/impl/IonMarkupWriterTest.java, test/com/amazon/ion/impl/TextWriterTest.java
=> Adds a space after a fieldname's colon when pretty-printing

src/com/amazon/ion/IonWriter.java
Inspired by this question: https://github.com/amzn/ion-java/issues/10#issuecomment-671154715
=> Remove comment suggesting `IonWriter` isn't stable

README.md, pom.xml
=> prepare new release 1.7.0

pom.xml
=> creates v1.7.1-SNAPSHOT

README.md, pom.xml
=> Preparing release 1.7.1

pom.xml
=> prepare 1.7.2-SNAPSHOT

ion-java-cli/pom.xml, ion-java-cli/src/com/amazon/tools/cli/CommandType.java, ion-java-cli/src/com/amazon/tools/cli/CompareContext.java, ion-java-cli/src/com/amazon/tools/cli/ComparisonType.java, ion-java-cli/src/com/amazon/tools/cli/IonJavaCli.java, ion-java-cli/src/com/amazon/tools/cli/NoCloseOutputStream.java, ion-java-cli/src/com/amazon/tools/cli/NoOpOutputStream.java, ion-java-cli/src/com/amazon/tools/cli/OutputFormat.java, ion-java-cli/src/com/amazon/tools/cli/ProcessContext.java, ion-java-cli/src/com/amazon/tools/comparisonReport/ComparisonContext.java, ion-java-cli/src/com/amazon/tools/comparisonReport/ComparisonResult.java, ion-java-cli/src/com/amazon/tools/comparisonReport/ComparisonResultType.java, ion-java-cli/src/com/amazon/tools/errorReport/ErrorDescription.java, ion-java-cli/src/com/amazon/tools/errorReport/ErrorType.java, ion-java-cli/src/com/amazon/tools/events/Event.java, ion-java-cli/src/com/amazon/tools/events/EventType.java, ion-java-cli/src/com/amazon/tools/events/ImportDescriptor.java, pom.xml
This PR Implemented ion-java-cli version one which supports process and compare command.
1. Ion-java-cli is a subproject of ion-java. Build logic is in ion-java/ion-java-cli/pom.xml.
2. Process/compare logic are in ionJavaCli.java, Refer [ion-test-driver](https://github.com/amzn/ion-test-driver) for more details.
Files from [ion-tests](https://github.com/amzn/ion-tests)
=> ion-java-cli (java implementation for ion-test-driver)

.github/ISSUE_TEMPLATE.md, .github/workflows/main.yml
refer to https://github.com/amzn/ion-java/pull/325 for details.
PR to update testing branch.
=> Changed repository to amzn and added open issue logic.

.github/ISSUE_TEMPLATE.md, .github/workflows/main.yml
Refer to https://github.com/amzn/ion-java/pull/325 for details.
=> Integrate ion test driver

.github/workflows/main.yml
Refer to https://github.com/amzn/ion-java/pull/325 for more details.
=> Able to upload file to artifacts.

.github/workflows/main.yml
Refer to https://github.com/amzn/ion-java/pull/325 for details.
=> Allow async PR.

ion-java-cli/src/com/amazon/tools/cli/IonJavaCli.java
Refer https://github.com/amzn/ion-java/pull/325 for details.
=> Disable process, should raise errors.

ion-java-cli/src/com/amazon/tools/cli/IonJavaCli.java
Refer to https://github.com/amzn/ion-java/pull/325 for more details.
=> mack process error.

ion-java-cli/src/com/amazon/tools/cli/IonJavaCli.java
https://github.com/amzn/ion-java/pull/325
=> Embedded error, should raise an error.

.github/ISSUE_TEMPLATE.md, .github/workflows/main.yml, ion-java-cli/src/com/amazon/tools/cli/IonJavaCli.java
https://github.com/amzn/ion-java/pull/325
=> Ready for CR.

.github/workflows/main.yml
https://github.com/amzn/ion-java/pull/325
=> Fixed diff repo issue.

.github/workflows/main.yml
https://github.com/amzn/ion-java/pull/325
=> Added cat step and changed reference name.

README.md, pom.xml
=> Prepare new release 1.8.0

pom.xml
=> Prepare 1.8.1-SNAPSHOT

.github/workflows/ion-test-driver.yml
=> Using --replace option in GH Actions to avoid ion-test-driver async issue.

README.md, pom.xml
None.
Preparing to publish release 1.8.1
=> Preparing release 1.8.1

README.md, pom.xml
None
Bumps version to `1.8.2-SNAPSHOT`
=> Bumps version to 1.8.2-SNAPSHOT

README.md, pom.xml
This will be the last commit before release 1.8.2 is tagged.
=> Prepares version 1.8.2 for release.

pom.xml
=> Prepares 1.8.3-SNAPSHOT

README.md, pom.xml
=> Prepares version 1.8.3 for release.

pom.xml
=> Bumps version to 1.8.4-SNAPSHOT

.github/workflows/codeql-analysis.yml
N/A
Adds static code analysis to detect code weaknesses/vulnerabilities.
=> Adds CodeQL analysis

src/com/amazon/ion/Timestamp.java
N/A
Adds explicit narrowing casts to resolve the code weaknesses found by CodeQL in #409 
=> Adds explicit narrowing casts in Timestamp

README.md, pom.xml
=> Prepares version 1.9.1 for release.

pom.xml
=> Bumps version to 1.9.2-SNAPSHOT

README.md, pom.xml
=> Release 1.9.3

pom.xml
=> Bump version to 1.9.4-SNAPSHOT

test/com/amazon/ion/impl/IonReaderBinaryIncrementalTest.java
Fixes an incorrect comment identified in #426.
=> Fixes an incorrect comment in IonReaderBinaryIncrementalTest.

README.md, pom.xml
=> Prepares version 1.9.4 for release.

README.md, pom.xml
Prepares version 1.9.5 for release.
=> Prepares version 1.9.5 for release.

pom.xml
Bumps version to 1.9.6-SNAPSHOT
=> Bumps version to 1.9.6-SNAPSHOT

.github/workflows/ion-java-performance-regression-detector.yml
N/A
This change was made along with this [PR](https://github.com/amzn/ion-java-benchmark-cli/pull/49). After updating, there will be more test data which mimic the real world data to be used for ion-java benchmark process. 
=> Adds real-world-data schema to generate more test data.

test/com/amazon/ion/impl/IonRoundtripConcurrencyStressTest.java
Removes one space. Getting a review because that's policy 😭.
=> Trivial indentation fix

.github/workflows/main.yml, build.gradle.kts
*Issue #, if available:* #472 
*Description of changes:* Save SpotBugs reports with GHA runs
=> Save SpotBugs reports with GHA runs

CONTRIBUTING.md
#484 
All `http` changed to `https`.
=> Use https links in CONTRIBUTING.md

.github/workflows/ion-java-performance-regression-detector.yml, .github/workflows/ion-test-driver.yml
N/A
This PR updates the trigger events of `ion-java-regression-detection` and `ion-test-driver` to make sure these workflows can be triggered appropriately.
=> Update workflow trigger events.

build.gradle.kts
None
When updating to use Kotlin, the publish artifacts were not correctly updated. This updates the publishing to use the minified Jar. This PR also cleans up some unnecessary complexity in the javadoc and source jar tasks.
=> Fix publish artifacts

build.gradle.kts
Fixes #547 
Adds `Automatic-Module-Name` and OSGi bundle attributes to the Jar manifest file.
=> Adds automatic module name and OSGi bundle headers

src/test/java/com/amazon/ion/impl/IonReaderBinaryLargeStreamTest.java
No issue number.
This one test class is really slow, so I've made it only run one a CI environment. GitHub Actions (and others) set `CI=true` to signal to build systems that it is a CI environment.
If you do want to run this test locally for some reason, you can run `export CI=true` before running `./gradlew test`.
While I was doing this, I upgraded the whole test class to use JUnit5 API and swapped `"UTF-8"` for `StandardCharsets.UTF_8`.
=> Skips IonReaderBinaryLargeStreamTest unless running on CI server

src/main/java/com/amazon/ion/impl/bin/IonManagedWriter_1_1.kt
Related PR: #854 
Performance measured by https://github.com/amazon-ion/ion-java-benchmark-cli/tree/ion-1-1 using a 20MB binary Ion log file (all symbol tokens interned).
Command:
```
ion-java-benchmark-cli write --warmups 2 --iterations 2 --forks 2 --mode AverageTime --io-type file --ion-minor-version 1 log.10n
```
Before this PR:
701 ms / op
After this PR:
195 ms / op
For reference, Ion 1.0:
210 ms / op
=> Avoids an O(n) lookup for symbols newly added to the Ion 1.1 writer, improving performance.

src/main/java/com/amazon/ion/apps/macroize/MacroizeMacroMatcher.java, src/main/java/com/amazon/ion/impl/bin/IonManagedWriter_1_1.kt, src/main/java/com/amazon/ion/impl/macro/MacroCompiler.kt, src/main/java/com/amazon/ion/impl/macro/MacroRef.kt, src/main/java/com/amazon/ion/impl/macro/SystemMacro.kt, src/test/java/com/amazon/ion/conformance/ConformanceTestRunner.kt, src/test/java/com/amazon/ion/impl/macro/MacroCompilerTest.kt
none
* Updates `MacroRef` to support qualified references
* Adds support for the `literal` special form
* Updates to the latest commit of `ion-tests` and updates the skip-list in the conformance test runner.
=> Implements `literal` special form

src/main/java/com/amazon/ion/impl/EncodingDirectiveReader.kt, src/main/java/com/amazon/ion/impl/IonReaderContinuableCoreBinary.java, src/main/java/com/amazon/ion/impl/SystemSymbols_1_1.kt, src/main/java/com/amazon/ion/impl/bin/IonManagedWriter_1_1.kt, src/main/java/com/amazon/ion/impl/macro/SystemMacro.kt, src/test/java/com/amazon/ion/conformance/ConformanceTestRunner.kt, src/test/java/com/amazon/ion/impl/EncodingDirectiveCompilationTest.java, src/test/java/com/amazon/ion/impl/IonReaderContinuableApplicationBinaryTest.java, src/test/java/com/amazon/ion/impl/IonReaderContinuableCoreBinaryTest.java, src/test/java/com/amazon/ion/impl/IonReaderContinuableTopLevelBinaryTest.java, src/test/java/com/amazon/ion/impl/bin/IonManagedWriter_1_1_Test.kt, src/test/java/com/amazon/ion/impl/bin/IonRawBinaryWriterTest_1_1.kt, src/test/java/com/amazon/ion/impl/bin/WriteBufferTest.java, src/test/java/com/amazon/ion/impl/macro/MacroEvaluatorTest.kt
None
* Update ion-java with changes from amazon-ion/ion-docs#390
=> Update ion-java with changes from amazon-ion/ion-docs#390
